### ISSUE TITLE
Show a number beside the games

### ISSUE THREAD

**Issue by ajayyy** [ludumdare/ludumdare#1003]
Like, 1st place, 2nd place etc. And maybe show a gold medal.

Like the old site:

![image](https://cloud.githubusercontent.com/assets/12688112/26330882/270aaf12-3f1c-11e7-999c-6de897238c7e.png)

**Comment by Cerno-b** [comment]
I had the same thought. There could be different icons, one per category and each in three colors: gold, silver, bronze. The icons you win are displayed as an overlay on top of your game thumbnail. If there is space left, the overall rank could also be displayed, maybe restricted to the top 100 games. Or there could be other achievements with special icons, like top 10 game, top 25 game, top 50 game, top 100 game.

**Comment by povrazor** [comment]
?

![troyhee](https://user-images.githubusercontent.com/1570313/27363847-cd5bb81c-5604-11e7-8c5b-af6b809cf9cf.png)

**Comment by ajayyy** [comment]
Yea, this can be closed now

**Comment by ajayyy** [comment]
Nevermind, I'm going to reopen this for having the medals appear in the game view too. (Where the results are)
