### ISSUE TITLE
Change commenting 'upvote' to a more neutral icon

### ISSUE THREAD

**Issue by Jezzamonn** [ludumdare/ludumdare#1005]
Sometimes there is useful, but not positive feedback, that you want to say "Thank you, this is helpful" to, or "Yes, I agree with this". The heart icon doesn't feel fitting for these cases. Additionally, positive, but useless comments shouldn't really get upvotes if they're used to determine game rankings.

Here are two hypothetical comments:

> OMG awesome game!! Please make more!!!

> I can see you spent a lot of time working on graphics for this game, but the game is way too difficult, and the instructions are unclear. Next time you should get someone to play your game during the competition, and see how they find the game.

It feels weird giving a <3 to the second one, but it seems more deserving of recognition

**Comment by Samusoidal** [comment]
I think that the heart represents your support of the commenter's attitude (i.e. his honesty).

**Comment by povrazor** [comment]
There were similar concerns a long time ago about comments "for a laugh"

**Comment by zwrawr** [comment]
People complained when twitter changed to a heart icon. But they only complained for a week or two before it became normal.
![image](https://cloud.githubusercontent.com/assets/18352787/26461383/efce2762-4174-11e7-9010-9009b8482051.png)

**Comment by Jezzamonn** [comment]
Sorry, I should've marked that this is an idea, not a "THIS NEEDS TO BE DONE" type thing :P  I wanted to get people's feedback on this idea.

I guess my main concern is the case maybe what Mike is hinting at? Where someone posts a funny comment, that gets a lot of likes, which means their game gets more ratings. It doesn't really make sense to reward people for doing that in that way. Maybe the real issue is rewarding games for each comment upvote...

**Comment by povrazor** [comment]
Noted. I'm going to close this for now, but we'll keep listening. IMO a :+1: and a :heart: are the same thing (rather, I treat them as the same). AFAIK the "comedian" problem was never actually a problem (humour doesn't come easy in the written word).
