### ISSUE TITLE
Redirecting /games?

### ISSUE THREAD

**Issue by pfefferminzz** [ludumdare/ludumdare#1006]
The games page https://ldjam.com/games is not useful until LD 39.
I'd suggest to redirect it to the LD 38 games page https://ldjam.com/events/ludum-dare/38/games
until the pages
- https://ldjam.com/events/ (probably not needed at the moment)
- https://ldjam.com/events/ludum-dare/
- https://ldjam.com/events/ludum-dare/39
- and a navigation to those pages

exist.

**Comment by local-minimum** [comment]
I talked to Mike about that and https://ldjam.com/games this isn't actually where the voting should be done, but the hub for all games. So it should look entirely different from what it does now.

**Comment by pfefferminzz** [comment]
I know it's meant to be the hub for all games, but at the moment, there are only LD 38 games and the /games page has less features than the /events/ludum-dare/38/games page. So a redirect would be a perfect solution. As long as they are _almost_ the same, we could just use the page which is better.

**Comment by zwrawr** [comment]
This will be less of an issue once event browsing is a thing.

`/events` will show a list of all game jam events that have happened (LD's, mini, october and eventually others)

`/events/ludumdare` will show a list of all ludumdares that have happened
`/events/mini-ld` (or something) will show a list of all mini LD's that have happened

`/groups/ludumdare` should all also show some stuff about it.

**Comment by pfefferminzz** [comment]
> This will be less of an issue once event browsing is a thing.
[...]

I agree, this sounds all nice, but at the moment, in my opinion, it _is_ an issue which could easily be solved, temporarily. At this moment, `/events/ludum-dare/38/games` is simply the better version of `/games`.
