### ISSUE TITLE
Medals?

### ISSUE THREAD

**Issue by pfefferminzz** [ludumdare/ludumdare#1011]
I saw the medals on the old LD site. It would be cool to have those medals back in the LD 38 games overview. Maybe in this direction:

![ld-gsb](https://cloud.githubusercontent.com/assets/5459440/26375690/35323008-400a-11e7-9b6d-944e3449d230.png)

![ld-g](https://cloud.githubusercontent.com/assets/5459440/26375698/3e0b6ed8-400a-11e7-8945-356f9584bd1a.png)  ![ld-s](https://cloud.githubusercontent.com/assets/5459440/26375736/59c028d0-400a-11e7-95ff-26018b8bdd3d.png) ![ld-b](https://cloud.githubusercontent.com/assets/5459440/26375759/6f774fdc-400a-11e7-8cc8-73d30082e7b7.png)

I had fun creating the following medals, but they did not exactly turn out as expected. 😅 I'm sure someone will come up with better medals.

![ld-medals](https://cloud.githubusercontent.com/assets/5459440/26375044/b257eee0-4007-11e7-99a7-105a9c0f98af.png)

![ld-gold](https://cloud.githubusercontent.com/assets/5459440/26375058/bcfe9a24-4007-11e7-8c06-d27216e72f2c.png) ![ld-silver](https://cloud.githubusercontent.com/assets/5459440/26375065/c481f872-4007-11e7-9522-069b72e01a00.png) ![ld-bronze](https://cloud.githubusercontent.com/assets/5459440/26375083/d586ecfe-4007-11e7-92e6-de95260bed4b.png)

**Comment by zwrawr** [comment]
Those graphics are really nice. 
Not sure if the quite fit the flat theme of the site though.

It would be cool if we got different people to make the medals for each ld.

**Comment by ajayyy** [comment]
The different LD medals is a really good idea! And, I think it will really add to the page. Right now, the results page looks kind of bland with just grey and dark grey, a medal would really stand out in a good way.

**Comment by pfefferminzz** [comment]
I agree, they clash with the flat design. I just wanted to pixel something.

**Comment by pfefferminzz** [comment]
A fast way to add medals would be using the trophy icon which is already used in the Jam and Compo button. You could add a CSS shadow for better visibility on bright backgrounds.

![ld-trophy](https://cloud.githubusercontent.com/assets/5459440/26377133/5614ffd0-400f-11e7-9ac2-7f87ad8dcba1.png)

**Comment by ajayyy** [comment]
Great idea! Those look perfect.

**Comment by ajayyy** [comment]
Here's another cool style:

https://ldjam.com/events/ludum-dare/38/cryodream-2/podium-dare-38-windows

**Comment by povrazor** [comment]
![trophy](https://cloud.githubusercontent.com/assets/1570313/26427718/000dcf16-40ac-11e7-9269-9f8420ec35f1.png)

**Comment by pfefferminzz** [comment]
Thank you! 😃

**Comment by Cerno-b** [comment]
Having the medals designed by people on LD (maybe one of the winners of last LD) would be really cool, but in order the keep the design coherent, maybe some design guidelines would need to be written.

**Comment by povrazor** [comment]
The Trophy Rack is going to change things, so I'd rather keep this simple for now.

**Comment by local-minimum** [comment]
I'd say it's good enough to close this issue! One minor thing would be it would feel more right if the medals came sorted by value (all gold first, then silver, last bronze), but it isn't all that important.

**Comment by local-minimum** [comment]
I made suggestion for medal sorting here https://github.com/ludumdare/ludumdare/pull/1028
