### ISSUE TITLE
[UI] Automatically set the `Currently On` flair based off of the featured event 

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#1012]
As said here https://ldjam.com/events/ludum-dare/38/antnator/how-to-get-to-the-results-page-without-knowing-the-actual-link
and in a few other places there's no way to get to the LD38 events page with out manually entering a url at the moment, because there is no events browser.

To fix this i suggest adding back the event flair to the top of the page with the `STAGE` being `Results` rather than the `Voting` it was before it was disabled.

**Comment by zwrawr** [comment]
Fixed by #1013 . Although iot might be worth keeping this open as a not to  "automate" this

**Comment by povrazor** [comment]
Yes, this is hacked in right now. It needs to be properly fixed.

**Comment by zwrawr** [comment]
This seems to be implemented in https://github.com/ludumdare/ludumdare/blob/master/src/com/header/whatsup/whatsup.js
This can probably be closed.
