### ISSUE TITLE
Support multiple events

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#1019]
Right now it's a weird hardcoded mess

**Comment by local-minimum** [comment]
This feels like it is an umbrella task for several minor tasks or is this only referring to the back-end ability to support more than one event? I think I'd in any case suggest listing the different aspects needed to resolve this so it is easier to help out.

**Comment by povrazor** [comment]
#784

**Comment by local-minimum** [comment]
Hoping it will help:

- [ ] `shrub/tools/theme/theme.php` uses `$EVENT_NODE` which is set from `$SH['ludumdare-event']` (should be called `$EVENT_ID` to match most common naming
- [ ] `shrub/tools/grade/grade.php` uses `$EVENT_ID` set from same above.
- [ ] `shrub/src/theme/theme_list_vote.php` uses `$event_id` in functions:
  - [ ] `themeListVote_CalculateScores` (not used in function)
  - [ ] `themeListVote_Add`
  - [ ] `themeListVote_GetByNodeUser`
- [ ] `shrub/src/theme/theme_list.php` uses $event_id in functions:
  - [ ] `themeList_Add`
- [ ] `shrub/src/theme/theme_idea_vote.php` uses `$event_id` in functions:
  - [ ] `themeIdeaVote_GetIdeas` (comment: This calls `themeIdea_GetOriginal` with user-id as 0)
  - [ ] `themeIdeaVote_GetMy`
  - [ ] `themeIdeaVote_Add`
  - [ ] `themeIdeaVote_Remove`
- [ ] `shrub/src/theme/theme_idea.php` uses `$event_id` in functions:
  - [ ] `_themeIdea_GetRandom`
  - [ ] `_themeIdea_Add`
  - [ ] `_themeIdea_AddWithLimit`
  - [ ] `themeIdea_GetStats`
  - [ ] `themeIdea_SetParent`
  - [ ] `themeIdea_Add`
  - [ ] `themeIdea_GetOther`
  - [ ] `themeIdea_GetDetail`
  - [ ] `themeIdea_CountUsers`
  - [ ] `themeIdea_CountOriginal`
  - [ ] `themeIdea_Count`
  - [ ] `themeIdea_GetOriginal`
  - [ ] `themeIdea_Get`
- [ ] `shrub/src/note/note_love.php` mentions `$event_id` in comments but never uses in code

- [ ] `shrub/js/theme/theme_list_vote.js` uses `event`  variable in `GetMy` in request to api using that event.
- [ ] `shrub/js/theme/theme_list.js` uses `event`  variable in `Get` in request to api using that event.
- [ ] `shrub/js/theme/theme_idea_vote.js` uses `event`  variable in:
  - [ ] `Get` in request to api using that event.
  - [ ] `GetMy` in request to api using that event.
- [ ] `shrub/js/theme/theme_idea.js` uses `event`  variable in:
  - [ ] `GetMy` in request to api using that event.
  - [ ] `Add` in request to api using that event.
  - [ ] `Remove` in request to api using that event.
- [ ] `shrub/js/theme/theme.js` uses `event`  variable in:
  - [ ] `GetStats` in request to api using that event.

- [ ] `com/header-whatsup/whatsup.js` **Has hardcoded a bunch of event references**
- [ ] `com/dialog-create/create.js` 
  - [ ] Could have text using the actual name of the current event, not just `"Create a game for the active event?"`
  - [ ] Uses `event_id` **set rather mysterically as** `var event_id = this.props.extra.length ? Number.parseInt(this.props.extra[0]) : 0;`
 - [ ] Has hard-coded title: ` new_props.title += ' '+ShowType+" for Ludum Dare 38";`
- [ ] `com/content/item/item.js`
  - [ ] **Uses hardcoded link to event post** `/events/ludum-dare/38/ludum-dare-dot-com`
  - [ ] Has a todo: ` // TODO: Re-enable this to allow event selection`
- [ ] `com/content-event/event.js` has ` // NOTE: THIS IS WRONG! We should be asking the event node (i.e. this) for `what`. Alas, with 1 event we can cheat`
- [ ] `com/content-event/event-list` has `var event_id = this.props.node.id;`
- [ ] `com/sidebar-upcoming/upcoming.js` has hardcoded commented out event info.
- [ ] `com/header-clock/clock.js` has an hardcoded `EventDate` commented out
- [ ] `com/contents-event/event.js`
  - [ ] has a bunch of  `EventBody` set using a `node`.
  - [ ] `onJoin` doesn't care what event you are looking at, it joins the featured event.
  - [ ] `render` has `ShowJoin` not check first if `node == root.featured` or maybe that is part of `node_CanCreate` but then I don't get the `featured` checks later...
- [ ] `com/contents-event/event-theme.js` has a bunch of  `ShowBody` set using a `node`.
- [ ] `shrub/src/jammer/constants.php` has `const SH_NODE_OTHER_DEMO = 37` and `const SH_NODE_OTHER_CRAFT = 38;`
- [ ] `internal/autoembed/twitter.txt` references LD38

I'll edit this with more, it feels like there are some files that should have used the word event or used them more times but these are all the events there are in `www/src`

**Comment by zwrawr** [comment]
If this is to support multiple events such as LD38/LD39/LD40 then this can be closed.
If this is to support multiple events such as LD/miniLD/october-challenge then were no where near.

**Comment by local-minimum** [comment]
Sound like the latter should have its own issue "support mini LD"

**Comment by povrazor** [comment]
Yes.
