### ISSUE TITLE
Scotchbox 3.0 has launched (and it might break everything)

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1036]
https://box.scotch.io/

Notably:
* PHP 7

**Comment by povrazor** [comment]
For obvious reasons (not free) we will not be supporting Scotchbox Pro.

**Comment by povrazor** [comment]
Yes it does break everything.

**Comment by povrazor** [comment]
[ButterBox](/povrazor/butterbox) is the result. After some iteration it is working as a standalone fork of ScotchBox. It contains more current versions of software (and I should upgrade NPM too).

This is now more important, 'cause it was discovered *Vagrant Cachier* was the source of some frustrating Windows VM bugs.

**Comment by zwrawr** [comment]
We are now using ScotchBox 3.0 on Ubuntu 16 with PHP 7.0
