### ISSUE TITLE
Make loved comments colourful

### ISSUE THREAD

**Issue by ajayyy** [ludumdare/ludumdare#1037]
On the old site when there are 4 or more likes: 
![image](https://user-images.githubusercontent.com/12688112/27803896-e46041f0-5ff9-11e7-8780-ba39eca07782.png)

Now, there is no colour change.

**Comment by local-minimum** [comment]
This should be really easy to fix in the render function adding a special style

**Comment by povrazor** [comment]
The red is too intense IMO. Any good post or comment should eventually break the threshold of "well loved". It should stand out versus others, but I think red might be too much.

When things are slow (between events), that means the front page gets filled with red posts.

**Comment by ajayyy** [comment]
The red with the gradient made it not too crazy on the original site, so I think just making the top #ff6a54 ish, and then making the rest of the post background #ffddd8 ish.

**Comment by local-minimum** [comment]
Maybe number of comments should count towards standing out too not only notes?

**Comment by ajayyy** [comment]
Yea I think 4 likes and 3 comments would be a good balance.
