### ISSUE TITLE
Can't Login in Tor Browser

### ISSUE THREAD

**Issue by krazyy1** [ludumdare/ludumdare#1053]
This is really annoying. After I type my username and password and press "Log In" the website reloads and I'm not logged in. This only happens in Tor Browser. There are some messages in the console but I have no idea what they mean or if it's normal.
```
[fetchData]
[fetchUser]
[fetchUser] caller_id: 0
[fetchUser] Done: 0
[constructor]
[fetchData]
[fetchUser]
[fetchRoot]
```

**Comment by povrazor** [comment]
That means your Tor security settings wont let the `https://api.ludumdare.com` cookies through. Regrettably I made a change to fix a different bug, and it doesn't seem to be helping.

**Comment by povrazor** [comment]
Yeah, I'm looking in to it. It probably wont happen until after the event though.

**Comment by pixlark** [comment]
Yep, I'm getting this issue in chrome. For some reason it's identifying the ldjam.com cookies as third-party so there's no way to login unless I enable third-party cookies from all sites.

**Comment by mn113** [comment]
In Chrome you can work-around it for now by going into Settings > Content Settings > Cookies and adding `api.ludumdare.com` to the Allow whitelist (assuming your login issue occurs on ldjam.com). There's no need to be accepting them from all third-party sites.
