### ISSUE TITLE
Theme Slaughter Toggle

### ISSUE THREAD

**Issue by pfefferminzz** [ludumdare/ludumdare#1059]
![ld-toggle](https://user-images.githubusercontent.com/5459440/28512101-b79ce238-7050-11e7-8eb9-4c6984765771.png)

Please add toggle buttons to make it possible to change/correct a recent theme slaughter decision.

**Comment by gonutz** [comment]
This is the same as [issue 325](https://github.com/ludumdare/ludumdare/issues/325).

**Comment by pfefferminzz** [comment]
Oops. My bad. I searched for "slaughter", but the search did not return anything. :(

**Comment by gonutz** [comment]
It's fine, you can just close this issue and maybe comment on the other one. Issue 325 is rather old but I guess it will go up in priority if enough people comment on it.
