### ISSUE TITLE
LD#38 games don't show ratings, only metrics

### ISSUE THREAD

**Issue by bremco** [ludumdare/ludumdare#1064]
LD#38 games had ratings a while ago, now only the metrics are printed.
Seen on Windows/Chrome and LinuxMint/Firefox.
![no_ratings](https://user-images.githubusercontent.com/30440932/28580844-f48a0c50-7160-11e7-85e7-6f73cef58507.png)

**Comment by local-minimum** [comment]
The game feed is probably still a bit of a hack because we have not yet implemented what stages events are in. It could probably be fixed if there was a check against current event and show full results if the game's event is not the current event.

**Comment by povrazor** [comment]
Game should know what they belong to. But yeah, the check is probably "if featured event" rather than "if my parent event".

**Comment by povrazor** [comment]
I believe this is fixed.

**Comment by bremco** [comment]
Confirmed!
