### ISSUE TITLE
'Your own' LD#38 game will only load after refresh

### ISSUE THREAD

**Issue by bremco** [ludumdare/ludumdare#1065]
Steps to reproduce:

 - log in
 - go to your own page
 - click games-button below
 - click on your own LD#38 game

Behaviour:

 Will only show the comments on initial load. Actual game-page loads on refresh.
![no_show](https://user-images.githubusercontent.com/30440932/28581002-64402264-7161-11e7-9c95-231e551392cc.png)

**Comment by povrazor** [comment]
Yep! Definitely a bug.

**Comment by povrazor** [comment]
This should be fixed.

**Comment by bremco** [comment]
Confirmed!
