### ISSUE TITLE
Emoticons regression

### ISSUE THREAD

**Issue by bremco** [ludumdare/ludumdare#1066]
Please see the attached picture, much clearer than anything I can write :-)
![no_sweat](https://user-images.githubusercontent.com/30440932/28581091-a35baf86-7161-11e7-8fe0-8604b7629a71.png)

**Comment by povrazor** [comment]
You probably mean `sweat_drops`, `droplet`, `sweat`, or `sweat_smile`, as per https://emoji.codes

Auto-completion of Emoji should help here (once implemented). That and the behaviour of an invalid Emoji Code should probably be different.

**Comment by bremco** [comment]
I probably did, my apologies for the spurious issue.
(You'd think I remember not correcting it after all.)

The proposed features/changes would be very welcome in any case! :-)

**Comment by povrazor** [comment]
Okay. `:bad_codes:` used to work correctly, so this was a regression. This is now fixed. Autocompletion has been moved to #1071.
