### ISSUE TITLE
Remove or update the outdated bit on the rules

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1068]
On https://ldjam.com/events/ludum-dare/rules there's a paragraph 

> Coming Soon: We will soon have a system in place that credits you for leaving good feedback on a game. > Details are still being worked out, but there will likely be Coolness bonuses.

That system is already implemented isn't it?

**Comment by povrazor** [comment]
Yes. The neighbouring paragraphs need to be updated accordingly too, mentioning that the standard sorting scheme prioritizes users that both rate AND leave good feedback.

**Comment by elpaxoudis** [comment]
Isn't this issue already solved?

**Comment by mikekasprzak** [comment]
Yes.
