### ISSUE TITLE
Emoji autocompletion

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1071]
When typing emoji codes (i.e. `:some_thing:`) you should get a live popup that shows auto-completion as you're typing. This will avoid issues like #1066, where assumptions are made regarding emoji codes.

**Comment by ajayyy** [comment]
What about @ tagging auto completion?

**Comment by povrazor** [comment]
Separate issue (now open #1072).

**Comment by mikekasprzak** [comment]
Working for comments, see new issue for posts.
