### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by romgerman** [ludumdare/ludumdare#1080]
It keep saying "Error: Unauthorized"
![image](https://user-images.githubusercontent.com/1517367/28726137-b30c5052-73c8-11e7-8cab-052b920fac54.png)

**Comment by povrazor** [comment]
Have you created an account on the new website yet? Several people have assumed we copied accounts over, but we didn't. You need to make a separate account on the new website. 

What we did do was if you had previous games on the old website, we reserved your username so nobody could take it from you.

If you login on the old website and go here:

http://ludumdare.com/compo/wp-admin/profile.php

You can check what e-mail address you used to sign up. If you use the same e-mail address to sign up on the new website, you'll be able to use your original username.

In time we'll be migrating the old games to the new website. Some folks have multiple accounts, so we'll be doing work there too to help resolve them. But at the moment the only website is still at ludumdare.com so we don't break every link on the internet to it.

**Comment by romgerman** [comment]
Thank you. I thought that i've created account but i was confused because there now two websites and i thought that i can use my account on both.

**Comment by povrazor** [comment]
Yep, you're not the only one. I should probably add a note to the login dialog.
