### ISSUE TITLE
Create Account: Step 2: This account can't be activated.

### ISSUE THREAD

**Issue by iszlonn** [ludumdare/ludumdare#1093]
When I try to create a new account on the new page, I get the activation link, click it and then get this message:
![image](https://user-images.githubusercontent.com/6363224/28745319-959adc4e-744c-11e7-94f4-4fb667a22313.png)

**Comment by povrazor** [comment]
Re-enter your e-mail address in the create-account field. I've seen this once before, and for some reason that cleared it up.

**Comment by iszlonn** [comment]
Well, that seem to have fixed it. Either that or simply being the fourth try. Thanks!!
