### ISSUE TITLE
Platforms and Tags we need

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1104]
Hello, as you may have seen we now have **Platforms** and **Tags** associated with games. These are used to further classify and sort games. Right now these lists are being edited manually.

**Please check** that a Platform or Tag isn't already on the list. This thread is here to inform us of Platforms and Tags we should support.

The purpose of Tagging is to group games that have things in common together. Tags should be broad enough to cover multiple games. Tags that cover only a single game or nearly all games aren't useful.

## Platforms
Platforms should be systems and hardware of significance (be it millions of units sold or other such notoriety). If there is a common umbrella term for a wide variety of systems, prefer that. Where needed, if a system had multiple names internationally, try to combine them in some reasonable way.

Good Examples:
* Windows
* Commodore 64
* Linux
* Amiga
* HTML5
* Super Nintendo/Famicom
* Sega Genesis/Mega Drive
* GameBoy Advance
* Atari 2600
* Atari (other)

Bad Examples:
* Amiga 3000 (all Motorola powered Amiga's are somewhat compatible)
* PlayStation 4 Pro (it's software compatible with the PlayStation 4, so prefer that)
* Windows 98 (Windows compatibility is pretty good, so getting this specific isn't necessary)

Debatable Examples:
* Atari 7800 (only 100k units produced, backwards compatible with the 2600. It is somewhat notable because it was the last Atari 8-bit system, followed 6 years later by the Jaguar. If and when somebody makes a game for it its chances go up)

## Tags
Tags should be distinguishing factors, be it features, genres, or special hardware required by the game.

Good Examples:
* VR
* Online Multiplayer
* Local Multiplayer
* Turn Based
* Gamepad
* Mouse
* Platformer
* First Person Shooter
* Shmup

Bad Examples:
* Unity (again, "tools used" are being handled differently)
* Playable (so are thousands of other games)

Debatable Examples:
* 5 Player Multiplayer (5 is a weird number. Aside from MOBA's and Bomberman, it's a rarely used figure. We need to be careful that a 5 player game isn't ignored by people looking at 4 player games, unless 5 are necessary) 
* Split Screen Multiplayer (Isn't this just the same thing as Local Multiplayer? Other than Turn Based, how else do you do it?)

**Comment by povrazor** [comment]
Hello. At the time of this comment, the feature isn't live yet. This is a placeholder. :)

**Comment by local-minimum** [comment]
Though they fall in the "don't use these tags" people that do Java many times write `.jar` as indicator of cross-platform. Equally so for `love`.

Equally confusing, `puzzlescript` games are basically a genre. So are `twines`.

**Comment by local-minimum** [comment]
As for more tags:

* AR
* Touch

* Dating-sim
* Typing-game
* Tower-defence
* RTS
* Action
* Story-rich
* Sim

Platform

* Android

**Comment by local-minimum** [comment]
For the more uncommon platform
* Pdf (either print and make the game, but it has happened that ppl make adventure games within a pdf)
