### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1129]
Ah oops, I couldn't find the bookmarks feature (I think it's mentioned part of something else).

Anyway, we need bookmarks. A friend sent me a link to his game, and I want to remember that I need to check it out.

https://ldjam.com/events/ludum-dare/39/$45423

**Comment by mikekasprzak** [comment]
#961

**Comment by local-minimum** [comment]
I close this since it seems to be just a special case of lists issue and now I edited that issue to contain the word bookmark, so this one here doesn't add much other than possible confusion.
