### ISSUE TITLE
Joining event after deadline?

### ISSUE THREAD

**Issue by pfefferminzz** [ludumdare/ludumdare#1138]
It seems i could still join the event?
So i could vote without having created a game.
Looks like a bug.

**Comment by local-minimum** [comment]
The event-state system isn't fully in place yet, but that should of course not be. We should be able to fix it by marking such as "unfinished" games for now.

**Comment by povrazor** [comment]
In the past whenever folks had a lot of trouble submitting, I tended to leave submissions open overnight until I wake up the next day. Submissions have now been closed.
