### ISSUE TITLE
Getting logged out too regularly

### ISSUE THREAD

**Issue by increpare** [ludumdare/ludumdare#1142]
What's the cookie's timeout?  Once a week strikes me as ok, but right now I seem to have to log in every day.

**Comment by local-minimum** [comment]
I have been meaning to issue this too, but I've been wondering if cookie-validation is tied to build version of the site and right now it is rebuilt rather frequently.

**Comment by Jezzamonn** [comment]
+1 I get logged out way too often

**Comment by povrazor** [comment]
It should be 2 days, but something has been kicking me out sooner.

**Comment by Jezzamonn** [comment]
2 days still seems really low. I very rarely have to log in to Facebook or
Twitter, they seem to have their refresh time longer than a month

**Comment by povrazor** [comment]
Well what it was supposed to do is refresh that 2 days every time you visit the website. So in practice you'd never notice that it was so short. But that refresh code is broken.

Also every time I reboot frontend server it should have logged you out, but for some reason it would immediately persist for me, and kick me off later.

Anyway, it's not clear what's wrong with login persistence.

**Comment by karai17** [comment]
You know, I haven't been logged out of Google in about 5 years. There is seriously no need to log people out on a regular basis. Also I am unsure how you are doing cookies, but the Lapis framework puts session data in a user cookie and signs the data with a secret token. That way if the server needs to be rebooted, users don't have to log back in. Hell I even wiped my test app and because I used the same secret key when I reconstituted the server, I remained logged in.

**Comment by karai17** [comment]
Signing a cookie also stops users from tampering with session data (such as giving themselves admin permissions or logging in with a different username) because changing any data would affect the generated hash.

**Comment by povrazor** [comment]
> You know, I haven't been logged out of Google in about 5 years

When was the last time you kept both your computer and your smartphone powered off for 1 week?

**Comment by karai17** [comment]
I visit twitter every few weeks or months, I stay logged in each time.

**Comment by povrazor** [comment]
You're lucky. I visit daily and need to log in again every few months.

**Comment by karai17** [comment]
Getting logged out of websites is one of the most frustrating first world problems I encounter. I get signed out of bato.to weekly regardless of how often I visit the site and it makes me very angry deep inside my soul. Hyperbole aside, is there a valid reason to log someone out besides "it seems like a valid security measure"?

I think cookies expiring after a month of inactivity would be okay if you really, really want them to expire. But anything less than that seems more like security theatre than actual security.

**Comment by zwrawr** [comment]
if you haven't logged-in in 5 years then you havent changed a password in 5
years... I'd go do that now.

**Comment by karai17** [comment]
Changing your password periodically does not enhance security unless your general security practices are poor to begin with. Assuming the service you are using uses a compatent hashing algorithm (if it uses one at all...), then brute forcing that password is gonna take years. If your password DOES get cracked, then you best not be using that password on other services. Changing that password every now and again isn't really gonna protect you. Ofcourse, if the service you are using gets hacked and their database stolen, yeah, change your (relevant) passwords to invalidate the old ones so they become useless to a hacker.

I assume Mike is using something like bcrypt and not md5 or SHA-1 for password hashing. bcrypt uses very strong and (relatively) slow hashing algorithms, iterates the hash thousands of times, and generates a unique salt for each hash. On top of that, I would expect Mike is also using a secret token that is LD-specific so even if LD was hacked, rainbow tables would be 100% useless.

The "slowness" of bcrypt is important here. Right now with a couple [Maxwell Titans](https://www.youtube.com/watch?v=7U-RbOKanYs), you can write simple CUDA programs that hash *billions* of strings per second. You can create a rainbow table for the entire 8 byte ASCII table in a second or two. Not so much with bcrypt, that number drops by several orders of magnitude making brute forcing virtually impossible.

tl;dr: Assuming Mike is using sensible security measures, and users use non-shit passwords, changing it periodically will do nothing to help you.

**Comment by povrazor** [comment]
> Getting logged out of websites is one of the most frustrating first world problems I encounter

Yeah I agree, it sucks. It does helps if logging back in is 1-click. I believe that part is working in Chrome, but I haven't looked in to it since we started making accounts.

Once I'm sure the persistence issues are solved, then I will likely bump the timeout to 1 week. That will mean that if you visit the site within a week, it'll keep you in (while invisibly generating a fresh key). 

We also need to get 2FA working. Though we're a low risk target (nothing to steal), I'm noticing way more attempts at to steal accounts from me. Fortunately Mojang and Nintendo have confirmations, or I'd have lost my Minecraft account and Pokemons.

**Comment by karai17** [comment]
I was just about to open an issue suggesting we set up 2fa. I 100% agree,
that is a super useful feature. I actually did have my Mc account stolen
but I recovered it without issue~

**Comment by blinry** [comment]
Now that #285 is fixed and we can log out manually, maybe it's time to make sure that users aren't logged out automatically each day? :) This is one of the biggest sources of frustration when using the site for me.

Ideally, the user would have to log in after missing a complete event or so, meaning the logout-on-no-activity duration should be set to 4 months. Are there any disadvantages to that?

**Comment by povrazor** [comment]
Yes, security.

The best way to keep a connection safe is to regularly randomize the
session keys. Right now the same key is used forever. What needs to happen
is after X hours, the key needs to be renewed, which means the expiration
can be reset too. Right now sessions have a 2 day timeout. I'm happy to
increase it, but I would be reluctant to go longer than a week.

Also Chrome users, the login/password remembering works fine. Firefox, last
I heard it doesn't.

**Comment by increpare** [comment]
> Also Chrome users, the login/password remembering works fine. Firefox,
last I heard it doesn't.
Also safari has problems with it for me.  The login setup right now with
the site is, um, not without its frustrations.

2017-12-07 18:28 GMT+01:00 Mike Kasprzak <notifications@github.com>:

> Yes, security.
>
> The best way to keep a connection safe is to regularly randomize the
> session keys. Right now the same key is used forever. What needs to happen
> is after X hours, the key needs to be renewed, which means the expiration
> can be reset too. Right now sessions have a 2 day timeout. I'm happy to
> increase it, but I would be reluctant to go longer than a week.
>
> Also Chrome users, the login/password remembering works fine. Firefox, last
> I heard it doesn't.
>

**Comment by povrazor** [comment]
Okay, I've opened a new issue for that #1501.

**Comment by Jezzamonn** [comment]
No other site that I use logs me out after less than a week, so surely this is a solved problem.

I did some searching... here's one recommendation? https://paragonie.com/blog/2015/04/secure-authentication-php-with-long-term-persistence#title.2

I'd love Ludum Dare to have a better login experience. If you could just open the site to the games page you already had bookmarked and start rating games straight away I'm sure we'd get more people doing it too

**Comment by karai17** [comment]
I really do believe that the security concerns are very over blown. I visit Amazon every few months and I ma never logged out. I have to re-authenticate to do particularily special things like view my orders or make a purchase, but that's because real personal information and credit card info is involved. I visit Reddit once every few months and again, I've never been logged out. Same with my Microsoft account, I probably use that a couple times a year at most and I've never had to log in after the first time unless I am accessing personal info.

If Amazon, Reddit, and Microsoft among many others think that this isn't a major issue, I'm gonna trust them on that.

**Comment by povrazor** [comment]
I'm repeating myself, but Google follows you around the internet. From their services like YouTube to Adsense, they unlike most companies have chances every hour to maintain a session (and randomize a session key). Amazon works around the issue by requiring you to re-login when you do something important (i.e. making a purchase, checking order history). Microsoft always makes me login (super frustrating, I know). Reddit doesn't need to care, because a Reddit account isn't an identity. They are throwaway.

Ludum Dare and game jamming is an identity for some folks. You brag about your accomplishments here. We don't keep information around of value around (other than your e-mail), but granting access to a Ludum Dare account provides edit privileges for that identity. We have a responsibility to protect that identity.

**Comment by zwrawr** [comment]
We should defo bump the expiry time to a week, that should keep an active user logged in through most of an event. (probably need a re-log for results)

Also it still seems that you may get logged out if the site is redeployed(rebuilt?)

**Comment by povrazor** [comment]
User Session ID's are store in Redis, but currently only on the live server (I haven't merged the change in to the VM config). So long as redis doesn't crash, it will maintain its data across reboots.

**Comment by karai17** [comment]
Why not store them in an encrypted cookie? That's what I do and it works
great. I can delete a docker container and redeploy and no one has to
notice. It's encrypted suing a server-side secret token so the session data
isn't modifiable by the user and is unique to their browser.


---
Landon Manning
lmanning17@gmail.com

**Comment by povrazor** [comment]
Because our code is public. If you know exactly what the unencrypted data should look like, all you need is 2-3 unique accounts, and you can reverse engineer the secret.

**Comment by karai17** [comment]
I don't think reverse engineering encryption is quite that simple. Do you
have any proofs of concept?


---
Landon Manning
lmanning17@gmail.com

**Comment by povrazor** [comment]
Are you familiar with the math formula `A + B = C`? If you know A and B, you can solve for C. Same as if you know A and C, you can solve B. At this point it's not even an encryption issue. It's arithmetic.

**Comment by karai17** [comment]
That is a gross oversimplification of the issue. The arithmetic involved in
reverse engineering the secret from a respectable encryption algorithm
would take billions of years to calculate, not a few minutes. You're
basically just brute forcing it, regardless of how many unique accounts you
have.


---
Landon Manning
lmanning17@gmail.com

**Comment by povrazor** [comment]
Yes it's an oversimplification, but it takes years to brute force when you have nothing. If you know what's inside an encrypted blob, plus how a blob is generated, that's child's play.

The only truly secure thing to do is hand out a unique key (AKA session ID). Worst case you can hack yourself.

**Comment by zwrawr** [comment]
The link @Jezzamonn suggested, recommends creating a long random token which is what you just suggested. Right?
So why don't we do that?

**Comment by povrazor** [comment]
We do generate random tokens (i.e. session Ids). The only thing we don't do is negotiate a new one every X hours to keep it fresh.

**Comment by zwrawr** [comment]
So you get logged out 2 days after you logged in, not 2 days after you last visited the site?

**Comment by povrazor** [comment]
Yes.

**Comment by zwrawr** [comment]
So bumping expiry to a week and implementing renegotiation, will massively reduce how annoying this issue is, maybe even mitigate it.

**Comment by povrazor** [comment]
Yes. It's literally a couple hours of work. It's an annoyance than an actual issue.

**Comment by zwrawr** [comment]
It's a big annoyance though, i think this should be prioritised after search is done.

**Comment by povrazor** [comment]
I more meant it's easy to do. Yes it's frustrating being logged out.

**Comment by ttencate** [comment]
> Because our code is public. If you know exactly what the unencrypted data should look like, all you need is 2-3 unique accounts, and you can reverse engineer the secret.

Are you familiar with [Kerckhoffs's Principle](https://en.wikipedia.org/wiki/Kerckhoffs's_principle)? Encryption algorithms are _already_ public. This doesn't make them any less secure, even if you have [crib](https://en.wikipedia.org/wiki/Known-plaintext_attack)s. State of the art ciphers like AES-256 are [not known to be vulnerable](https://crypto.stackexchange.com/questions/1512/why-is-aes-resistant-to-known-plaintext-attacks) to known-plaintext attacks.

Besides, the plaintext contents of the cookie are not even known to the attacker. It would contain a random session ID that is only stored in plaintext in the database, and never leaves the server. If we did reveal the plaintext contents, what would be the point of encrypting it in the first place?

The suggestion to store encrypted data (e.g. session ID) in a cookie is a very sensible one. Even Google does it this way. You only need to make sure the key is stored securely on your server, where nobody but the site administrators can access it.

**Comment by karai17** [comment]
^ Exactly this. Having a secret token on the server that only the server knows is how modern internet encryption works. This is also how securing passwords works, you throw a server-secret token (a pepper) in with the password to be hashed so even if a database is leaked, unless you have that token you basically cannot break a password.

```
let hash = bcrypt.digest("s3cur3p455" + "b3VpZ2hiaTt1Z2JsaWdiaXB1Z2JwaWd1YnA7aXVnYmhpO3VwZyBwaW91aCBwWzA5b2l1IHloOTgweWhwOXVocGhp", 12)
```
