### ISSUE TITLE
Livestream module

### ISSUE THREAD

**Issue by karai17** [ludumdare/ludumdare#1153]
The new livestream module seems to have a very negative impact on views. In previous LDs, when I woudl be playing games and inviting people to share their games to be played and rated on stream, I would have a healthy number of folks popping in and out of my stream, sharing games, chatting, etc. Since using the new website, that all but doesn't happen. I was streaming for about 2 hours the other day and had 3 people drop in during the whole stream. The new module really highlights the top streamer instead of attempting to distribute views to everyone in the community.

**Comment by povrazor** [comment]
Well removing it wouldn't help.

**Comment by karai17** [comment]
I never said removing it was the solution, only that the current implementation seems to be problematic. Basically, during ther entire stream, we had zero peopel show up from the website (as opposed to previous LDs where we had an average viewer count of 10 as peopel came and went). The only two or three people that showed up came from IRC via direct link.

I don't think closing and ignoring this issue is the best way to go about this. Ludum Dare is about community, and this is an issue with community.

**Comment by povrazor** [comment]
Fair enough. Either way #543 #544
