### ISSUE TITLE
Metrics caching

### ISSUE THREAD

**Issue by karai17** [ludumdare/ludumdare#1154]
Is there any actual purpose to caching  metrics? The total votes aren't cached so those numbers often get out of sync, such as a category having 23 votes but metrics showing only 19 people voted. I can't expect calculating metrics to necessitate caching.

**Comment by zwrawr** [comment]
votes are cached.

some metrics like coolness need to be cached, as there expensive to
calculate. Ots also not vital that these numbers always be correct so
cachong is a good way to reduce load.

**Comment by karai17** [comment]
I can't imagine it takes that long to calculate coolness. What is the formula? Are we doing 50,000 square root operations?

**Comment by povrazor** [comment]
Not necessary. Metrics are part of the node.

**Comment by povrazor** [comment]
> Are we doing 50,000 square root operations?
Yes. :wink:

Calculating smart, classic balance, and all those other metrics **ARE** slow, because several tables need to be queried per node to calculate them (ratings, comments, etc). But though I say slow, it calculates 500 per 2 minutes. All those queries take between 20 and 80 seconds to complete (depending on how well it does on DB cache hits, which is different than the caching I typically talk about).

**Comment by karai17** [comment]
Well, the main issue here isn't whether to or not to cache, but having the data be consistant. Maybe cache the total votes, too?

Also, what in god's name are you doing to require over a minute to crunch numbers on a couple thousand entires? If LD had *millions* of games each cycle, I'd be totally fine with that, but 2000-3000? ***WHAT?!***

**Comment by povrazor** [comment]
The bottleneck of servers is 2 PCs talking to eachother. The overhead to make a request is high, which is why batching is so important.

**Comment by karai17** [comment]
I'd just like to remind you that itch.io runs on a single $40 Linode.

**Comment by povrazor** [comment]
We run on 2x $20 Linodes.

**Comment by povrazor** [comment]
Also, you gotta admit we do get a little busier than Itch when we run events.

**Comment by karai17** [comment]
My point is that itch is a much larger site than LD and has exactly zero performance issues, whereas LD seems to have tonnes of performance issues or weird quirks that cause some serious frustration.

**Comment by povrazor** [comment]
Itch has been live for like 5 years. We've been live for just a few months.

**Comment by karai17** [comment]
I am fairly certain itch's consitant traffic is far greather than LD's peak traffic. Maybe @leafo can throw us some numbers?
