### ISSUE TITLE
Unicode Emoji Proposal: Jam Emoji

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1158]
Okay here me out. We're going to do something silly here. :wink:

For a little bit of background, I tried to find myself an emoji to communicate "Jam", and I couldn't find anything good enough. :guitar: is too music. :baby_bottle: is the only bottle. :strawberry: isn't clear enough. Just like the :eggplant: has found new use (gigity), I want to propose something to the Unicode board with widespread use, that we can also claim for ourselves for fun social media usage.

I have a couple ideas for a proposal. I would expect one should propose a few ideas, but seeing how they only add 60-80 per year, reasons for their existence will likely need a strong argument.

**First:** `Mason Jar with Lid`

![jar](https://user-images.githubusercontent.com/1570313/28992753-ed58461c-7972-11e7-9d4b-63c87844fa46.jpg)

https://en.wikipedia.org/wiki/Mason_jar

Ideally though we want this:

![strawberry-jam](https://user-images.githubusercontent.com/1570313/28992754-f5d9c252-7972-11e7-909e-1eedcadc923f.jpg)

But frankly I'll whatever we can get.

Also notably absent is a Pickle emoji. Next best thing is Cucumber. What do you do with a  :cucumber:? You put it in a Mason Jar!

* `Mason Jar with Lid`
* `Mason Jar with Strawberry Jam`
* `Mason Jar with Pickle`

As the most common uses of the Mason Jar, I would start with these. `Mason Jar with Beer` can come another day. :wink:

**Second**: `Bread with Strawberry Jam`. i.e. :bread: + :strawberry: 

![toastwithbread](https://user-images.githubusercontent.com/1570313/28992756-072b8ed2-7973-11e7-9d8e-1c2415ab9758.jpg)

It's a shame there's no `Toast` or `Slice of Bread` emoji. That might be another route, to get to what we need. :wink:

Anyway, that's what I have thus far. I'm not yet familiar with the procedure. Just wanted to share the silly to see if anyone else wanted to come on board to help champion the idea with me. :wink:

**Comment by StormBurpee** [comment]
Have you taken a look at http://unicode.org/emoji/selection.html
I'm sure we could contribute to writing a proposal the way they've suggested! :wink:

**Comment by local-minimum** [comment]
This seems to be where you submit the proposal: http://www.unicode.org/emoji/selection.html
