### ISSUE TITLE
Can't remove love from comments

### ISSUE THREAD

**Issue by Junber** [ludumdare/ludumdare#1173]
I can't remove love from comments (tested on comments on posts, my game and other games). The error message "Failed to load resource: the server responded with a status of 404 ()" gets shown in the 'Inspect'-console.

**Comment by sgstair** [comment]
Thanks for the report, I can repro this issue, the UI makes it look like the love was removed but it wasn't.

I found the typo in the source leading to this problem. in note.php the remove path calls "no**d**e_GetById" to verify presence of the item rather than "note"
```
						$user_id = userAuth_GetID();

						if ( $note = node_GetById($note_id) ) {
//							if ( in_array($node['type'], THINGS_I_CAN_LOVE) ) {
								$RESPONSE['removed'] = noteLove_RemoveByNote($note_id, $user_id);
```

**Comment by povrazor** [comment]
Doh! Should be fixed now.
