### ISSUE TITLE
Anonymous comments

### ISSUE THREAD

**Issue by hadikcz** [ludumdare/ludumdare#1188]
> the problem is mainly due to the absence of anonymous comments. If you give harsh criticism about a game, the dev can be upset and downvote your game. I may be wrong, but I’m positively sure that this is the main reason for BS comments like “Good job, I like the font you used” and then BAM, 2/5.
Basically, if comments are short and “congratulations, good game”, the user really disliked what you’ve done.

TLDR: Bring back anonymous comments and the written feedback will be greatly improved.

But also keep list of user which one comment you, but not connected with their text, you can simply rate game back, but you dont know which comments write concrete user. For example under all comments some text like: Users who commented: Hadik, xxx, yyy, User11.

This will be also optionaly by some checkbox. Default will be enabled.
https://ldjam.com/events/ludum-dare/39/false-game/results-for-ludum-dare-39

**Comment by sgstair** [comment]
I do think we should implement this before the next LD.

**Comment by sgstair** [comment]
Hm, so are you suggesting that all comments should be anonymous? The way I see it working is, you will have an option to, when you are writing a comment, to mark it as an anonymous comment. In that case I'd expect other users to have no chance to connect it to your username.

I understand the desire to have links back to allow for both parties to rate each other, but if the purpose is to avoid retaliation this seems like a bad idea. I don't particularly like the idea of all comments being anonymous either.

**Comment by hadikcz** [comment]
Of course it will be optionaly

**Comment by povrazor** [comment]
FWIW anonymous comments didn't actually work on the old site :wink:. I started the feature, made mention of it, but never actually never finished it.

**Comment by local-minimum** [comment]
I think this is really important as it deals with internet safety but here's a question: should the comment be truly anonymous in the sense that the internal data-state on the server won't even know who made it, or does it suffice that anonymous comments are simply flagged as such and when such a comment is requested from the api, the api knows to leave out the author? The latter would allow for the commenter being able to keep track of their comments even if anonymous and would allow the site to monitor abuse better (if someone starts using anonymous comments for harm).

**Comment by sgstair** [comment]
it's my opinion that anonymous comments are a mechanism to provide honest criticism and protect against (the perceived possibility) of retalitation by the target voting negatively on the rater's game.

As such, I think the author should still be in the db, just implemented as a flag - And moderators/admins should (eventually) have UI to unmask the user if there's abuse of the system for unproductive comments.

**Comment by povrazor** [comment]
Yes, the original intent of anonymous comments were hidden usernames, but administrators could see who it was in case they decided to be jerks.

**Comment by povrazor** [comment]
Speaking of an anonymity flag, can anybody think of any other metadata that should be attached to a comment? At the moment I just that (anonymity). Curious if there should be a proper metadata system for comments, or if we can just get away with adding 1 flag.

**Comment by sgstair** [comment]
The other state I was thinking of besides "anonymous" was "deleted". Plausibly we could make a system to allow users to provide feedback on comments (reactions, or just anti-likes, or something), but I don't know that that is a priority, we have a long list of other things :)

**Comment by povrazor** [comment]
Yeah deletions I can't remember how they're supposed to work (another issue I think, or maybe just my notebook). But good point.

**Comment by sgstair** [comment]
Backend work for this has been completed with PR #1247
