### ISSUE TITLE
Multiple Karma Sub-Types

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#119]
We have separate **Post/Game** and **Comment** karma scores, simply due to how it's implemented. It makes sense to sub-categorise these.

For example:
- **Feedback Karma** - Comments on games that aren't yours
- **Helper Karma** - Comments on posts that aren't yours (might want a better name)
- **Game Karma** - Karma received by games you publish/contribute to

These individual karma scores aren't necessarily important, but could be used to infer things about a user. For example, some users may have high karma because they're helpful contributors to the community. Others may bring a popularity with them, and thus their games get a lot of attention.

Another use, Helper Karma could be used for determining what users to give the **Patching** promotion to, instead of outright giving it to everyone since this can be easily abused (i.e. notification spam).

Useful criteria:
- Your content/Not your content
- Your team's content/Not your team's content
- Karma from the author/team of content

`content` is any post, page (article), game, tool, etc.

Not all Karma types necessarily need to be reported. How much you give karma to yourself for example (Vanity Karma).

**Total Karma Score** will be a sum of all meaningful karma types. Certain Karma's can be worth more (i.e. Feedback Karma from the original author).

Implementing sub-types shouldn't actually require any changes, but rather to interpret (and cache) the available data differently.

**Comment by mkalam-alami** [comment]
I've also thought a bit about a such karma system, here's a couple risks to consider:

* Game Karma might reinforce the "popular guy" bias when rating games, and even might be used as a filter for some people who don't want to try bad games ("game is at +2? boring, not worth my time... +150? must be a cool game to try and rate!")
* Comment-related karma if done wrong might discourage criticism, and just favor instead short compliments & jokes (\*cough\* Reddit)

**Comment by povrazor** [comment]
Karma isn't coolness. :smile:

Most people pre-judge games by the screenshots anyway, which will be bigger and actually readable this time. Drilling down in to a profile just to check someone's Game Karma before deciding to play would be quite the effort.

Generally the Karmas are all just numbers for gauging a degree of participation. Who participates a lot, who gives a lot of feedback, etc.

You do bring up a good point with humour. It hasn't been a problem yet, but if _comedians_ do become a problem, we could track a separate humour karma, and give users a 2nd button to click (+Funny instead of +Heart).

**Comment by mkalam-alami** [comment]
> we could track a separate humour karma on comments. Give users a 2nd button to click (+:laughing: instead of +:heart:).

Hehe now I totally want multiple icons whether a comment is "humourous", "innovative", "moody", etc. (..."graphic"?!)

**Comment by povrazor** [comment]
Adding to my shortlist, to remind me to double check what I was thinking (what changes Karma needed).

**Comment by povrazor** [comment]
I'm pretty sure my thinking was each karma score would be calculated. This is how coolness is working right now. Users don't currently know how cool their are though (different issue).
