### ISSUE TITLE
Make grading more granular

### ISSUE THREAD

**Issue by sgstair** [ludumdare/ludumdare#1190]
Allow half-star granularity on ratings.
This would probably have to be done by doubling all the grade values. Probably we would want the table_create upgrade stage to double all existing grade values (so future tooling for visualizing the data would continue to work)

**Comment by povrazor** [comment]
Alternatively just make grade values in to floats, and on submit limit the valid values to steps of `0.5`. Easy change.

My main concern is the UX for this on mobile. Right now the implementation is simple, just click/touch the star you want, and that immediately sends the requested value to the server. If we allow halves, that makes the control itself a bit more tricky. 

Not necessarily a problem, but I just wanted to point out that making sure this works well one mobile is an important part of this change.

**Comment by zwrawr** [comment]
Closed by #1427
