### ISSUE TITLE
Preventing voting abuse

### ISSUE THREAD

**Issue by sgstair** [ludumdare/ludumdare#1195]
I doubt if these were used, but I noticed a few interesting gaps in the voting security we should shore up:
* The API allows you to vote, even if you didn't publish your game. It's theoretically possible to create dummy accounts and games, but not publish, and boost votes with little effort.
* The API allows you to vote on your own game, though the website doesn't.

**Comment by povrazor** [comment]
Oooh, that 2nd one. hehe

**Comment by povrazor** [comment]
I can't remember. We might have addressed this.

**Comment by sgstair** [comment]
I don't think it's been addressed yet.
