### ISSUE TITLE
On component structure

### ISSUE THREAD

**Issue by sgstair** [ludumdare/ludumdare#1245]
These are my ideas on the structure of components in the site. At the moment, the selection and rendering of components based on the current page is buried really deeply in the site in an inobvious location.

I know @Noojuno has been tinkering with component organization / refactoring some, and I don't really know where that effort is, but I'd like to start a thread so we can nail down what kind of refactoring should be done here.

At the moment, the site preact tree looks approximately like this:
* Main
  * ViewBar (top bar)
  * ViewHeader (featured, noob header)
  * ViewContent 
    * The universe. This is the problem :) ViewContent single-handedly emits all the types of objects, emits comments, emits all the nav buttons for every kind of page, everything
  * ViewSidebar
  * ViewHeader (footer)

The core issue is that *all* of the logic about what to display is in ViewContent.  
The direction I would take it is to have ViewContent simply use a minimal decision-making process to emit a "panel" component, e.g. PanelFeed (would emit nav buttons and feed content for feed pages), PanelGames (games selector & display), PanelUser, PanelEvent, PanelPost, etc.

Anyway, that's my two cents on the issue.

**Comment by local-minimum** [comment]
I agree, that ViewContent is a monster that had a lot of logic about what to do with the data for each individual PanelX, which I would prefer to be delegated to the panels themselves.

**Comment by Noojuno** [comment]
Part of what I've been working on in regards to refactoring is a router system that means no big blocks of if's. This is some of the structure of the current website in this format. 

Static routes are based on a path and should begin with a / but also work when not. The component is just a preact component (`import ExampleComponent from "com/example/example-component";` style) and gets rendered with any props from the `props` object in the main router.

```jsx
<Router props={...props_info} error={ErrorComponent}>
  <Route type="root" component={RootComponent}/>

  <Route type="post" component={PostComponent}/>
  <Route type="page" component={PageComponent}/>

  <Route type="item" component={ItemComponent}>
    <Route subtype="game" component={GameComponent}/>
  </Route>

  <Route type="tag" component={TagComponent}/>
  <Route type="user" component={UserComponent}>
    <Route static path="/feed" component={UserFeedComponent} />
    <Route static path="/games" component={UserGamesComponent} />
    <Route static path="/following" component={UserFollowingComponent} />
  </Route>

  <Route static path={["/games", "/results"]} component={PageTest}/>
  <Route static path="/feed" component={FeedComponent} />

  {/* etc. */}
</Router>
```
The user page could be done in a different way since it's just the bottom half of the page that actually changes, meaning that there could be a separate router on the user page that handles just the user page logic.

I'm about to go to bed so I'll expand more on the specifics of the system if I get a chance tomorrow or when I submit the actual PR.

**Comment by sgstair** [comment]
Cool, yeah thanks for describing it, I didn't follow it as clearly back on the gitter as I was focused on other things then, but I get the idea and this does look like a good solution to me - though I'd prefer a dedicated class of names for the router children, like "panel" in my suggestion. I'm curious if Pov has any further opinions or specifics guidelines here

**Comment by povrazor** [comment]
That would be pretty slick. Similarly in the back of my mind I've been warming up to the idea of changing the APIs in to something not too different (rather something that can be done in PHP).

```php
doAPI(
['/node/get', function(args) {
  // do get 
}],
['/node/getmy', function(args) {

}],
['/node/meta/get', function(args) {

}],
); // doAPI
```

Not to mention potentially changing the structure so that `/node/meta` calls could be in its own file.

**Comment by povrazor** [comment]
I think this has been addressed (both cases). There's still some refactoring to do (`/com/content/`), but for the most part this is a thing now.
