### ISSUE TITLE
Adding game links require tags.

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1261]
This should not be, especially not thorough silent failing like it does now.

Note: does not direct apply to live site since it has tags.

**Comment by sgstair** [comment]
Yeah, we can fix it by adding default tags in the simulator for now.
Long term, we should probably have a deploy script, that does a bunch of default setup actions - but that's presumably after we have a proper admin interface.

**Comment by povrazor** [comment]
Alternatively we could fetch the tag list from the live server, and just re-create them locally.

**Comment by local-minimum** [comment]
And I'd like to see the preact side deal with issues a bit nicer too
