### ISSUE TITLE
Investigate ServiceWorkers for potential offline support

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1298]
I haven't been following this, but DevelopIt (Preact author) mentioned ServiceWorkers, an upcoming feature that could potentially be interesting.

https://twitter.com/_developit/status/925829935310270464
https://twitter.com/_developit/status/925856419873685504

The Spec:

https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

Supported in recent Chrome and Firefox versions.

Given how ServiceWorker works, it may be worth investigating it, and adapting our API's to be play nice with it.

**Comment by zwrawr** [comment]
Service workers are also key in making a progressive web app #547 
*(At least from my reading of blogs like this https://blog.ionic.io/what-is-a-progressive-web-app/)*
