### ISSUE TITLE
Theme Suggestions link not going to /theme is confusing

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1304]
![ldcoo](https://user-images.githubusercontent.com/1570313/32407167-615495fe-c15b-11e7-9fb7-549fe62a1ce2.png)

It's true, the fact that this doesn't go to `/theme` is confusing. Either change what's highlighted, or go direct.

The reason it doesn't link to `/theme` is because I was trying to get folks used to the idea that the things they care about are on the event page.

https://twitter.com/blinry/status/926820420451528705

**Comment by zwrawr** [comment]
The 'Ludum Dare 40' could link to the event page, and the description could link to specific pages.

**Comment by mikekasprzak** [comment]
That was originally the plan, but I went ahead and corrected the links. The
new navigation tweaks should make it more obvious there is an event
homepage.
