### ISSUE TITLE
Suggestion: Make profile pages more compact

### ISSUE THREAD

**Issue by Samusoidal** [ludumdare/ludumdare#1310]
I suggest ordering the segments into tabs, it would reduce scroll time to get to Feed, Games, Following, etc.
![samusoidal ldjam com - mozilla firefox](https://user-images.githubusercontent.com/28611086/32572334-6fe6434a-c487-11e7-8ed5-860003ff07eb.png)

**Comment by povrazor** [comment]
Good idea.

**Comment by ajayyy** [comment]
I personally think Games and Feed should always be visible (they should not be a toggle)

**Comment by Samusoidal** [comment]
@ajayyy I'm afraid I can't quite see how that layout would work. Can you provide a sketch or mockup?

**Comment by ajayyy** [comment]
![image](https://user-images.githubusercontent.com/12688112/32639657-ebd24f10-c592-11e7-8d42-ceb0d3fc260e.png)
Something similar to the old site

**Comment by Samusoidal** [comment]
So much scrolling!
The faster a user can access the content, the better. And, if the buttons are in a static place (at the top instead of at the bottom of a variable height divider), muscle memory can develop and people can get to it even faster. It's the same concept in creating a video game. Tabs facilitate this, and allow for additional segments (like stats, etc) without adding more scrolling or cramming the layout.

**Comment by ajayyy** [comment]
Yea, I also think it might work better if the tabs were preloaded, because
now you have to wait a bit for it to arrive, making it very annoying to
switch between tabs

**Comment by Samusoidal** [comment]
Definitely.

**Comment by ajayyy** [comment]
I see this ended up getting fixed, thanks!

**Comment by Samusoidal** [comment]
Two more things: 'Feed' should not show the profile text. Profile text should get its own tab. Also, when you navigate to a user page, the profile text shows, but the games tab is highlighted. You still have to scroll down to get to the games (unless you click again).

**Comment by ajayyy** [comment]
I have to disagree with that. I feel that makes it far too compressed, and scrolling is a lot faster than clicking.

**Comment by povrazor** [comment]
Yeah sorry, not done.

**Comment by Samusoidal** [comment]
I guess it comes down to opinion here. I would rather have preloaded segments (organized into tabs) of about the same average height than scroll through a bunch of stuff to get what I want.  
In addition (also opinion) I feel it adds to the consistency and professionalism of the site. The profile pages, through their composition, color, and the addition of the back button are made separate from the main page or game pages. Consistently organizing the content will keep it from seeming like a dumping ground of content, not organized in any particular manner.  
At least place the Feed tab first so that the longest page is the first one, not the middle one.
