### ISSUE TITLE
labels inverted on 'ammount of jam vs compo games' chart

### ISSUE THREAD

**Issue by bremco** [ludumdare/ludumdare#1325]
See screenshot (which shows the graph for LD39, but LD38 has te same issue, so it's probably just the labels instead of the data).

![inverted_labels](https://user-images.githubusercontent.com/30440932/32648911-3fa2a4ae-c5f8-11e7-862e-a29bbe61171c.png)

I'm certain that the ammount of jam games outstips the number of compo games for the last few rounds. Either that or both my memory of < 1000 games for compo last time _and_ LDstats is wrong.

**Comment by sgstair** [comment]
yeah, just fixed in #1323 and will be pushed to the site when pov notices :) - Thanks for the report

**Comment by povrazor** [comment]
Looks fixed to me.
