### ISSUE TITLE
Decrease the font size/size of elements on the page

### ISSUE THREAD

**Issue by Jezzamonn** [ludumdare/ludumdare#1327]
I find the current site unusable unless I'm zoomed out. I have a little macbook with a small screen, so that doesn't help either. But here's a comparison of the site at the default zoom level with other sites

Lets start with the old Ludum Dare site
![screen shot 2017-11-10 at 08 39 41](https://user-images.githubusercontent.com/10319630/32668753-4c7e37a6-c5f3-11e7-9752-b44b00966da6.png)

Twitter
![screen shot 2017-11-10 at 08 40 39](https://user-images.githubusercontent.com/10319630/32668757-4f15ac4c-c5f3-11e7-8775-8da836554341.png)

New York Times
![screen shot 2017-11-10 at 08 44 37](https://user-images.githubusercontent.com/10319630/32668777-640bd9c8-c5f3-11e7-9edc-1fbe9111bffe.png)

And now, the current Ludum Dare site
![screen shot 2017-11-10 at 08 44 41](https://user-images.githubusercontent.com/10319630/32668781-663996fe-c5f3-11e7-8d11-704de2c66a78.png)

I think the default should be much smaller. It's probably part of the reason why people say our site feels like a 'mobile site'

**Comment by povrazor** [comment]
Part of the problem too is the font. Both should be re-evaluated.

**Comment by povrazor** [comment]
Before:

![font-a](https://user-images.githubusercontent.com/1570313/32675167-f41e04d4-c623-11e7-9f2a-53ff2a5f68dc.png)

After:

![font-b](https://user-images.githubusercontent.com/1570313/32675174-fb6aeb58-c623-11e7-8922-1933f31e7c06.png)

**Comment by povrazor** [comment]
Other than as SVG size, this should be done.
