### ISSUE TITLE
Allow you to add team members from the game page

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1350]
Picking up where #1157 left off. Re-creating this so to make it stand out more.

Improve the team making process. We were rushed before, so the process is not obvious. Make it better.

As the other thread suggests, do something like:

* John
* Billy :x:
* [add member]

where 'add member' is a drop down box of your friends currently not on your team.

**Comment by local-minimum** [comment]
Who can add or remove friends? Is it only the main author?
Can you remove yourself?
If more than main can add, whos friends? Only mains' or everyone's?
