### ISSUE TITLE
Load more games per request on feed pages.

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#1364]
This should probably be dependant on the number of games per row, and should be higher than the current amount. I'd say 25+

**Comment by povrazor** [comment]
I'd be fine with bumping it. API should be stable enough now (my shameful rebuild-every-request bug is fixed now). The current number divided nicely in to 3 (whatever it is, I forget).

**Comment by povrazor** [comment]
24 divides nicely in to 2, 3, 4, and 6 (can't win them all). I'd be fine with a bump to 24.

**Comment by sgstair** [comment]
you can win them all if you bump it up to 60 :) I was also thinking about loading 10x(width)

**Comment by zwrawr** [comment]
Default was bumped to 24 as per #1462 .
