### ISSUE TITLE
Dismiss dropdown when clicking elsewhere on the site

### ISSUE THREAD

**Issue by sgstair** [ludumdare/ludumdare#1365]
Suggestion from Sun-Wukong on the LD site;
I'm not sure how easy this would be to implement, but I do agree it would be more intuitive.

**Comment by povrazor** [comment]
Yeah the other drop-downs work this way. Not sure why it's the way it is.

**Comment by local-minimum** [comment]
If it is the notifications, it would be because the notifications may not be using the full dropdown component.
