### ISSUE TITLE
Add hotkeys to theme slaughter

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#1381]
Mention on the site here https://ldjam.com/events/ludum-dare/40/$50300/script-to-add-keyboard-controls-to-theme-slaughter

Also in the same vain as #12

**Comment by local-minimum** [comment]
I think we need to pull in something like https://github.com/NekR/preact-delegate to have hotkeys work. If @mikekasprzak is OK with that, I think it would be a quick fix.

**Comment by mikekasprzak** [comment]
Well it doesn't actually need it, but that is an interesting approach.
