### ISSUE TITLE
Make notification style consistent with the rest of the site.

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#1382]
![screenshot from 2017-11-20 18-50-14](https://user-images.githubusercontent.com/18352787/33035753-2912f0f2-ce24-11e7-8d4b-5a3dac55c3dd.png)

* Needs to use the defined colors in `defs.less`
* Needs more contrast between bg and fg colors (black + blue is bad)
* Title is indented ?
* Mark as read for individual notifications

**Comment by povrazor** [comment]
#1314

**Comment by sgstair** [comment]
I was considering using a yellowish background tint for unread notifications. There is also now the option to style notifications in the dropdown as unread also. Haven't done any work on style here yet though.
