### ISSUE TITLE
/events/ludum-dare page is missing the navigation bar at the top

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#1386]

**Comment by povrazor** [comment]
Please elaborate. If your not running/featuring an event, you don't get one.

**Comment by zwrawr** [comment]
All of the other pages linked at the top of the home page have the a nav bar at the top.

### All the other pages linked in home pages nav bar

![image](https://user-images.githubusercontent.com/18352787/33091302-9f3d33c6-ceee-11e7-99ea-3ffc9e15a4c8.png)

![image](https://user-images.githubusercontent.com/18352787/33091320-ab1b7b4e-ceee-11e7-9ae4-ca24be02b789.png)

![image](https://user-images.githubusercontent.com/18352787/33091337-b716438e-ceee-11e7-890e-9b2194ded298.png)

![image](https://user-images.githubusercontent.com/18352787/33091350-c30c9972-ceee-11e7-8493-4faa858dc7b0.png)

### The events page

![image](https://user-images.githubusercontent.com/18352787/33091392-e6560684-ceee-11e7-913d-825ffe59dc32.png)

**Comment by povrazor** [comment]
Okay got it. It's the whole fact that tap tab bars are starting to feel like how navigation actually works around here.
