### ISSUE TITLE
Missing "VR" entry for the game link type

### ISSUE THREAD

**Issue by WizzardMaker** [ludumdare/ludumdare#1393]
I thought about making a game where you can play with VR and without it, and that's why I would need 
Windows (VR), macOS (VR), etc. entries.

**Comment by povrazor** [comment]
Okay. VR is supposed to be a TAG, but your example makes total sense. What I'll probably do instead is let you pick the platform, but also edit the text.

**Comment by povrazor** [comment]
Here this bug is! Got editing in, but did not have enough time to get user tagging working before submissions opened.
