### ISSUE TITLE
Cover photo resolution

### ISSUE THREAD

**Issue by KureKureciCZ** [ludumdare/ludumdare#1394]
Hi, ehm, i posted this to LDJam.com and they linked me here, so:
could you change the game cover resolution to something more, 2017? Thanks

**Comment by povrazor** [comment]
What does that mean?

**Comment by zwrawr** [comment]
This shouldn't be too much of an issue, but we could probably bump it a bit.
Although it worth noting that the images are 480px wide and are normally shown a ~300px wide. So increasing the resolution won't do anything that decreasing the compression (when we reprocess them) wont.

**Comment by pfefferminzz** [comment]
Please keep the 5:4 ratio because itch.io uses a 315x250 (63:50 = 5.04:4) cover image resolution which is almost the same ratio as the Ludum Dare resolution 480x384 (5:4). It comes in handy if you can use the same image for LDJAM and hosting at itch.io.
 
> The cover image is used whenever itch.io wants to link to your project from another part of the site. Required (Aspect ratio: 315x250)

**Comment by povrazor** [comment]
I still don't know what the actual issue is. More information would be appreciated.

**Comment by KureKureciCZ** [comment]
Its low-res. It gets blurry when you use high-res monitor OR if you have 1 - 3 games per line... It would be more future proof...

**Comment by pfefferminzz** [comment]
Could you please post a screenshot? What does https://ldjam.com/games looks like on your monitor?

**Comment by KureKureciCZ** [comment]
This is just FullHD monitor...
I dont want to tell you its bad, just not good on the long run. When 4K screens become the standart, older covers are going to look very bad.
![123perline](https://user-images.githubusercontent.com/30993672/33478422-85ae8f70-d689-11e7-8cbe-f68c9f049039.png)

**Comment by povrazor** [comment]
It hasn't happened yet, but we'll actually be disabling the 1 and 2 per line choices when viewing on the Desktop. They'll only be available on Mobile (or a browser window as wide as a mobile browser).
