### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by sn0uk** [ludumdare/ludumdare#1411]
UK
Chrome
Win10 Home
Starts Saturday at 2:00 AM BST
Starts Saturday at 2:00 AM GMT

SS:
![image](https://user-images.githubusercontent.com/30574262/33507711-304d5286-d6ee-11e7-8ce2-e1f10474a1df.png)

edit:
This shows the correct time on the countdown.

**Comment by adampurnell** [comment]
This is already been covered in #1406

**Comment by povrazor** [comment]
And #589
