### ISSUE TITLE
'Publish' doesn't always work.

### ISSUE THREAD

**Issue by thenightraven89** [ludumdare/ludumdare#1412]
For some reason I could not publish a message, only save it as draft.
As long as I created a draft message with the same title, it couldn't be published.
Changing the title to something else made it work for me.

![image](https://user-images.githubusercontent.com/7041320/33509929-d5468df0-d70e-11e7-8e5d-5a1f2c1d735d.png)

**Comment by sgstair** [comment]
Post titles need to be longer than 3 characters - This is a hard rule enforced by the API - Sorry, it's not very well communicated when the post fails due to this at the moment.
