### ISSUE TITLE
Emoji with underscore doesn't render

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1426]
We are saying we support `:woman_running:` for example and we might do, but if you preview it doesn't render the emoji, instead it writes `:woman,_running:`. Note the injected `,`.

**Comment by povrazor** [comment]
Sounds like something might have broke it.

**Comment by local-minimum** [comment]
I'm thinking some other markdown rule. I've got too many things before this baby-apocalypse of a game is done. So probably don't have time during the weekend to look at it.

**Comment by zwrawr** [comment]
js is weird, and sometimes the code works without explicit joins and sometimes it doesn't. I've fixed this before so i'll do it again.

**Comment by zwrawr** [comment]
So :woman_running: isn't an emoji. Thats why it isn't rendering. Try :green_apple: `:green_apple:`.

**Comment by zwrawr** [comment]
I fixed this for the emoji parsing, guess i didn't fix the fail case.

**Comment by zwrawr** [comment]
Closed by #1438
