### ISSUE TITLE
COM: Rework components to be 'mobile first'

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#143]
Which is basically a hipster way of saying _"make them work when they're small"_. Fiddly stuff with the media queries. Setting some standards for new components.

**Comment by povrazor** [comment]
Moved to wishlist. Not going to be done in time.

**Comment by Bjeaurn** [comment]
I can vouch that the mobile experience on the new LDJam.com could be better. It's workable, and at least it lets me zoom to a proper level. But there's some small enhancements that could make the experience a bit better.

Maybe I'll tinker around with some of the basic settings to improve the main experience, without fiddling too much with the separate components.

**Comment by povrazor** [comment]
Ya, all I have time for right now is making sure it works (mobile), not making sure it works well. 

This is a pretty important part of the site I'm discovering. Voting for themes on mobile was way more popular than I expected.
