### ISSUE TITLE
Platform and Tag requests

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1430]
We don't yet have a way for everyone to create **Platforms** and **Tags**, so I've opened this issue to make requests.

Post requests for Platforms and Tags here!

## Important (READ THIS BEFORE SUBMITTING)
We use specific terms for things when cataloguing our data. These terms are as follows:

* **Platform** - Things games run on: https://api.ldjam.com/vx/tag/get/platform?pretty
  * eg. `Windows`, `Mac`, `Linux`, `Nintendo GameBoy`
  * NOTE: `VR` isn't a platform according to our classification. If you post a VR game, choose the host platform, and include the `VR` tag (or specific tags like `Oculus Rift`, `HTC Vive`, etc)
* **Tag** - Details about a game: https://api.ldjam.com/vx/tag/get/?pretty
  * eg. `VR`, `Local Multiplayer`, `Gamepad`, `Mouse`
* **Tool** - Things games are made with (**NOTE**: This is coming later)
  * eg. `Unity`, `Unreal`, `SFXr`, `C++`

The current lists can be seen via the API links above.

**Comment by zwrawr** [comment]
ref #1104
