### ISSUE TITLE
Broken comments on games

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#1441]
https://ldjam.com/events/ludum-dare/40/dense-revolve/this-is-a-problem

![screenshot from 2017-12-04 03-41-04](https://user-images.githubusercontent.com/18352787/33535344-fbd9b9d2-d8a4-11e7-8f95-d39eec5afaa8.png)

**Comment by zwrawr** [comment]
This seems to only effect anon comments. The user who posted them can see them but no one else can.

**Comment by zwrawr** [comment]
Looking at the stack trace, it seems like were attempting to load the avatar of `anon`.

**Comment by fiaKaiera** [comment]
If it helps, this what it looks like in Firefox, 
![image](https://user-images.githubusercontent.com/15869263/33535947-ded3f1b2-d8eb-11e7-8b42-1a63aaa2149b.png)

**Comment by povrazor** [comment]
Okay, this should be fixed. #1443
