### ISSUE TITLE
Half-star ratings displayed incorrectly

### ISSUE THREAD

**Issue by seleb** [ludumdare/ludumdare#1442]
This half-star ratings are showing up as a set of conjoined ~3/4th stars:

![image](https://user-images.githubusercontent.com/6496840/33535976-14ab016c-d87f-11e7-88c2-616ee65881f1.png)

It looks like the cause is that the half-width CSS is being overriden:
![image](https://user-images.githubusercontent.com/6496840/33536072-e8cb63b0-d87f-11e7-952f-9ab993476d6d.png)

Seeing this on Firefox 57.0.1 + Chrome 62.0.3202.94, Windows 10

**Comment by povrazor** [comment]
Okay, this should now be fixed.
