### ISSUE TITLE
Improve team building (was Team Questions)

### ISSUE THREAD

**Issue by josefnpat** [ludumdare/ludumdare#1448]
Howdy;

So I have found my way to https://ldjam.com/users/josefnpat/following

And I want to make sure the team is set up right. How do I make sure this is the team for the current jam and not my previous jam? Or is it the same list, so to speak?

Also, I can't seem to "Remove From" previous members. It just has the js popup, and then does nothing, even if I refresh the page.

**Comment by josefnpat** [comment]
Also, as a sidenote; the users don't seem to be randomly shuffled each time I refresh.

**Comment by povrazor** [comment]
Teambuilding right now is a hack that I just haven't had time to go back and fix. The Add/Remove buttons on the follow page only apply to the game in the current event.

For now, the best way to know if it's done properly is to visit your game page, and look at the authors shown at the top of the page.

**Comment by zwrawr** [comment]
I think he means that the users **are** randomly sorted. Which is just an issue with the following pages,

**Comment by josefnpat** [comment]
@zwrawr you are correct, thank you.

What are the associated tickets, so we can close this one?

**Comment by zwrawr** [comment]
Adding users to your game is addressed in  #1350. There was some discussion in #1157
Don't think there is an issue for the user pages
