### ISSUE TITLE
Hard to find specific types of notification when scanning list

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#1449]
> Mike Kasprzak @povrazor 18:34
A suggestion sent to me for notifications:
> >It would be very, very helpful if we could separate “also commented on” and “mentioned” in some way so that we don’t have to read every line to find comments we really need to engage with!

> Zak West @zwrawr 19:18
We could just add icons to the lines
@ for mentions
speach buble for also commented on
Some thing for someone your following making a post
controller for someone your following posting a game
That would make it easy to scan to the notification too see what there about

**Comment by local-minimum** [comment]
The feed icon could be good for when someone is making a post.

**Comment by mikekasprzak** [comment]
Just checking, but was this resolved by #1484?

**Comment by zwrawr** [comment]
I believe so
