### ISSUE TITLE
Use `&nbsp;`  or non-line breaking in general for team-member names.

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1450]
![image](https://user-images.githubusercontent.com/8041100/33577749-50b6c892-d944-11e7-86dd-e56cb35c822e.png)

Breaking after the parenthesis looks quite wonky.

A small issue though.

**Comment by sgstair** [comment]
Related to this, we should look into adding the concept of "at-mention-possessive" e.g. "@sgstair's" as it's used in notifications, at the moment there's unnecessary space between before the 's

**Comment by povrazor** [comment]
- [ ] Wrap names in author line with a span featuring whatever that `no-wrap` tag is.
- [ ] Remove gap from around `@name`'s, so `'s` will work as expected
