### ISSUE TITLE
Game list 'filter' doesn't work as it should

### ISSUE THREAD

**Issue by willvincent** [ludumdare/ludumdare#1453]
While typing in a value _does_ remove items that don't match your search term, space of unmatched items is not removed. So results still appear paginated just with only those matching things on pages.. The result is you have to hit more several times to get to all the results, and the result of hitting more _may_ be just an empty line.

Ideally, this filter should completely remove items from the result set that are not a match, and pagination should work as it does when no search filter is applied (ie: 12 items per page)

Here's a screenshot of the existing bad behaviour (represents having clicked 'more' about 10 or 12 times):

![ldjam com_events_ludum-dare_40_games_classic_compo](https://user-images.githubusercontent.com/689891/33586087-24e06a14-d92d-11e7-85cc-fd423d94fef6.png)

**Comment by povrazor** [comment]
Yes, I'm actually working on replacing this. We had a bunch of changes all come together near the end (see the tiny gear peeping out from beneath the corner), and a few too many things going on at once, that unfortunately improving the UX came last. Working on it.
