### ISSUE TITLE
Include something that lets you tell if a game was made solo or as part of a team

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1480]
![food](https://user-images.githubusercontent.com/1570313/33636958-7406f4f4-d9ec-11e7-9aea-f0fe7fab15d9.png)

Now that the Jam has taken over (nearly 2:1), it would be nice to know if a Jam game was made solo or as part of a team from glance.

Originally that was going to mean showing avatars of all contributors, but instead we could use the Person and People SVG iconography in a corner.

**Comment by local-minimum** [comment]
Avatars wont work well (we were 8 in team,  though not all registered). So svg sounds cool. Maybe also replace compo and jam with svgs?

**Comment by mikekasprzak** [comment]
Had a bit of a thought here. Technically the word COMPO is longer than JAM, so if you think about it, there's a tiny bit of space besides the word JAM that could be such an indicator of solo versus not. I believe we have a "single user" icon and a "multiple users icon". I'm curious what this would look like.

This could probably be easily mocked up. Alternatively, single vs multi user icon should go on the opposite side as the trophy icons.

`node_GetAuthors(node).length` (result should be an array, hence `.length`) should be usable to actually perform the check. This solution has the added benefit that author avatars don't need to be loaded.

Finally a semi-related issue: when these boxes get small, you can't see anything (it gets covered by the title, event name, etc). Some effort should probably go in to the CSS to auto-hide info as the size shrinks so the cover art can still be seen. Not necessarily a task for this issue, but something to remember.
