### ISSUE TITLE
Platforms of links not showing when editing a game 

### ISSUE THREAD

**Issue by gruhh** [ludumdare/ludumdare#1485]
When editing a game the platform reference of each added link is not being displayed.

![captura de tela 2017-12-06 as 09 56 19](https://user-images.githubusercontent.com/25804857/33660749-0f4326de-da6c-11e7-81e1-ad4f4946d48c.png)

Note: I did not try to save without correcting the platforms of each link to see if the reference is lost or not.

**Comment by povrazor** [comment]
Oh weird. I saw that in my local branch, but I was changing the code. I'm on it.

**Comment by local-minimum** [comment]
This should have been resolved by #1669, if not please comment to say it persists.
