### ISSUE TITLE
ludumdare.com: switch domain to active site

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#150]

**Comment by povrazor** [comment]
Pushing this back.

**Comment by povrazor** [comment]
API has now moved to `api.ludumdare.com`, due to certificate issues.

**Comment by mikekasprzak** [comment]
Change of plans. We've established ourselves on `ldjam.com` too much, so by the time we're ready `ludumdare.com` will act like a redirect for `ldjam.com`.
