### ISSUE TITLE
arcadespot, stolen games

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#1500]
https://twitter.com/egordorichev/status/939035168723017729

After just a few mins of looking i've already found many LD40 games, just from recognising the art work.

| LDJAM        | arcadespot           |
| ------------- |-------------|
|https://ldjam.com/events/ludum-dare/40/Curse-of-Greed  |  http://www.arcadespot.com/game/curse-of-greed/ |
|https://ldjam.com/events/ludum-dare/40/the-lost-strawberry  |  http://www.arcadespot.com/game/the-lost-strawberry/ |
|https://ldjam.com/events/ludum-dare/40/Famous-Knight |http://www.arcadespot.com/game/famous-knight/ |
|https://ldjam.com/events/ludum-dare/40/Sofra |http://www.arcadespot.com/game/sofra/ |
|https://ldjam.com/events/ludum-dare/40/caribou-simulator | http://www.arcadespot.com/game/caribou-simulator/|
| | |

**Comment by povrazor** [comment]
Quick look at the site, they use the following companies for advertisers.

* exponential.com
* doubleclick.net (google)

Sites like these are parasitic. The most effective way to get a takedown is to reach out to the advertisers.

**Comment by sgstair** [comment]
The first 4 games on that list are all on newgrounds.
I don't think Arcadespot is stealing from LD.
"The lost strawberry" is conclusive - He says on twitter that they cut out his logo - They did no such thing, the LD site version has a logo, and the newgrounds version does not. They stole the newgrounds version.

**Comment by egordorichev** [comment]
Oops, I missed the logo part, sorry :X I did not see, that newgrounds one is missing it. Will update it soon.

**Comment by egordorichev** [comment]
![screenshot 2017-12-11 at 11 38 27 am](https://user-images.githubusercontent.com/7851390/33822229-dd389c5a-de67-11e7-958a-91863a1cca1e.png)

[http://www.gamezhero.com/games/theloststrawberry](http://www.gamezhero.com/games/theloststrawberry)

:X

**Comment by egordorichev** [comment]
![screenshot 2017-12-18 at 9 27 06 pm](https://user-images.githubusercontent.com/7851390/34121526-60f1ebdc-e43a-11e7-911e-b79868aa78f6.png)


OH MY :X Help me ;(

**Comment by egordorichev** [comment]
They added god mode:
http://www.arcadeprehacks.com/game/32666/the-lost-strawberry.html

**Comment by sgstair** [comment]
@egordorichev See pov's advice earlier in this thread; Beyond that I don't know what you expect to achieve by posting here.
