### ISSUE TITLE
Reloading Games list changes the filter to "All Events"

### ISSUE THREAD

**Issue by rplnt** [ludumdare/ludumdare#1504]
How to reproduce:
1. Navigate to [Games]
2. Reload webpage (UI, F5, Ctrl+R, ...)

Expected result:
* Filter stays as is (or is reset to default - Featured Events)

What happens:
* Filter is changed to "All Events"

**Comment by rplnt** [comment]
Also, probably related, the event selection is unresponsive/ignored after the reload. Other filters work fine.

**Comment by Jezzamonn** [comment]
+1 Just found this and was about to report it

**Comment by local-minimum** [comment]
Better just close issue and reopen if needed.
