### ISSUE TITLE
Notifications for "My Game" missing?

### ISSUE THREAD

**Issue by cppchriscpp** [ludumdare/ludumdare#1507]
Since a few days ago, I no longer get notifications for comments on my LD40 game. If I look at the `/my/notifications` page, I don't have anything under "Feedback" despite a decent number of comments on my game. Some of them seem to have ended up under the general "Comments" tab, but the most recent comment seems to have completely vanished. (11 hours ago, by "jjjjason")

My username is cppchriscpp, and this is my game: https://ldjam.com/events/ludum-dare/40/fluffy-space-escape 
I mentioned this in the Discord chat, and another user named "Akusan" mentioned having the same problem. 

![image](https://user-images.githubusercontent.com/750475/34073883-34da8d7a-e272-11e7-802a-c5cc7194e2e9.png)

Hope this is enough info - if not feel free to ask and I'll get back to you asap. Thanks for adding the notification feature btw; it's really nice to see things I might care about at a glance.

**Comment by local-minimum** [comment]
Are these old feedbacks or new? 

Thing is feedback didn't really exist in the system before. It was something I had hacked onto it on the client side while preparing the texts. So now that it does exist as a real category, those older feedbacks would be just comments. I realize it might NY have been  optimal to stop the old reclassification mid LD voting. My bad. I'll check if I can reintroduce it when doing some other fixes to the UI.

**Comment by cppchriscpp** [comment]
Aha, that makes sense for the older ones; for sure! It doesn't bother me too much for the ones that already existed prior to the non-hacky solution, knowing that. 

The one thing that still concerns me is the most recent comment I got (~25 hours ago) didn't show up in comments **or** feedback. This might be a one-off issue, but does seem concerning.

**Comment by bremco** [comment]
> The one thing that still concerns me is the most recent comment I got (~25 hours ago) didn't show up in comments or feedback. This might be a one-off issue, but does seem concerning.

I can confirm (see images included), and there's the last comment made here ( https://ldjam.com/events/ludum-dare/40/playable-hams/ludum-dare-40-has-ended-time-to-play-rate-and-give-feedback-on-games ) by 'avavt' that seems to point in the same direction. Maybe it only affects new comments on your own game?

![ld40_notify_b](https://user-images.githubusercontent.com/30440932/34079534-dd39d45e-e32f-11e7-85e9-8c7336a5da57.png)
![ld40_notify_a](https://user-images.githubusercontent.com/30440932/34079535-dd4e2fc6-e32f-11e7-9ae3-2a9950f17d31.png)

**Comment by local-minimum** [comment]
Yes I'm noticing this for myself right now too. This was not the case on my local machine, so hopefully it's a quick fix. Will look into it now.

**Comment by local-minimum** [comment]
Think I found it now too. But I'm gonna spend a little time doing some other fixes too unless Mike is ready to do a quick merge. Basically you will only get feedback-notifications if you are not the main author at the moment... Oops.

**Comment by cppchriscpp** [comment]
Ah, saw #1508 and that would definitely do it. Glad you were able to find it pretty quick. (I tried to poke through a couple changes from around the time I saw the problem, but wasn't nearly familiar enough with the codebase to get there)

Thanks for jumping in with extra screenshots bremco; I didn't think to provide that level of detail - I'm usually better about that!

Thanks!

**Comment by local-minimum** [comment]
PR is merged, I have gotten feedback notification on my game so issue should be resolved.
