### ISSUE TITLE
Graded games list should have better summary of game

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1514]
The current solution just grabs first 100 characters of the text:
![image](https://user-images.githubusercontent.com/8041100/34232655-9d315512-e5e1-11e7-9348-716f93e7b698.png)

**Comment by zwrawr** [comment]
The game description should list the author of the game. Would make sense to put this on the same line as the games name.

**Comment by local-minimum** [comment]
#1518 Fixes this (but not on the same line)
