### ISSUE TITLE
Graded games list should show the grades you gave

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1515]
The graded games list should include your grades per item. 

Preferably the list should be sortable not only on order that you graded games but also the grades given.

**Comment by zwrawr** [comment]
Could also show the final ranking and grade of the game once the results are out.

**Comment by local-minimum** [comment]
#1518 has the grades showing. It'd be better opening new issue if we should show comparison to global average and rank after voting. It's also a matter of not getting too much text and info into the list.
