### ISSUE TITLE
[Graded Games List] Filters/Sort Orders

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#1519]
A few suggestions came up here https://ldjam.com/events/ludum-dare/40/babies-babies-babies/we-should-be-better-at-announcing-new-features-my-graded-games-list

* Sort based on average grade given by me
* Sort based on theme/sound/fun/mood/overall grade given by me
* Sort based on weather i have commented on the game.

**Comment by local-minimum** [comment]
I started working on the sorting but not so much these since they require new endpoints in the API to get the data needed

**From gitter.im**
> > [...] add an API call that returns everything given an event's node_id as input. 
>
> > I actually want the same type of API endpoint as for grades that would return the node id:s for all nodes in an event that I've commented on.

**Comment by local-minimum** [comment]
#1518 Has sorting implemented, it is just waiting for the relative endpoints to add the above suggested sort-options.

**Comment by local-minimum** [comment]
Only thing missing from #1518 now is if commented on or not

**Comment by local-minimum** [comment]
Think this can be closed
