### ISSUE TITLE
metrics stopped updating

### ISSUE THREAD

**Issue by bremco** [ludumdare/ludumdare#1532]
I was looking around for games with just below 15 ratings to bump them into the next category ('pre-Danger'?) I've rated two such games around 2 hours ago, and commented on one of them (see screen-shot), but they're still stuck below 15, and my own metrics haven't updated either.

The two games are
 - [Conservation Island](https://ldjam.com/events/ludum-dare/40/conservation-island), from which a screenshot.
 - [Fat Puss](https://ldjam.com/events/ludum-dare/40/fat-puss)

![ohno_ratings_ld40](https://user-images.githubusercontent.com/30440932/34315076-e3f3504a-e77b-11e7-89f5-0966cd49f93e.png)

Interestingly, 'events/ludum-dare/40/mygrades' _has_ updated, with the two games mentioned!

I'm not the only one with this problem, I think: see [here](https://ldjam.com/events/ludum-dare/40/atoms-an-arcade-game/ratings-given-not-showing-up) and [here](https://ldjam.com/events/ludum-dare/40/who-ate-my-pizza/ldjam-site-bug-my-rating-stats-isnt-being-updates).

**Comment by local-minimum** [comment]
If `/events/ludum-dare/40/mygrades` has updated you can be sure that the new grade took and is in the DB.

The bug,  was another symptom of the issue that coused #1533 and is resolved by #1534

**Comment by bremco** [comment]
Yes, that and that the grades (stars) did not disappear when I left a game-page suggested that it must've been saved at least _somewhere_.

This seems back in working order in any case :-)

**Comment by local-minimum** [comment]
Feel free to close the issues then :)
