### ISSUE TITLE
Add user name auto-complete

### ISSUE THREAD

**Issue by Cerno-b** [ludumdare/ludumdare#1553]
I would love to see Github's auto-complete for user names if possible

When a user presses "@", a drop down menu opens where they can select user names from a list. When they start typing a name, the list is reduced to the names that fit what was typed.

Also, it would be nice to have a small icon next to a user name in the feed or comment section. When someone clicks the icon, the user name is added to the comment field. It should be possible to click more than one person to create multiple referrals in the comments.

**Comment by mikekasprzak** [comment]
#1548

**Comment by Cerno-b** [comment]
Wow, alright! 

So it's already implemented and waiting for the merge?

**Comment by mikekasprzak** [comment]
Pretty much. It may have some limitations right now (only users that are part of the discussion), and it needs some testing, but yeah.
