### ISSUE TITLE
db-create.sh requires input

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1561]
To be able to run test with Travis all relevant scripts needs to have ways to execute without needing input from user. This would also make it easier for the event simulator to fix tables if they seem to be needing a fix.

So this issue probably touches more than `db-create.sh`.

I'm looking for something like:

`sudo ~/db-create.sh --yes` and/or `sudo ~/db-create.sh -y` to skip the `Are you sure`-question and just go ahead doing it all.

**Comment by mikekasprzak** [comment]
This was worked around somehow, correct?

**Comment by local-minimum** [comment]
We were running travis checks I believe, so it must have been resolved. If we want to explore this in the future we can reopen it.
