### ISSUE TITLE
Strange order of "Previous Themes" in Theme Suggestions

### ISSUE THREAD

**Issue by gonutz** [ludumdare/ludumdare#1588]
On the Theme Suggestion page, the list of Previous Themes is:

Ludum Dare 39  Running Out of Power
Ludum Dare 38  A Small World
Ludum Dare 37  One room
Ludum Dare 40  The more you have, the worse it is

This is not in order :-)

**Comment by zwrawr** [comment]
For me they are showing up in order 
![screenshot from 2018-04-07 16-50-25](https://user-images.githubusercontent.com/18352787/38457091-db06ee14-3a83-11e8-820e-ce49c695f14c.png)

And it looks like they are being [sorted by there `start-date`](https://github.com/ludumdare/ludumdare/blob/master/src/com/content-event/event-idea.js#L58)
Although that sort might be on a UTC string and not on a date object. It's probably worth converting the `start-date` into a unix timestamp before sorting

**Comment by local-minimum** [comment]
The utc string should be safe if it is a proper iso date string, but wouldn't hurt converting to dates

**Comment by mikekasprzak** [comment]
We're already passed the round, but was anybody else able to reproduce this? I'm afraid I've not seed the unusual order myself. I know this page shows things a little weird.

https://ldjam.com/events/ludum-dare

But it's still in order.

**Comment by zwrawr** [comment]
Since the it's not the default page any more, here is a link to the page in question
https://ldjam.com/events/ludum-dare/41/theme/idea

**Comment by gonutz** [comment]
This looks fine to me now, I have it sorted from 40 down to 37.
