### ISSUE TITLE
theme slaughter: duplicate entries

### ISSUE THREAD

**Issue by gonutz** [ludumdare/ludumdare#1591]
There seems to be no filter for the themes to exclude double entries, I encountered "Steampunk" for the third time now and "Alone" and "alone" if I remember correctly.

**Comment by gonutz** [comment]
Right now there are two "Space" themes in my recent 10 slaughtered list.

**Comment by mikekasprzak** [comment]
Ah shoot, that's my fault. There's a script I'm supposed to run that
removes dupes, but I forgot. I'll take care of it later today.

**Comment by timbeaudet** [comment]
I just wanted to say I also found duplicates of `escape`, seems like it is a known issue.

**Comment by mikekasprzak** [comment]
Sorry!

**Comment by mikekasprzak** [comment]
Okay, dupes should be removed now. You might run in to a theme you'd previously done, but that was because the one you previously did was the one removed. You shouldn't see 2 identical themes on your lists anymore.

Again, sorry about that everyone.

**Comment by gonutz** [comment]
Cool, thanks!
