### ISSUE TITLE
Theme Slaughter hotkeys listening while not logged in/a dialog is open

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1592]
Ah shoot. It looks when you're visiting the Theme Slaughter page, the `Y` and `N` hotkeys try to do stuff, even while you're not logged in.

https://twitter.com/SuciuTiberius/status/984472862168965120

At the very least, we need to stop this with a check, 'cause it's triggering that error message.

Eventually this is going to have to be switched to something focus related. Once the Search popup is added, you're going to want to be able to type `Y` and `N` keys.

**Comment by local-minimum** [comment]
What specifically is the issue here? The minimal solution so to say?

Is it the error message in itself, that it should say that the user needs to log in?
I'm thinking the client doesn't really know if the user is logged in unless it tries to vote on a theme.
