### ISSUE TITLE
Amount of "Love" in a comment does not update until actually pressed

### ISSUE THREAD

**Issue by tiberiusuciu** [ludumdare/ludumdare#1600]
![not_updated_likes](https://user-images.githubusercontent.com/22992043/38830654-0a21f1f4-418b-11e8-8fb3-07520a059e94.gif)

**Comment by mikekasprzak** [comment]
This is by design. It may improve once we start doing the Twitter thing (i.e. checking for new posts while you wait), but right now, until you refresh the browser the old cached copy of the posts are used.

**Comment by tiberiusuciu** [comment]
Yeah I was actually just about to write that as well, my apologies

**Comment by mikekasprzak** [comment]
No worries. :smile:
