### ISSUE TITLE
Import the game count of number of games made on ludumdare.com

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1617]
This depends on #1616 

Idea is that it would be fun if the total number of games showed the grand totals

- [ ] number of ld on old and new site
- [ ] number of ld & minis on old and new site

Since we don't want each profile request to cause a bit of information gathering from the old site, setting an account-link to the old site would have to trigger that count.

**Comment by mikekasprzak** [comment]
Data will be migrated over, and old site will be eventually retired.
