### ISSUE TITLE
@tag auto name suggestion breaks users with spaces

### ISSUE THREAD

**Issue by jasonleekennedy** [ludumdare/ludumdare#1625]
for example

if someone types @ jason - it suggests @ jason kennedy, but but the user name per the system is @ jason-kennedy.  Appears to prevent the tag from getting detected for notifications and the tag links to the wrong or non-existent user

**Comment by mikekasprzak** [comment]
I've been getting a bunch of these.

https://twitter.com/HarryLightGames/status/988504843122806791

**Comment by JackWesleyNelson** [comment]
Yeah, I noticed this as well. I thought someone mistagged another, but when I went to correct them I realized that while it still autocompletes the name it doesn't actually associate a correct link. (And only the first break of the name is hyperlinked)
