### ISSUE TITLE
Game page loose values for Download and Links section when edit

### ISSUE THREAD

**Issue by acoto87** [ludumdare/ludumdare#1628]
When you edit the page of your game the Downloads and Links section looses the values for the Platform column.

![image](https://user-images.githubusercontent.com/2373936/39142870-8967098e-46f1-11e8-915f-9263f5ec9778.png)

![image](https://user-images.githubusercontent.com/2373936/39142886-989d5e30-46f1-11e8-8039-7ae4cb953c09.png)

**Comment by mikekasprzak** [comment]
See #1620. This is apparently a bug with previewing. If you set it, save it, then view your page, it should be fine.

**Comment by acoto87** [comment]
Yeah, I think the bug is that the values from database aren't assigned the UI field properly when the view is loaded, I think it doesn't have more impact than that.

**Comment by local-minimum** [comment]
#1669 resolves this too (at least in my dev environment)
