### ISSUE TITLE
"Play my game" spam as comments

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1636]
Like #1202, but it's potentially worse since it subverts the natural voting.

**Comment by mikekasprzak** [comment]
Added this as a `support bottleneck` since I'm the goto person when folks find this.

**Comment by local-minimum** [comment]
It could look something like this:

![image](https://user-images.githubusercontent.com/8041100/39331867-fd352b1e-49a5-11e8-947b-9e9db84322e0.png)

`onChange` event detects that I've entered a link to my game and it replaces the publish etc buttons with a helpful message.

**Comment by local-minimum** [comment]
It could look something like this:

![ld_comment_nolinks](https://user-images.githubusercontent.com/8041100/39331939-40835df0-49a6-11e8-8d08-eb72e4d6c4aa.png)

The component reacts to and `onChange` event that sees that I've entered a link to my own page and replaces the publish etc. buttons with a helpful info box.

**Comment by mikekasprzak** [comment]
Neat. Does it stay there or is dismissable/go away at any time.r?

**Comment by SecretPocketCat** [comment]
Couldn't there be a button to mark comments as unhelpful? Clicking it would be the opposite of the 'Love btn' and would lower the commenters coolness. 
(Does the love button raise it? I'm actually not entirely sure what it does).
