### ISSUE TITLE
CORE: Upload Avatars

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#164]

**Comment by josefnpat** [comment]
Why not save yourself time and hassle and just use a trusted third party service like [gravatar](http://en.gravatar.com/) until you flesh this feature out entirely?

**Comment by povrazor** [comment]
Yeah, if I run out of time that's not a bad solution. Not a simple one (e-mails are isolated from users), but it can be done as a process.

**Comment by Shinmera** [comment]
I'd actually prefer having Gravatar over internal avatars, or at least having it as an option. Having to go around all the different sites to change an avatar is very tedious. Gravatar makes that process much simpler.

**Comment by josefnpat** [comment]
So why did this get closed? Was it implemented? Is this WONTFIX? Did we get gravatars?

**Comment by zwrawr** [comment]
We have avatars now (Yay!). So now this issue is closed. 

Supporting gravtars is a separate discussion and should have a separate issues. Feel free to open one.
