### ISSUE TITLE
Lead users landing on the frontpage into the game rating process

### ISSUE THREAD

**Issue by quantumrain** [ludumdare/ludumdare#1644]
The rating process should be given more prominence on the front page.

Right now it's a little bit hidden, and a couple of clicks deep depending on the flow you follow.

This makes the news feed a great target for people trying to advertise their game as it will have much more presence when posted here, which encourages people to spam the news feed with posts- which does seem to be an effective strategy if you look at the number of ratings received/given for these games.

If the front page lead people into the rating process and actively advertised games which needed rating the power of these posts would be reduced, and would also reinforce an important aspect of ludum dare- which is the rating of games.

This is an example mock up of how the front page flow could be adjusted:

![image](https://user-images.githubusercontent.com/713039/39442488-4523ee3c-4ca9-11e8-9484-94e967abb36e.png)

Here the top 4 entries from the smart list would be inserted into the top of the news feed as an auto-generated blog post.

This gives people a brief reminder of how the rating process works, and offers up several games which are currently most in need of rating.

The number of games you still need to rate this jam is also given as a prompt to the user that they should continue to rate games.

This post could also appear as the top item each time you click 'more' at the bottom of the news feed, with a new set of games randomly picked from the top 100 smart list to continue to try to attract the users attention into the rating process.

**Comment by zwrawr** [comment]
Yes!
There is a good discussion about something very similar here #954

**Comment by ajayyy** [comment]
This looks perfect, there was something similar on the old site, but this would be even better.
