### ISSUE TITLE
Bring the Compo checkboxes back

### ISSUE THREAD

**Issue by ajayyy** [ludumdare/ludumdare#1646]
I think it would be very useful to bring the Compo checkboxes back to make sure people know the rules.

I know some people didn't understand how it worked but I still think it would be very useful.

When publishing was accidentally left on before the jam started, people were publishing not even knowing what they were doing.

Or at least maybe a dialog box warning when you hit publish.

**Comment by gatechgrad** [comment]
I came here to basically post the same thing.  I'm finding a lot of compo games where people either don't understand the rules or just ignore the rules.  It would be nice if the person rating the game could flag the game for breaking the rules, and maybe give a few options (used existing assets, didn't work alone, didn't share code, etc).

**Comment by SecretPocketCat** [comment]
@gatechgrad I wouldn't make it compo specific - there should be certain flags avaible to jam games as well, e.g. didn't opt-out from category, but using existing assets

**Comment by ajayyy** [comment]
I only said compo checkboxes because that's what the old implementation was

**Comment by local-minimum** [comment]
For this, is it sufficient just to deactivate the publish and save buttons when a user clicks `Compo` option until the user has said that they know the rules (i.e. store their actions in the state, trigger this need to answer each time user clicks on the `Compo` button)?

Does anyone have a list of what they checkboxes were? Or ideas about what they should be.

**Comment by ajayyy** [comment]
![image](https://user-images.githubusercontent.com/12688112/40742232-d39ded8c-641b-11e8-86d6-9b1944af18f9.png)

**Comment by local-minimum** [comment]
I haven't fully implemented the disabling aspect yet, but I'm thinking something like this:
![image](https://user-images.githubusercontent.com/8041100/40795843-856b8e06-6503-11e8-8bf4-853933d1d205.png)

**Comment by zwrawr** [comment]
The compo/jam lines should hide and show themselves based on whether the game is compo/jam. I would also suggest moving them below the Jam/Compo buttons.

**Comment by local-minimum** [comment]
I was considering that too but wasn't sure if it would be confusing to the user when options appeared and disappeared. If can swap it around though if Mike thinks it is better that way.

**Comment by local-minimum** [comment]
Fix is now in.
