### ISSUE TITLE
Edit button for anonymous comments available for anybody

### ISSUE THREAD

**Issue by winniehell** [ludumdare/ludumdare#1649]
For me it was unexpected behavior that anybody (without being logged in) can edit a comment that was posted as Anonymous. Is that intended?

**Comment by zwrawr** [comment]
Confirmed. UI allows to edit anon comments. API returns 401 unauthorized on
the call to vx/comment/update/$

**Comment by zwrawr** [comment]
Edits do not persist on page refresh.
Does not appear to be a security issue, just a ui issue.

**Comment by winniehell** [comment]
> Edits do not persist on page refresh.

Thanks, forgot to test that. :smiley:

**Comment by Samusoidal** [comment]
Title should be tagged as non-persistent, scared the pants off of me!

**Comment by mikekasprzak** [comment]
Or alternatively, it's an easy fix if somebody wants to dig.

**Comment by winniehell** [comment]
@Samusoidal Thank you, I changed the title. :+1: I wasn't aware that it's not persistent when creating the issue.

**Comment by Samusoidal** [comment]
Is there a page where I can see the layout of the API and instructions on setting up a development version? I'd like to try my hand at fixing this.

**Comment by mikekasprzak** [comment]
The homepage of this repo should tell you where to go to get set up. The
specific fix should be on the JS side, I believe in a file under
`src/com/content-comment/`

**Comment by Samusoidal** [comment]
Thanks, @mikekasprzak! I'm having a little trouble getting it set up, but I left an issue on the DairyBox page.

**Comment by local-minimum** [comment]
This issue seems to be resolved or non-existing in the dev environment:

![image](https://user-images.githubusercontent.com/8041100/40874350-7eafb2ba-666e-11e8-8f6a-90e87acfd3d1.png)

Please confirm it still remains on the live site and post a link to game with the issue.

**Comment by winniehell** [comment]
> Please confirm it still remains on the live site and post a link to game with the issue.

@local-minimum It's still happening for me with our game: https://ldjam.com/events/ludum-dare/41/splendid-adventures-on-a-sunday-afternoon (comment-202441)

![bildschirmfoto vom 2018-06-02 15-35-42](https://user-images.githubusercontent.com/1652293/40876864-aeea0d0c-667a-11e8-80e6-a9a2c22afa09.png)
![bildschirmfoto vom 2018-06-02 15-35-54](https://user-images.githubusercontent.com/1652293/40876866-af44d6ce-667a-11e8-9252-a3a51a2d4d29.png)

**Comment by local-minimum** [comment]
I see, perhaps it only happens when not logged in. That would explain why I didn't see it yesterday. I'll check later today or tomorrow.
