### ISSUE TITLE
Metrics are flipped on some games

### ISSUE THREAD

**Issue by ajayyy** [ludumdare/ludumdare#1651]
For example, on this game https://ldjam.com/events/ludum-dare/41/zoccer , the metrics appear like this: 

![image](https://user-images.githubusercontent.com/12688112/39971052-df87304c-56c2-11e8-9580-597981cd3d93.png)

But on most other games they appear like this:

![image](https://user-images.githubusercontent.com/12688112/39971054-eefcc154-56c2-11e8-8cbe-ab26f7f9163e.png)

(example is https://ldjam.com/events/ludum-dare/41/castle-beat)

**Comment by mikekasprzak** [comment]
Neat. I'm not sure why it happens (well, it is because of how we fetch the other metrics and the order they exist inside a table), but it's harmless. Still a neat find.
