### ISSUE TITLE
":emoji_codes:" page linked below editors doesn't provide short codes

### ISSUE THREAD

**Issue by mkalam-alami** [ludumdare/ludumdare#1685]
The https://emoji.codes/ link now redirects to https://www.emojicopy.com/, which only lets people copypaste the unicode emojis (not supported yet #200).

As a quick workaround, the best replacement I've found is this page, I have no idea if it matches 100% but overall it looks good: https://www.webpagefx.com/tools/emoji-cheat-sheet/

**Comment by mikekasprzak** [comment]
That sucks that they changed the website. We do have emoji autocomplete
working in comments. Once it works in posts, we should be able to remove
the link.

**Comment by local-minimum** [comment]
Maybe this bumps priority of related issue(s) to next LD, rather than end of year?

**Comment by mikekasprzak** [comment]
Yeah, if you want to tackle that sooner than later please do.
