### ISSUE TITLE
Can view unpublished game when not logged in.

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1688]
![image](https://user-images.githubusercontent.com/8041100/41200174-ea198e7c-6c9f-11e8-8de4-9f2f3d5619c8.png)

**Comment by mikekasprzak** [comment]
I can't decide what do to about this. There are good reasons for/against it.

Keep it:
* Can easily share unfinished posts/articles/games with anyone by sending them the link

Remove it:
* Privacy

We're not really a community designed around private communication though. The entire point of what we do here is to share, so I'm leaning towards not changing this.

**Comment by local-minimum** [comment]
I think we keep it after all and no-one has complained about it so if it becomes a problem we make an issue of it then. I think it may be quite useful if you are a team working remotely and not everyone is registered..
