### ISSUE TITLE
Can comment before game is published.

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1689]
![image](https://user-images.githubusercontent.com/8041100/41200200-3ad772f2-6ca0-11e8-86b8-c418fbf6f97a.png)
Even as other user it seems.

**Comment by mikekasprzak** [comment]
I'm also on the fence about this, but it does have some utility.

For example, if I was making a post and wanted to reserve the first comment before someone steals it, this would allow me to do this.

**Comment by local-minimum** [comment]
Lets close this, if it becomes an issue then we do something about it then
