### ISSUE TITLE
Make emoji autocomplete menu scrollable

### ISSUE THREAD

**Issue by Samusoidal** [ludumdare/ludumdare#1692]
When using the emoji autocomplete, pressing enter will return undefined instead of the highlighted emoji code.
Would also be nice to browse the list with the arrow keys (since it's searchable by substring), and scroll entries so we can see more than 5.

**Comment by local-minimum** [comment]
This is resolved by one of the PR up right now

**Comment by local-minimum** [comment]
Not the scrolling though

**Comment by Samusoidal** [comment]
Changed title to reflect the current PR status.

**Comment by mikekasprzak** [comment]
I think the limit is currently 8 (GitHub is 5). I'm tempted to close this since I don't necessarily think scrolling adds much (besides complexity on Mobile). That said, in the future we can pursue better/alternative emoji entry interfaces.
