### ISSUE TITLE
Make the Rules/Events more accessible

### ISSUE THREAD

**Issue by Samusoidal** [ludumdare/ludumdare#1698]
It's kind of hidden there on the event page, and I've noticed that new jammers seem to have a hard time finding/understanding the rules. 

There should also be a 'tutorials' page where new users can see how to open issues, contribute to the project, and use the site (creating teams, etc).

**Comment by ajayyy** [comment]
I agree, there should be a link in the header or sidebar.

**Comment by local-minimum** [comment]
@paulloz is looking into this one

**Comment by paulloz** [comment]
Would a **Guides** section in the sidebar be good enough?  
We can link the **rules** and the **game hosting guidelines** from there, and the **tutorials** @Samusoidal is talking about when they're written.  

![firefox_2018-08-29_18-57-48](https://user-images.githubusercontent.com/437025/44803043-90203a80-abbd-11e8-86b3-94561fde09d2.png)

**Comment by local-minimum** [comment]
The one concern is that `https://ldjam.com/events/ludum-dare/rules` are the rules for LD-jams only, and the dream is to one day support the miniLD again. But well if you ask me this is much of an improvement and if we get to supporting more than main LD then we can deal with it later.

**Comment by Samusoidal** [comment]
I like the idea of a Guides section in the sidebar but it needs to stand out like a sore thumb in a bucket of sardines.
Maybe you could put a fill behind it? Rounded edges, light gray from the palette, etc. That would be eye catching and denote that it's important.

**Comment by local-minimum** [comment]
I'm quite happy with the style in the image. We are planning other ways to point people to the rules too like the new rules questions when you submit and https://github.com/ludumdare/ludumdare/issues/1752

**Comment by local-minimum** [comment]
But we like `<SVGIcon>` so perhaps add one that fits for the rules. You find them in http://192.168.48.48/dev_icons.php or something close to that
