### ISSUE TITLE
CORE: Post Comments

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#170]

**Comment by k30v1n** [comment]
miss comments there on LDJAM.COM =/
I am a developer too, how can I help?

**Comment by povrazor** [comment]
You can familiarize yourself with the toolchain. #221 has some notes on it. But depending on your background, it might be a little complicated as it stands (plus I wont have a ton of time to merge changes during the weekend).

I'd recommend enjoying the event, then after the dust settles, you're welcome to dive in to what we're doing here.

As for comments, they'll be coming alongside judging next week (since we absolutely need them for that).
