### ISSUE TITLE
Can't login if username/email contains the letter 'n'

### ISSUE THREAD

**Issue by VapidLinus** [ludumdare/ludumdare#1700]
My username/email contains the letter 'n' which causes a dialouge to pop up when pressed.

**Text:**
> **Oops!!**
> It looks like your session expired (and yes, it's probably a bug).
> Log in again to continue what you were doing.

**Example:**
https://gfycat.com/CorruptExcellentAngwantibo

**Comment by Samusoidal** [comment]
Try logging in from a different page than the Theme Slaughter. That page has hotkeys Y and N that could be messing with your login.

**Comment by VapidLinus** [comment]
That works, thank you.

**Comment by mikekasprzak** [comment]
#1592
