### ISSUE TITLE
Add Ability to Edit Display Name

### ISSUE THREAD

**Issue by Doppp** [ludumdare/ludumdare#1722]
Not sure if this is on the roadmap but it would be nice to have the ability to edit the name next to the `(@name)` section of the profile.

**Comment by mikekasprzak** [comment]
Yep, we call it "slug editing" internally. It's super high on my list, but
its the thing that keeps getting put aside for other stuff that seems more
important in the moment. Definitely on our radar though. 😁

**Comment by Doppp** [comment]
@mikekasprzak Any updates on "slug editing"?
