### ISSUE TITLE
Markdown: Insert image links

### ISSUE THREAD

**Issue by SecretPocketCat** [ludumdare/ludumdare#1742]
Currently, the parser will seemingly disallow the use of img links and the user has to upload them to the site. Why is that?

It'd be nice to be able to link to large gifs for example or be able to control the caching of an image (so that I can serve a current image of an online leaderboard for instance). 
I mean, many large gifs would slow down the landing page a lot, so I can see a clear reason why not, but it'd be nice to be able to do that outside the posts (so game and user descriptions).

**Comment by mikekasprzak** [comment]
A significant amount of people don't understand how to play-nice with
low-bandwidth devices, so it's done to give us an easy insertion point for
optimization passes (I.e. we'll optimize so you don't have to). Given how
we built the website (JavaScript), it is actually possible to harvest
private information from users if we're not careful, hence why data from
outside websites is restricted. We have a sandboxing solution in testing
that should allow more than just YouTube we'll be deploying soon.

**Comment by SecretPocketCat** [comment]
Thanks for taking the time to reply and glad to hear something's in the works.
