### ISSUE TITLE
Implement a way to use ldj.am

### ISSUE THREAD

**Issue by ajayyy** [ludumdare/ludumdare#1788]
Similar to this awesome firefox extension: https://addons.mozilla.org/en-US/firefox/addon/ld-shortlinkener/

**Comment by mikekasprzak** [comment]
https://ldj.am/$ID works

**Comment by ajayyy** [comment]
Ya, but it would be nice if there was an easy way to find the $ID.

**Comment by mikekasprzak** [comment]
The secret way is to hover your mouse over the post/game/user-page title. 😉

**Comment by MHillier98** [comment]
It would be nice to have a button that'd copy the generated link to your clipboard. It could either be a link icon, or a bit of text that just says "Copy link to game".

**Comment by local-minimum** [comment]
It should be easy to add a url-shortener copy to clipboard button, either near the title of the post or next to the heart.
