### ISSUE TITLE
Error: unauthorized on login (401 error)

### ISSUE THREAD

**Issue by kristinalustig** [ludumdare/ludumdare#1796]
I'm attempting to log in to my ldjam.com account, and when I enter my username and password (or email and password), I get an "Error: unauthorized." Here's a screenshot of the console:

![Screen Shot 2019-04-22 at 2 42 54 PM](https://user-images.githubusercontent.com/4544317/56518382-4e0d8580-650d-11e9-8f0a-449069f6a876.png)

**Comment by mikekasprzak** [comment]
What username did you use?

**Comment by kristinalustig** [comment]
kristinamay is the username. Just tried on a different laptop as well, still no dice.

If it's helpful, pasted here is the full log for this sequence of actions (just now):
1. Navigate to ldjam.com (in chrome)
2. Proceed to secure site
3. Click login button
4. Type in username
5. Paste in password from 1password storage
6. Press "enter"

<img width="663" alt="Screen Shot 2019-04-22 at 5 24 04 PM" src="https://user-images.githubusercontent.com/4544317/56532365-a2236480-6523-11e9-8aad-972c8f22bd36.png">
<img width="656" alt="Screen Shot 2019-04-22 at 5 24 15 PM" src="https://user-images.githubusercontent.com/4544317/56532376-a51e5500-6523-11e9-9c4f-16bba32d3391.png">

**Comment by kristinalustig** [comment]
Heads up that I reset my password and it works now. Not sure why, as I use a password manager to keep them stored and current, but I'm no longer unable to log in.

**Comment by mikekasprzak** [comment]
Great. Thanks for letting me know.

Mike Kasprzak
