### ISSUE TITLE
Switch to @font-face

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#1823]
- Gives an easy way to show text before font is loaded `font-display:swap`
- Demo page https://font-display.glitch.me/
- Supported by all browser (font-display all but edge and IE)
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

```
LIGHTHOUSE AUDIT
URL | Potential Savings (ms)
 -- | --
…v19/KFOlCnqEu….woff2(fonts.gstatic.com) | 50 ms
…v13/1Ptrg8zYS….woff2(fonts.gstatic.com) | 100 ms
…v19/KFOjCnqEu….woff2(fonts.gstatic.com) | 100 ms
…v13/1Ptrg8zYS….woff2(fonts.gstatic.com) | 30 ms
…v13/1Ptrg8zYS….woff2(fonts.gstatic.com) | 40 ms
```

**Comment by zwrawr** [comment]
Looks like google font's added support for font lazy loading via the URL param `&display=swap`

**Comment by mikekasprzak** [comment]
Cool. Should be an easy fix.

**Comment by zwrawr** [comment]
Cloased by bedefad
