### ISSUE TITLE
Remove unused images?

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1826]
Since images should be the bulk of all data we store, there should be a server script that deletes all images older than X days that are not referenced in any node or note.

I imagine this would clear up some space.

**Comment by mikekasprzak** [comment]
We add rough 10 GB more data per event, and this costs us about $1 more per
month. In the grand scheme of server costs, our storage cost is still under
$10, or about 5%.

**Comment by mikekasprzak** [comment]
FWIW that cost will go up (double) once I switch to actual clustering, as
each of the front-end nodes will need a copy of the data.
