### ISSUE TITLE
Process images I old posts

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1827]
Related to #1826.

Posts are hardly ever read after they leave the main feeds first page. Therefore the cost of storing the images in their originally submitted resolution/size/quality can't really be justified.

Specifically for posts, not items/games. All images in a post older than X days should be processed to minimize their size. If we have most recent request stamp on the node we can filter on this instead.

This should free up huge space.

**Comment by mikekasprzak** [comment]
Images are not really the culprit, GIF's are. The solution to GIF's is to
re-encode them as MP4 videos, but transcoding takes time (minutes
sometimes), unlike images where re-encoding takes fractions of a second
(and are done in effectively real-time).

**Comment by local-minimum** [comment]
Alright in that case, if storage isn't important, let's close the this and the other one
