### ISSUE TITLE
CORE: Notifications and Subscriptions

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#183]
Some related issues:
- the `@host` shorthand: https://github.com/ludumdare/ludumdare/issues/8
- on orphaned accounts, and their implications: https://github.com/ludumdare/ludumdare/issues/3
- popup a dialog when you publish telling you who's getting notified https://github.com/ludumdare/ludumdare/issues/193

**Comment by povrazor** [comment]
```js
{
  "to": target_id, /* user (@username), event (@host), post/game (@author) */
  "from_post": post_origin_id, /* direct message (user), event notice (event), a comment (the post/game) */
  "from_comment": comment_origin_id, /* 0 (the post itself), non-zero (the specific comment) */
  "author": author_id /* just to save us from looking it up. may not be needed */
}
```

**Comment by povrazor** [comment]
# Subscriptions

TODO breakdown

**Comment by sgstair** [comment]
Well, I didn't actually realize this issue existed before implementing notifications, but what I implemented seems pretty similar :)

**Comment by zwrawr** [comment]
This is implemented, to be closed.

**Comment by povrazor** [comment]
Good job everyone. :+1:
