### ISSUE TITLE
Site Title Doesn't Include "Ludum Dare"

### ISSUE THREAD

**Issue by dashrava** [ludumdare/ludumdare#1832]
**Issue:**
Typing "_Ludum Dare_" into urlbar doesn't return ldjam.com main site because the site's title doesn't actually include the name.

**Steps to reproduce:**
1) Begin typing "_Ludum Dare_"
2) Get offered LD Twitter, and previous LD events, but not the main site.
3) Regret.
4) Type "_ldjam_" instead.
5) Repeat every time you want to enter the site.

**Use-case:**
So far I for one have failed to enter the site on first attempt every time.
Typing "Ludum..." and browser autofilling would be a great boost in autocomplete usability.

**Things attempted:**
I tried searching for "ldjam.com" in the repo, but on a quick non-webdev glance couldn't find where the title is set, so I failed to create pull request directly.

**Suggested Fix:**
Add "_Ludum Dare_" anywhere in the title, e.g.
"_LDJam.com - Ludum Dare_"
"_Home of Ludum Dare - LDJam.com_"
"_Ludum Dare_"

**Comment by BrianMacIntosh** [comment]
I think this has been resolved, the https://ldjam.com/ title is currently 'ldjam.com | Ludum Dare game jam' for me.
