### ISSUE TITLE
CORE: Countdown Clocks

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#184]

**Comment by Lukenickerson** [comment]
Seems like a countdown clock would require a few things:

- Frontend/UI "widget" to be included on the homepage
- API endpoint for listing competitions ("compos" or "jams") in chronological order (which would allow the frontend to know which one is the most recent)
- An API endpoint ("compos/x" or "jams/x")  that includes data about each competition/jam
-- Compos endpoint needs to return the start and end dates

Is that what this entails?

**Comment by StormBurpee** [comment]
If you look at pull request #389 the countdown clocks have been completed, all that is needed to be completed now, is conveying the syntax to proper preact.js styles. 
I'm currently working on this as we speak :)

**Comment by povrazor** [comment]
> Is that what this entails?

Yes. I still need port the Schedule code over (I have it working in another project), and basically do what you're suggesting. For LD37's sake we'll just hardcode it, but @StormBurpee has been working on making it look good. :smile:

**Comment by Lukenickerson** [comment]
It looks great! 👍 
![image](https://cloud.githubusercontent.com/assets/3942453/20949880/f5874424-bbe9-11e6-958c-c266d1b5875a.png)
