### ISSUE TITLE
Routing for searching categories interfere with name games changing entire query to game link 

### ISSUE THREAD

**Issue by KubaJakubowski** [ludumdare/ludumdare#1866]
There is issue that if you name your game like "Zero" it'll overwrite Zero search category and everybody who would like to sort via Zere category will be directed to game site.

It's critical issue, someone can just post game named "classic" and break entire games search engine and everybody will view his game.

Requests from search engine should be done like /events/ludum-dare/46/games/?="category",
not like /events/ludum-dare/46/games/zero

**Comment by mikekasprzak** [comment]
All other names were on the reserved list. I forgot to add zero.

**Comment by mikekasprzak** [comment]
No I stand corrected. It's just a bug. `/games` is the reserved word, and it's bypassing it and going to the slug named zero instead of `/games`.

**Comment by mikekasprzak** [comment]
Fixed. https://github.com/ludumdare/ludumdare/pull/1867
