### ISSUE TITLE
Document Source Tree

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#187]
Strategically place more README.mk files in the source tree, so anyone browsing on GitHub can figure out what folders are for easier.

`/src/` is a _prime_ location for this, since it's **NOT** user facing (like the old structure was).

**Comment by frenetic** [comment]
+1

**Comment by povrazor** [comment]
`/src/` documentation has been roughed out. 

#140 still needs to happen, and I discovered a mistake in the design while working on #139, so I wouldn't call it reliable yet. That said, anyone feeling adventurous should be able to follow along better now.

At least, for things in the `/src/` folder. The root, and rest of the tree still needs work.

`/public-???/` will not be specifically documented, but the `README.md` in root will eventually explain what they are.

**Comment by povrazor** [comment]
*cough* oh, and there's no current building instructions. So when I say "follow along", I mean looking. ;)
