### ISSUE TITLE
Can't post comments when signed in

### ISSUE THREAD

**Issue by matthewvroman** [ludumdare/ludumdare#1879]
Hope this is the right place to post this.

This seemed to just start happening today. When going to the comments section of a game, I see the 'Sign in to post a comment' message, even though I'm already signed in. 

Sometimes refreshing the page will show me the comment box and allow me to comment but it seems hit or miss.

There is an error that pops up in the console, but it seems to show up regardless of whether or not the comment box appears so unsure if they're related. 

Let me know what other details I can provide related to this! 

Win 10
Chrome Version 80.0.3987.163 (Official Build) (64-bit)

![chrome_aIp0NjXnRP](https://user-images.githubusercontent.com/1207382/79938476-9063ee00-8411-11ea-8385-6e8751d2e794.png)

**Comment by mikekasprzak** [comment]
Fixed.

Mike Kasprzak
