### ISSUE TITLE
GitHub organization description is outdated

### ISSUE THREAD

**Issue by Marcono1234** [ludumdare/ludumdare#1901]
Not directly related to this repository, but the description of the ludumdare GitHub organization (https://github.com/ludumdare) is outdated:
![GitHub organization description](https://user-images.githubusercontent.com/11685886/88919711-e85d8c80-d26b-11ea-913b-9d18a9f142a8.png)
It still says "Every April, August, and December!" even though Ludum Dare takes places every April and October now.

**Comment by mikekasprzak** [comment]
Fixed.
