### ISSUE TITLE
https version of website doesn't load

### ISSUE THREAD

**Issue by saloomi2012** [ludumdare/ludumdare#1902]
Visiting https://ldjam.com on both Chrome and Safari on macOS Catalina results in a loading website with no content.

Steps to reproduce:
1. Visit https://ldjam.com

<img width="1431" alt="Screen Shot 2020-08-24 at 1 40 19 AM" src="https://user-images.githubusercontent.com/3886505/91007899-1acc8200-e5ab-11ea-8f10-8223b5630d48.png">

Visiting the http version loads fine. It is instant and fast.

**Comment by SecondThread** [comment]
This also happens on Firefox mobile.

**Comment by local-minimum** [comment]
Yes, same on Firefox desktop, so not browser specific.

**Comment by ReneHabermann** [comment]
It is in this state since at least 3 days ago.

**Comment by mikekasprzak** [comment]
Servers are being rebuild. Should be resolved in a few days.

**Comment by wischi-chr** [comment]
Just tested it and it works fine on Chrome. Looks like this ticket can be closed?

**Comment by mikekasprzak** [comment]
Yes. This was a certificate issue. It may crop up one more time, but permanent fix is in progress.
