### ISSUE TITLE
Im not getting activation email

### ISSUE THREAD

**Issue by firesoldier888** [ludumdare/ludumdare#1913]
i trying to create account and i dont get activation link

**Comment by wischi-chr** [comment]
Just tested it, seems to work fine (again?)

**Comment by mikekasprzak** [comment]
Certain email providers' spam filters still do eat our emails. The mail server will be migrated to a different machine soon, so a new similar issue may pop up, but I'm going to close this for now. Do feel free to re-open this or a new issue if emails aren't arriving, and let us know who you're with, in case we need to ask to be whitelisted.
