### ISSUE TITLE
Time is represented as EDT instead of EST, with a 1 hour difference

### ISSUE THREAD

**Issue by Windzyboy** [ludumdare/ludumdare#1918]
![image](https://user-images.githubusercontent.com/63932310/115939958-eed10b80-a46d-11eb-91cc-76289226a390.png)

**Comment by mikekasprzak** [comment]
We are in the Daylight (EDT) cycle right now. :wink:

**Comment by Windzyboy** [comment]
oh crap yeah I'm an idiot

**Comment by mikekasprzak** [comment]
No worries. :D
