### ISSUE TITLE
Site logs me out every minute.

### ISSUE THREAD

**Issue by TheWaouh** [ludumdare/ludumdare#1947]
ldjam.com logs me out every minute, no matter what I am doing at the time.
I am using Microsoft Edge Version 93.0.961.47 (Official build) (64-bit), and Windows 10 Home (64-bit).

Only error in Console is:
![image](https://user-images.githubusercontent.com/62972395/133847733-01dd8a49-fe17-4339-8296-5d12fcfc3af7.png)

**Comment by daprice** [comment]
Also getting logged out constantly on iOS Safari.

**Comment by mikekasprzak** [comment]
I'm looking into this (was #1142), but I'm not yet aware of how to consistently reproduce this.

**Comment by mikekasprzak** [comment]
Okay, I think this is fixed. Please let me know if this has resolved the issue for you.

**Comment by daprice** [comment]
I haven’t gotten logged out since about the time of your comment, so it seems to be fixed for me. Thanks!
