### ISSUE TITLE
Toolchain: Issues following a dev environment setup

### ISSUE THREAD

**Issue by mkalam-alami** [ludumdare/ludumdare#221]
Hi,

I've seen the big "BROKEN" warning in the readme but you may be interested in this list of little tweaks I had to do to get things to run (after setting things up as documented):
### Outside the VM
- `cd www/src/tools && chmod 777 *`
- (if the VM was up) `vagrant halt && vagrant up`
### Inside the VM

```
sudo npm install -g svgo less clean-css buble rollup uglifyjs
cd /var/www
npm install
sudo chmod 777 src/tools/*
make
sudo service apache2 restart # I also renamed the Apache configs to remove an extra ^M, not sure if it was needed 
```

I didn't look into it too much but the `all.min.svg` files didn't appear in my `-` folder, though the `svgo` commands seemed to run without errors. So unfortunately I couldn't enjoy the new LD logo in its full SVG glory :P

**Comment by povrazor** [comment]
Ah yes, I have been saying it's broken, but it's not actually broken, just not documented.

Using the `~/vvv` folder should have proper permissions.

There's a few tools that needed newer versions, from 3rd party repos, I just can't remember which ones. SVGO might have been completely broken (that seems to ring a bell). Either that, or it needed an actual current version of NPM and Node (not what ships in the Ubuntu repos). That said, I might just be remembering the hell that was trying to get Grub to support multiple build targets, hence why it's now a Makefile.

On my setup, I have them installed *outside* the VM, and do my builds there. There was a reason for that, but I can't remember what. I run Ubuntu 16.04.

**Comment by povrazor** [comment]
Some notes on installing the toolchain from outside the VM.

(I'm not actually sure which is preferred, inside or out, but I have to get one of my PC's working again)

* Install Dairybox, and follow the instructions there for setting up your repo
* Make sure `node` and `npm` are installed. Depending on the node version, sudo may not be needed.
* From `www`, install tools
  * `npm install` (this installs 
  * `sudo npm install -g svgo`
  * `sudo apt-get install php`
  * `sudo npm install -g less clean-css buble rollup`

... still working on this. I hit a brick wall, the version of NODE ubuntu ships with is too old.

**Comment by povrazor** [comment]
Alright, the above added instructions should work for anyone attempting to install the toolchain. My bad, but it looks like I forgot to push an update to the toolchain itself from way back in August. It was in my repo, but not mainline Ludum Dare's.

**Comment by povrazor** [comment]
Getting PHP7 running in the VM isn't necessarily straightforward.

https://github.com/scotch-io/scotch-box/issues/157#issuecomment-167076859

That said, I did try following my instructions above but with `sudo apt-get upgrade php --fix-missing` instead of install, and it did install. Haven't tested it it that well though. It probably breaks APCu.

**Comment by povrazor** [comment]
A "stock" install of `Starship` has no content, no users, nothing. 

* Run the `./start_mailcatcher.sh` script, and you should be able to sign up for accounts (and not bother anybody).
* You can inject data using PHPMyAdmin. You'll have to download it separately (not integrated yet). Place it in **DairyBox**'s `/dev/` folder (I suggest naming it `/dev/phpmyadmin/). You can then access it via http://192.168.48.48/dev/phpmyadmin/

**Comment by povrazor** [comment]
Alright! This should finally be fixed.

* All required apps are now installed inside the VM, so can always build from inside the VM (it's just slower)
* `~/www` inside the VM is now what you'd expect it to be, and have correct permissions
* Updated README.md with instructions

**Comment by Jezzamonn** [comment]
In the README, the URL for PHPMyAdmin is missing the 'dev' part, it's currently http://192.168.48.48/phpmyadmin/, and should be http://192.168.48.48/dev/phpmyadmin/

**Comment by povrazor** [comment]
Ah shoot. I think I did merge in a fix that corrected this, but I might have messed it up.

**Comment by povrazor** [comment]
Okay this is fixed. I see why it wasn't fixed.

**Comment by Jezzamonn** [comment]
I still get a 404 not found at http://192.168.48.48/phpmyadmin/, after updating and running `vagrant up` again

**Comment by povrazor** [comment]
It was moved to /dev/

**Comment by povrazor** [comment]
You might have to run `vagrant destroy` and `vagrant up` again

**Comment by Jezzamonn** [comment]
Ok, my bad. I was looking at the documentation in my own fork and wondering why the url hadn't been updated 😅  I can access it at http://192.168.48.48/dev/phpmyadmin/

**Comment by povrazor** [comment]
Proudly, I'm going to close this. There are new issues of course (toolchain should generate some sample content), but that is a separate issue.
