### ISSUE TITLE
Login persistence: not persistent

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#272]
There are a variety of situations where you become no longer logged in.

**Comment by kamjau** [comment]
Is there anything I can do to avoid those situations and stay logged in? It seems to log me out whenever I'm not looking, even when it's open in a tab :p

**Comment by povrazor** [comment]
Not yet. It's literally on my end (I implemented it wrong). This **might** be the source of a bunch of pain this weekend. :cry:

**Comment by povrazor** [comment]
This should be fixed now.
