### ISSUE TITLE
Future: Only allow login over HTTPS?

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#274]
One of the complaints I received was that when you login to the HTTP site, then click a link that takes you to HTTPS, it's weird that you need to log in a 2nd time.

Unfortunately, for embedding (and in case of problems) we still need access to HTTP. Not everybody has HTTPS correctly configured. Going 100% HTTPS isn't quite viable for us yet.

Imposing a "no logins" restriction to HTTP seems reasonable, but we are going to need a way to disable it in the query string. Something like `http://ldjam.com/?allow-login`... but a better name than that (`?i-know-i-am-insecure` ?).

**Comment by imerr** [comment]
> Unfortunately, for embedding (and in case of problems) we still need access to HTTP. Not everybody has HTTPS correctly configured. Going 100% HTTPS isn't quite viable for us yet.

wait, what?
Could you elaborate on that?
Except for ancient os'es (which you should /not/ support) I cant think of any reason that might be a thing

**Comment by povrazor** [comment]
> Could you elaborate on that?

Not everybody has HTTPS enabled on their personal web servers, and they may choose to self-host their "to be embedded" versions of games. If we are to put a game in `<iframe>` that links to a non HTTPS URL from the HTTPS site, all modern browsers now freak-out, claiming the connection to the website is no longer secure.

This was an issue earlier in the year, when I was doing the new Twitch and Hitbox integrations. Hitbox supported HTTPS, but Twitch did not (well, it was broken at the time).

To do HTTPS correctly, every asset used to generate a site needs to come from a secure connection.

**Comment by povrazor** [comment]
I suppose alternatively we could just require that all embedded games be hosted on an HTTPS capable website. Getting HTTPS using CloudFlare is pretty easy.

**Comment by karai17** [comment]
I would definitely err on the side of security. If someone wants to use this code to host their own jam site and not use https, maybe you just shouldn't support that.

**Comment by mkalam-alami** [comment]
I also think it's acceptable to restrict game embeds to HTTPS, since the feature is optional anyway (it's a cool feature but not having it doesn't harm).

On the other hand, forcing the user back and forth between HTTP & HTTPS leads to strange situations with user sessions, and security-wise having to login for both protocols removes half of the interest of HTTPS. Not mentioning the additional dev effort.

**Comment by imerr** [comment]
Requiring https in order to be able to embed games on the site sounds reasonable though, just going to have to rely on plain old links if you can't have https
Its basically free nowadays anyways

**Comment by povrazor** [comment]
Yeah, I think I am now leaning this way: HTTPS embeds only. Thanks for the feedback everyone.

**Comment by povrazor** [comment]
Ah, it looks like Newgrounds and Kongregate, neither of them support HTTPS. Though we don't have anything in place with them (yet), it does make me curious. Is there any Flash weirdness when it comes to HTTPS?

**Comment by povrazor** [comment]
Okay, there's a potential fix for the original issue. Login/register buttons don't show up on the HTTP site. Instead, a big "go to the secure site" button takes their place. It go live with the next update.

**Comment by povrazor** [comment]
Fix is live.
