### ISSUE TITLE
Can't suggest themes

### ISSUE THREAD

**Issue by blinry** [ludumdare/ludumdare#284]
When I try, I get a "Please wait..." message, which stays there for at least 5 minutes. When I refresh, I still have 3 suggestions left. Recent Firefox/Chromium, Linux, and from Japan, in case that matters.

**Comment by povrazor** [comment]
Ah shoot. I might have messed this up last night before bed. Investigating...

**Comment by povrazor** [comment]
Okay, this should be fixed now. Sorry about that. Late night. My bad.

**Comment by blinry** [comment]
Yup, can confirm! :) Thanks, and take care!
