### ISSUE TITLE
UX: No logout button

### ISSUE THREAD

**Issue by blinry** [ludumdare/ludumdare#285]
A way to log the current user out should be exposed in the interface.

**Comment by povrazor** [comment]
Yep! I haven't had time to finish the drop-down boxes that pop up with Notifications and when you click your Avatar. They go under the Avatar one.

**Comment by tanrax** [comment]
thx

**Comment by pfefferminzz** [comment]
First anniversary of this issue is tomorrow. If it's annoying to add a dropdown menu, the logout button could go here for now:

![ld-logout](https://user-images.githubusercontent.com/5459440/33243934-e47f6360-d2ee-11e7-8681-7a17ee12071e.png)

**Comment by povrazor** [comment]
This got lost in a commit that was never pushed.

**Comment by zwrawr** [comment]
Bump again

**Comment by zwrawr** [comment]
It only took a year!

**Comment by povrazor** [comment]
:fireworks:

**Comment by pfefferminzz** [comment]
Thank you very much!
