### ISSUE TITLE
Current phase should be displayed prominently

### ISSUE THREAD

**Issue by blinry** [ludumdare/ludumdare#288]
Like, on top of the page, or in a huge, colored box in the sidebar. "Upcoming" phases are interesting, as well, but the current one is the one that really matters.

**Comment by blinry** [comment]
That's all I got at the moment. Thanks for all your hard work, @povrazor, make sure to get enough sleep!

**Comment by povrazor** [comment]
Yeah, current phase is missing. Again, it's related to signups (which are not in yet).

**Comment by povrazor** [comment]
Okay, I put it in the title bar for now. When signups (and actives) are live, it'll replace them.

**Comment by zwrawr** [comment]
Current phase is shown if your logged in.

**Comment by povrazor** [comment]
This is fixed.
