### ISSUE TITLE
Delete suggestion button shows up as a question mark

### ISSUE THREAD

**Issue by alimoeeny** [ludumdare/ludumdare#295]
On the theme page `https://ldjam.com/events/ludum-dare/37/theme/`
after you create a suggestion, the `delete` button (which is just an X in Lato font), shows up as a question mark in a box, not as `X`, 
Using latest Chrome Beta on a mac running latests macos.

**Comment by povrazor** [comment]
Ah interesting. Okay, I can fix that with the SVG `X`.

**Comment by povrazor** [comment]
Okay, this should now be fixed.

**Comment by alimoeeny** [comment]
Is Fixed.
