### ISSUE TITLE
flash of "no posts" while waiting for ajax dl

### ISSUE THREAD

**Issue by McFunkypants** [ludumdare/ludumdare#310]
During page load the default html shows "no new posts" for a second or two while waiting for the data to download. During peak times this is all people will see for a brief moment (or perhaps at all!). Suggestion: better to not have ANY text while loading versus temporary "incorrect" info that will cause headaches and complaining.

![screenshot-11-28-2016-13](https://cloud.githubusercontent.com/assets/2111957/20696843/e8c97e18-b5aa-11e6-8a24-b6ea7f701625.png)

**Comment by povrazor** [comment]
Agreed. It's nasty.

I currently don't have caching enabled (had to gut it from the code). So part of it will be fixed by that (the delay and flashing). 

I also still need to add a little spinner, and perhaps some transitions.

**Comment by povrazor** [comment]
Okay, "no posts" is fixed. Spinner is in too. There's still a flicker when pages change, but that's a different issue.
