### ISSUE TITLE
Default to Secure/TLS Site

### ISSUE THREAD

**Issue by mcmahoniel** [ludumdare/ludumdare#313]
Navigating to "ldjam.com" in your browser takes you to http://ldjam.com. You cannot (for good reason) log in to the site this way; you must click "Go to secure site" to be redirected to https://ldjam.com to log in and participate.

Rather than requiring that extra step, I suggest defaulting to https://ldjam.com, including a redirect for people who hit the HTTP version directly.

**Comment by povrazor** [comment]
My brain is a little mushy right now, but there is a relatively exotic use case for the insecure site... I just can't remember what it is.

It is probably good advice to send everyone to HTTPS though.

**Comment by josefnpat** [comment]
Some programming languages have `file_get_contents` features, but they only work with http (as opposed to https)

I think that public API access could be http, but I would highly suggest redirecting the user to the https site right at the start. Maybe even at the apache2/nginx level.

Would you like me to write a PR for this?

**Comment by alimoeeny** [comment]
I am with @josefnpat , it's just a few lines in `nginx.conf` or whatever `nginx` config is called on your OS. Or it is an ELB setting if you are on AWS? Are you? 
I won't say no to forcing people to call the API on https either :) but I might be too optimistic / naive. 
I'd be happy to help with the nginx config (or ELB) if it speeds things up.

**Comment by Yngwarr** [comment]
Hmm, I see this issue is still present and it's super annoying. Are there any reasons for not redirecting users to secure site?
