### ISSUE TITLE
Header says 'Suggest Themes' yet links to Theme Slaughter

### ISSUE THREAD

**Issue by retroverse** [ludumdare/ludumdare#319]
![gif](https://cloud.githubusercontent.com/assets/16392483/20741183/b83851de-b71c-11e6-99fd-5f3af7dc89e2.gif)
New site is looking really cool, very excited, good luck!

**Comment by povrazor** [comment]
Yes, you can tell I hacked that in. ;). Thanks for the note.

**Comment by povrazor** [comment]
Okay, this should be fixed (until the next time).
