### ISSUE TITLE
'Burn' symbol beside 'Yes' and 'No' voted 'Recent Themes' in Theme Slaughter

### ISSUE THREAD

**Issue by wsrdzg** [ludumdare/ludumdare#320]
I voted one theme with 'yes' one with 'no' and then multiple with 'yes' but under 'Recent Themes' only the first one had a check mark symbol next to it. All other had a burned symbol. I couldn't recreate this a second time after logging out and in again. So I'm not sure if you have fixed it already.

**Comment by povrazor** [comment]
The fire is the "something went wrong" icon. I'm glad it caught you attention enough to post this, 'cause that's what I was hoping it did. :)

I'm looking in to adding a hover that shows the internal value when you hover over the symbol now.

**Comment by povrazor** [comment]
Okay, if you (or anybody) sees fire beside a theme again, hover your mouse over it and let me know what it says. Thanks!

**Comment by noah-potter** [comment]
I'm not getting anything when I hover over the fire. I'm just getting a 401 from the server for each vote request. Happened around the 5 minute mark from signing in and starting to vote

**Comment by povrazor** [comment]
Okay, it looks like you get fires when your session expires (yes, sessions expire way too soon, that's a different bug). There's now a popup dialog when this happens, informing you to log in again.

**Comment by povrazor** [comment]
This is now fixed.
