### ISSUE TITLE
Theme page does not warn you that you have been logged out and your votes don't fail

### ISSUE THREAD

**Issue by alimoeeny** [ludumdare/ludumdare#328]
Kept rating themes on https://ldjam.com/events/ludum-dare/37/theme/ while the server must have been restarted under me, or for some reason was logged out midway, went up to 300 votes then refreshed the page and noticed am logged out, when logged back in, half of my votes had gone. 
There were no visual indication that they are failing to register while I was voting.

**Comment by dkniffin** [comment]
This definitely looks similar to #327

**Comment by dkniffin** [comment]
And #320

**Comment by povrazor** [comment]
This should now be fixed (you get an popup dialog informing you to re-log in).
