### ISSUE TITLE
Use Ansible or similar for deployment scripts

### ISSUE THREAD

**Issue by dkniffin** [ludumdare/ludumdare#329]
I know this won't get addressed during this LD round, but I think you should definitely look into using something a bit more standard for devops, like [ansible](https://www.ansible.com/), or [chef](https://www.chef.io/), instead of custom shell scripts. There are many good reasons for this, but the biggest in my opinion is that there are a lot of open source code that's been written for these platforms, that will do the work for you, usually in a better way. For example, I saw you want to switch from MySQL to MariaDB (#301). The MariaDB setup would be as easy as adding a few lines to a config file.

**Comment by povrazor** [comment]
FWIW it's not for deployment, but for the toolchain, which uses Vagrant. The 'box' it's based on (scotchbox) needs a software upgrade (crossgrade).

**Comment by dkniffin** [comment]
Forget this issue. I think you've done a great job of getting this stuff working in a sustainable way. I didn't even realize you were using Vagrant and such. Keep up the great work!
