### ISSUE TITLE
Plans for global/centralized state management?

### ISSUE THREAD

**Issue by noah-potter** [ludumdare/ludumdare#333]
I was wondering if there were plans to use something like redux or mobx? This seems like it'll be a fairly complex app and might benefit in the future from the structure these libraries provide.

**Comment by povrazor** [comment]
At the moment no, but that's in part because I'm not entirely clear how it helps. I may have already ended up rolling my own.

I'm also using Preact, not React, so that potentially confuses things as well.

**Comment by noah-potter** [comment]
It's hard to say how beneficial it would be at this point since there are just a few features and I don't know all the capabilities of the old site (and I only know redux so I can't speak for mobx). However, there are a few areas that could become issues and in my experience it doesn't take many features to benefit from something like redux.

Such as when you call the api from within components and store the data locally. It's going to be hard to reuse that data in other components. Also, that data's existence depends on that component being mounted. Any time you unmount a component you'll need to make another api call even if it's not necessary (such as a quick page/view change).

Redux would also separate data management from the view, leaving you with simpler components.

Farther in the future, as your data becomes more complex, redux would give you things like reselect (handles connecting data from different domains into something a component can use easily), redux-saga, and normalizr, 

There's a lot more, but it's hard for me to come up with any since the app is basic at this point. Of course you can roll your own for this stuff but redux is solid and it'll be easier for contributors to work with a more standardized library than a custom one.

Again, in my experience it doesn't take many features to start benefiting from something like redux so I'm just trying to bring up the idea early. (I don't know mobx but I see good things mentioned about it)

**Comment by povrazor** [comment]
Yes, I definitely need a shared local data pool. It's something I haven't ported over from an earlier incarnation of the site yet. That said, it wouldn't simplify the code too much. I would still need to use Promises, since getting the data could be delayed, but it would mean some of the complex checking and conversions that happens in the promises could get removed. It's something that needs to be done eventually. I just need to see why the 3rd party solution is better.

**Comment by noah-potter** [comment]
I didn't realize you were planning to pool the data already. In that case my argument is that a lot more people know how to work with any popular 3rd party solution than a custom one and that using a popular 3rd party solution usually comes with a valuable ecosystem of tooling and plugins.

I'm not arguing against Promises, they're great.

Even if you end up rolling your own for this app, at least take a look at redux and/or mobx if you haven't. They've got some really cool ideas

**Comment by povrazor** [comment]
Yes, I will take a look at them. I appreciate you reaching out to ask me about them (it's why I use LESS, 'cause I didn't like what I saw when I was encouraged to use SASS). Sometimes I need a good nudge like this to make me do my homework. ;)

What I meant by promises is they're perhaps the only code that gets simpler by switching to a global pool, but they don't go away with a pool. Each component still needs to store a copy (or reference) to the data it cares about, they just wont have to hit the server for it. I'm already hiding Fetches to the REST API calls from the components with a JS API. The next step would have been to make a version/variation that stored data in a local cache, and returned the cached version. I'm doing something similar server side (or I was, most calls are raw and uncached).

**Comment by noah-potter** [comment]
I'm glad you're open to input. Yeah, I used to use SCSS, but switched to JSS as it really suits component oriented design. I'm really enjoying it. You shouldn't just accept what the masses say, but that also doesn't mean they have no merit.

I should mention that redux isn't a library and I'm more advocating for using a redux architecture.

I see about the promises. Simpler code isn't the only goal though. It's also about good separation of concern, organization, and predictability. I guess what I really meant to describe in my original post was that I saw (coming from redux background) some of your app's responsibilities overlapping and that it could lead to headaches, such as your register component being a view, handling registration implementation details, mail-sending details, and status details. It's just a lot for one component when in redux the component would just display ui and other files would handle how to execute actions and handle the response in a way that's predictable, allowing you to quickly find out how something works and where/if something went wrong.

**Comment by povrazor** [comment]
>  I guess what I really meant to describe in my original post was that I saw (coming from redux background) some of your app's responsibilities overlapping and that it could lead to headaches, such as your register component being a view, handling registration implementation details, mail-sending details, and status details.

Much of what you're suggesting is already handled. The components (Dialogs) are relatively thin, just storing the data needed to render or action them. Actually registering is handled by the backend, often with a simple single function call. The only way they get any thinner is if I make some derived components, like a textbox that automatically validates e-mail addresses or such.

**Comment by noah-potter** [comment]
They are thin. It's hard to see how it will handle future complexity so I'll just drop it and revisit this if it actually becomes an issue.

Also, if you used something like webpack you could use seperate bundling of 3rd party libraries and multiple entry points to delay 3rd party library loading. Which would let you not have to worry as much about 36K or even 500K-1M.

Also, have you looked at react-router and the history api? I noticed the app doing full reloads and it might be faster and smoother looking if you just pushed a route and only changed the content components.

**Comment by povrazor** [comment]
> Also, if you used something like webpack you could use seperate bundling of 3rd party libraries and multiple entry points to delay 3rd party library loading. Which would let you not have to worry as much about 36K or even 500K-1M.

Yeah, I use Rollup.

As for file size, this is an area where I personally disagree with a lot of the common web wisdom. I come from a low level/embedded/gamedev background, so even if most web developers don't care about file size, I do. :)

I have 3 binaries. I'll paste what the toolchain outputs for reference:

```
[JS]   GZIP:  49629  (78171)  [Minified:  171038]  [Original:  303997]
[CSS]  GZIP:  5645   (8538)   [Minified:  30004]   [Original:  48619]
[SVG]  GZIP:  19681  (19703)  [Minified:  59541]   [Original:  59770]
```

So roughly 74k for everything.

This is everything the site/app needs to run. A 50k binary, and some other data to make it look nice. It doesn't need to load any 3rd party dependencies to run, and I like it that way. Breaking up that 50k wouldn't realistically make it load any faster. Assuming I didn't change anything, it doesn't even need to be re-downloaded.

Most of that 50k is polyfills, so older browsers (IE 11+) can work. Remove that, and we'd even be legal in a 64k demoscene compo. ;)

> I noticed the app doing full reloads and it might be faster and smoother looking if you just pushed a route and only changed the content components.

It's actually not doing full reloads, but the site is dumb right now and triggers a full redraw and re-downloads of some child element data every time. As I mentioned earlier: it needs caching. I briefly looked an equivalent of react-router, but I forget exactly what I didn't like. I think we disagreed about how URLs should be formed.

**Comment by noah-potter** [comment]
Ah, thanks for detailing that out. Looks like a lot of this is difference of opinion, not lack of awareness. Carry on!

**Comment by povrazor** [comment]
Ha, well either way, it was nice chatting. :)

**Comment by povrazor** [comment]
Sorry for the necrothread, but apparently I don't have a better issue to drop this in.

https://twitter.com/_developit/status/938485861569761280
