### ISSUE TITLE
Theme Slaughter: Show stats!

### ISSUE THREAD

**Issue by karai17** [ludumdare/ludumdare#345]
I would like to know how many themes there are, how many I've voted on, how many I've Yes, No and Flagged, and a general breakdown of where I sit within the rest of the community. :)

**Comment by povrazor** [comment]
Good idea.

**Comment by karai17** [comment]
Yeah, I remember those and I really liked them. Simple text stats would be good enough for now though.

**Comment by local-minimum** [comment]
So what does grade mean here if we are talking theme-stats?

**Comment by povrazor** [comment]
What are you using for the chart?

**Comment by zwrawr** [comment]
The example above is on the event stats page. It's the number of games that got x number of rating.

The chart is native, seemed over kill to add a charting/graphing library for a few piecharts. (And i wanted something complex to work on so i could relearn some css)

If we end up needed lots of graphs then we'll probably need a library, but right now we only need piecharts.

**Comment by povrazor** [comment]
Cool. :smile:

**Comment by local-minimum** [comment]
That explains why I was a bit confused, the data being for the other stats page. Still very nice.

**Comment by zwrawr** [comment]
Yea, i miss remembered what the issue was.

**Comment by zwrawr** [comment]
Closed By #1275
