### ISSUE TITLE
TV: Hitbox Thumbnails are missing (was Twitch thumbnails are missing, but it's hitbox)

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#360]
![missingstream](https://cloud.githubusercontent.com/assets/1570313/20863864/ae77a846-b9a8-11e6-9d52-befbab5a35ce.png)

I blame Twitch for this. So note to self: set some minimum dimensions.

**Comment by povrazor** [comment]
Ah, this is actually caused by hitbox.

![hitboxjerk](https://cloud.githubusercontent.com/assets/1570313/20863895/b9334fd2-b9a9-11e6-8408-bec1bc4d63f0.png)

**Comment by mikekasprzak** [comment]
Hitbox is dead.
