### ISSUE TITLE
Markdown: Bad apostrophe glyph?

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#378]
It needs to be checked, but the markdown parser might be generating an incorrect apostrophe.

https://twitter.com/DevDejvo/status/805455254552739841

Switching the file to UTF-8 mode may fix.

**Comment by ishanpm** [comment]
JSYK, I had a similar issue (Android w/ Chrome) with the icon fonts on the "Yes" and "No" buttons for the theme slaughter.

**Comment by povrazor** [comment]
As expected, the locale was not set to whatever I use. ;)

**Comment by povrazor** [comment]
Another example, this time on a Swedish Android phone.

https://twitter.com/jxz_2000/status/806039014046310400

**Comment by povrazor** [comment]
Okay, I believe this is fixed now. The problem was the apostrophe.

http://stackoverflow.com/questions/27470859/apostrophe-converting-to-question-mark-in-textview

The fix was to use the `&rsquo;` HTML glyph instead of the unicode character (leaving it up to the browser to decide how to render it).

**Comment by povrazor** [comment]
No, apparently it didn't fix the original issue.

/me shrugs

**Comment by povrazor** [comment]
Hooray! It is actually fixed! User had a bad copy cached.
