### ISSUE TITLE
Resource Pack

### ISSUE THREAD

**Issue by karai17** [ludumdare/ludumdare#380]
Would be nice if there was a resource pack for people who want to use Ludum Dare branding for streams or splash screens, etc. Most notably, an SVG/high res logo in various shapes and form factors.

**Comment by povrazor** [comment]
Agreed. #194

**Comment by povrazor** [comment]
For the time being, you can grab the unprocessed SVG files of the `Ludum` and `Dare` logo words here.

https://github.com/ludumdare/ludumdare/tree/master/src/icons/ludumdare

**Comment by karai17** [comment]
I opened up those SVGs in Blender to make my own processed logo and I noticed that the glyphs weren't all at the same X base level. When normalizing all the bases to 0, the glyphs now look a bit off height-wise.

![image](https://cloud.githubusercontent.com/assets/590332/20894332/5590fe46-baeb-11e6-968a-3fe297c6f9a3.png)

**Comment by povrazor** [comment]
Yes, the glyphs work best if you leave them. Half-circles do tend to droop more than flats-sides.

**Comment by zwrawr** [comment]
Colored svg with a black background.
