### ISSUE TITLE
Content: Edit Bar

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#381]
The bar is effectively the same as what Github does, but the header and footer merged together.

![gith1](https://cloud.githubusercontent.com/assets/1570313/20868905/49ef7498-ba35-11e6-9583-827fcffe73f9.png)
![gith2](https://cloud.githubusercontent.com/assets/1570313/20868906/4b1d4ee4-ba35-11e6-8150-37bc2ae4a5b3.png)

In our case, we wont have shortcuts for styles (not yet).

```
[ EDIT ] [ PREVIEW ]                 [ + ] [ SAVE ] [ PUBLISH ]
```

... I can't remember what the `+` was for... heh.

**Comment by karai17** [comment]
+1 for markdown support.

**Comment by povrazor** [comment]
Already there. :) :+1: emoji using the same syntax as github too.

**Comment by karai17** [comment]
You're the hero we've always needed, but never deserved.

**Comment by Jezzamonn** [comment]
https://simplemde.com/ ? This is a potential open source option. I haven't looked in to all the details though, but it's basically syntax highlighting for markdown, with nice features like auto-continuing lists. Even though it's not wysiwyg, it's pretty readable 'cause it's markdown and all.

I still think a WYSIWYG might be nice for the non-coder Ludum Darers. Or those not familiar with markdown.

**Comment by mkalam-alami** [comment]
I agree with @Jezzamonn, we should not forget that not all LD users are tech-savvy. I think not having formatting buttons will make quite some people uncomfortable with posting.

I assume the long-term goal is to have something homemade, until then *SimpleMDE* seems like a good solution, that could be embedded with little effort. The 260KB price tag, while reasonable to me might put you off though... I looked into alternatives but couldn't find anything better (more lightweight, no dependencies, fitting theme, popular/stable enough).

**Comment by povrazor** [comment]
Yeah 260KB is out of the question. The site including all the SVG assets isn't even 100k.

**Comment by mkalam-alami** [comment]
Here's a couple things to put most of these issues in perspective:

* Right now the YouTube embed for the LD37 keynote adds 1.2MB of JS to ldjam.com (450k gzipped).
* Github itself, while being targeted at developers, has edit bars everywhere, including in comments. I think the editor holds a good portion of the 1.5MB of JS the site has.

Anyway whatever the editor is, consistency will be a nice change from the old site indeed :P

**Comment by povrazor** [comment]
> the YouTube embed for the LD37 keynote adds 1.2MB of JS to ldjam.com

Yes you are correct. On the TODO list (I forget the issue number) is to do like we're do with the streaming widget: fetch an image to display _instead_ of automatically embedding. Ideally, all code from outside sources/embed should be opt-in. I want the site to be as light as possible, unless you specifically choose to use certain features.

**Comment by karai17** [comment]
>I want the site to be as light as possible

And yet you inexplicably chose to write the entire thing in JavaScript instead of using actual HTML...

**Comment by povrazor** [comment]
Well, you might not realize it, but the an entire page request is now **1224 bytes** uncompressed.

```js
{  
   "status":200,
   "caller_id":11,
   "node":[  
      {  
         "id":10524,
         "parent":1,
         "superparent":0,
         "author":11,
         "type":"post",
         "subtype":"news",
         "subsubtype":"",
         "published":"2017-04-10T18:08:42Z",
         "created":"2017-04-10T18:08:42Z",
         "modified":"2017-04-10T18:30:33Z",
         "version":10647,
         "slug":"theme-slaughter-is-live",
         "name":"Theme Slaughter is Live!",
         "body":"Theme Selection has begun :ballot_box:, with the _Theme Slaughter Round_ :crossed_swords:. \n\nGet started here: [/events/ludum-dare/38/theme](/events/ludum-dare/38/theme)\n\nAlso, I've started rolling-out the **actual useful features** of the website. There's still a few more things to finish up before I let everybody make posts (for one, the feed loads too many posts). That said, if you go to your user page (i.e. click the people icon in the top-right corner), you should notice a little pencil icon on your user page. Click that, and you can edit your bio.\n\nBlogging works in much the same way (I'm using it right now to type this post).\n\nAnyways, give **user page editing** a try. \n\nIf you run in to any issues, you can [contact](/contact) me.",
         "path":[  
            {  
               "parent":1,
               "slug":"theme-slaughter-is-live"
            }
         ],
         "meta":[],
         "link":[],
         "love":94,
         "love-timestamp":"2017-04-12T17:49:11Z",
         "notes":0
      }
   ]
}
```
In practice it's actually compressed, so make that 705 bytes.

That's an improvement over 68 KB per request.

```bash
wget http://ludumdare.com/compo/2017/04/04/ludum-dare-38-on-the-alpha-website-ldjam-com/

# ...

2017-04-12 14:17:11 (301 KB/s) - ‘index.html’ saved [68320]
```
