### ISSUE TITLE
UI: Drop Down List

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#384]
Needed by both the User dropdown and Notifications.

Should have an invisible box that fills the window (similar to dialogs). When you click on it, the focus is lost, and the dropdown is closed.

There's some other stuff I can't remember too.

**Comment by zwrawr** [comment]
We have these implemented in a few places.
To be closed.

**Comment by local-minimum** [comment]
Needs fixing for notification dropdown

**Comment by povrazor** [comment]
Lets close this and open new issues related to fixing uses of it.
