### ISSUE TITLE
User Pages: Edit User Account Settings

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#385]
`/users/my-name/edit` - i.e. extra-slugs of `user` types

This is where all that fun stuff, like changing your username, your e-mail address, setting a real name, twitter, twitch, password, 2fa, and others go.

**Comment by CowboyBebop** [comment]
Why was this closed? No one to finish the issue or some other problems like storage size increase?

**Comment by mikekasprzak** [comment]
I believe at the time you couldn't edit pages. You can now edit pages.
