### ISSUE TITLE
Toolchain: Preloaded assets ignored?

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#403]
I've started getting these errors in the VM's console.

![preload1](https://cloud.githubusercontent.com/assets/1570313/20921819/d8252e9e-bb73-11e6-97f8-9074405d2abe.png)

It is true, our assets are being loaded twice.

![preload2](https://cloud.githubusercontent.com/assets/1570313/20921831/e5ef809c-bb73-11e6-811e-d78bbca4d35a.png)

**Comment by povrazor** [comment]
To contrast, the real website works fine. The preloads get converted in to HTTP/Push requests.

![preload3](https://cloud.githubusercontent.com/assets/1570313/20921925/493aa078-bb74-11e6-97a5-de05c35b3268.png)

There's still a lot of curious idle time though. Why?
