### ISSUE TITLE
Countdown timer misstep

### ISSUE THREAD

**Issue by josefandersson** [ludumdare/ludumdare#415]
I had the site with the ludum dare countdown in the background and notice that it jumped from 3 days 0 hours and 0 minutes to 2 days 24 hours and 59 minutes when it should be 23 hours.

**Reloading the page will reset the timer to the correct time though** as this is only the client-side javascript code for the timer that is wrong.

![Image of the thing](https://i.imgur.com/Iv91Kjv.png)

**Very low priority problem.**

**Comment by povrazor** [comment]
Calling @StormBurpee

**Comment by zwrawr** [comment]
[Issues cased by this line](https://github.com/ludumdare/ludumdare/blob/master/src/com/sidebar-countdown/countdown.js#L118)
This should be set to 23 not 24 .
