### ISSUE TITLE
Theme Slaughter: Don't give users duplicate themes

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#45]
Right now we're taking a random theme from the available themes pool.

In the future, change it so that we don't give people duplicate themes.
## Goals
- Every user gets different themes
- Ideally a different theme order per user

Needs: A good algorithm, implementable in an SQL query.

**Comment by povrazor** [comment]
The typical algorithm for this is to take an array of all IDs, randomly sort them, then read them linearly.

If a user has no votes, we can fall back to giving them a random theme, and that becomes their Base ID for stepping through linearly for Ids. Once there are no higher IDs, you loop back to the front.

The main problem with this is that everybody eventually gets the same set of Ids.

**Comment by povrazor** [comment]
Another option is abandoning the idea of using SQL for randomizing. 

Instead, store a RAM cached copy of the complete list of theme IDs, and a per-user cached copy of the id's of themes they've voted on. Do a php `array_diff()` on the two sets, and then return a random Id from the remaining set.

Any time a user submits a vote, the per-user cached copy array needs to be updated. Only for new themes, not edits. It would be a shame to have to do an extra check (does ID exist).

Since these are RAM cached, with the exception of the complete list, user lists will have a low TTL (lets say 5 minutes). Any time they make an update, reset the TTL. 

As of right now, with a maximum of under 5000 suggestions, that means roughly 40k of RAM used by any "worst case" users (assuming PHP doesn't inflate basic RAM usage much). Worst case, lets say 100k RAM to store 5000 records. That means 10 users per MB of RAM, voting with the same 5 minute period. To date, worst case scenario is over 1000 users accessing the site at the same time, but this is during Theme Announcements, not voting. And remember, we need to share RAM. The server(s) right now have 1 GB of RAM each. 100 MB of RAM gives us roughly 1000 users with maxed out voting.

The TTL could be lowered to 2 minutes, to more quickly free the memory. Or even 1 minute since the point really is for fast consecutive voting.

If a user is voting with muiltple devices, there is a chance of RAM cached data getting out of sync, since APCu doesn't exactly do locking (it does locking, but not the locking we need). If the writes to RAM are within MySQL blocks that lock, that would resolve it, but maybe it's okay that it's not perfect. Fact is, right now we get dupes, and that makes people sad. With the above setup, dupes would only happen if you're physically voting on 2+ machines.

**Comment by ttencate** [comment]
Could you just send the client a list of _all_ themes, plus the set of IDs they have voted on already, and do all the shuffling and deduplication in JavaScript? If it's just a few thousand themes, it shouldn't break the bank. And since the list of themes is static so it can be aggressively cached in server RAM.

**Comment by povrazor** [comment]
The list is *mostly* static (items get purged during the week), but yes, doing it client side is totally doable. It would certainly save server RAM this way, moving logic to the client. Not a bad idea.

**Comment by povrazor** [comment]
This is fixed! Rejoice!
