### ISSUE TITLE
Title on main page is ldjam.com

### ISSUE THREAD

**Issue by pta2002** [ludumdare/ludumdare#459]
It should probably say 'Ludum Dare'

**Comment by ComputerOverlord** [comment]
Sounds like an easy HTML fix..

**Comment by zwrawr** [comment]
The Content (users, pages and post) create there title via their nodes name. ldjam.com is the root nod and so has no name, so it fall back to the web address.

This bit in content probably needs changing, [content.js#L25](https://github.com/ludumdare/ludumdare/blob/master/src/com/view-content/content.js#L25).

**Comment by zwrawr** [comment]
Changing it to fallback to "Ludum Dare" seems reasonable as no other nodes should have empty names.

**Comment by povrazor** [comment]
Ludum Dare's **true** root node is not the root node right now. Symlinks aren't working correctly yet, so I defaulted all sites to the common root (but both Jammer's are disabled so most people didn't likely notice).
