### ISSUE TITLE
Confusing use of human shaped icon

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#474]
The human silhouette is used for both registering new user and accessing your own user info while logged in. Especially on mobile this becomes very confusing as there are no helping texts.

_Suggestion: Adding a plus sign when the icon refers to adding/registering new user._

Current, the svg element of the html says:
`<use xlink:href="#icon-user"></use>`

And if changed to:
`<use xlink:href="#icon-user-plus"></use>`

The icon looks as suggested and this issue is fixed.

**Comment by zwrawr** [comment]
Made a pull request to implement this for the Create account button.

Adding users to events and games should also user this icon.

**Comment by povrazor** [comment]
That is a good idea @zwrawr. I will merge that in once I return with dinner. :+1:

**Comment by povrazor** [comment]
Okay, this fix and live.
