### ISSUE TITLE
Too many CDNs.

### ISSUE THREAD

**Issue by karai17** [ludumdare/ludumdare#478]
This website has WAY too many CDNs and other junk. It makes the site a lot slower and causes issues with privacy extensions and ad blockers.

Speaking of ad blockers: doubleclick? come on. Let's not shit up the website with tracking and ads, okay?

**Comment by shakesoda** [comment]
also affects me, without adding exceptions to privacy badger I can't see the emoji, etc, and I really would rather not have to do that.

**Comment by zwrawr** [comment]
Emoji works fine with privacy badger on default settings http://prntscr.com/dhjc1b

**Comment by karai17** [comment]
Not for me, I had to switch jsdelivr from red to yellow. Also the amount of things that show up on privacy badger has gone up like 400% in the past week. I see no reason for this.

**Comment by zwrawr** [comment]
The double click appears to be from the embedded twitch player rather than the main site http://prntscr.com/dhjd4d

**Comment by zwrawr** [comment]
ytimg.com appears to be related to the webplayer for embedded youtube videos.
http://prntscr.com/dhjevj
Its there because there is an embedded Youtube player in one of the posts(the keynote).

**Comment by zwrawr** [comment]
And jtvnw is doing twitch thumbnails http://prntscr.com/dhjg4y .

jsdelivr is doing requests for the emoji's

and you have google fonts , that should be obvious.

**None** of these seem unneeded to me.

**Comment by karai17** [comment]
Why can't the emoji be hosted locally? Why do they need to come from some third party CDN?

**Comment by povrazor** [comment]
The majority of issues are caused by that YouTube embed. Visit any page but the homepage and you'll see way less issues.

**Comment by povrazor** [comment]
As for the others used:

* We're using Cloudflare as a Proxy/CDN, so you see a rogue cookie or two from them
* `static.jam.vg` is our static file host, used across all 3 sites (two of which I haven't talked about much yet)
* Emoji is hosted on EmojiOne's servers, as they actually regularly update the graphics. If it does become unresponsive/problematic, we'll host them ourselves.
* We are using a Google Font.

**Comment by karai17** [comment]
I think a major point is being missed here: I don't want to be tracked by a bunch of third parties through Ludum Dare. The fact that simply visiting the front page now has Privacy Badger *and* uBlock Origin screaming at me is not something that makes me happy.

**Comment by povrazor** [comment]
Well like I said, eventually we will 'require a click' for the embeds. That should help. Everything else is static  files, and with the exception of Cloudflare, don't send cookies.

**Comment by karai17** [comment]
Hm.

**Comment by zwrawr** [comment]
Finally addressing youtube embeds #717
