### ISSUE TITLE
CORE: Game Browsing

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#493]
For obvious reasons, we need to be able to browse games submitted to events (and otherwise).

![browse](https://cloud.githubusercontent.com/assets/1570313/21125303/9d362f74-c0b2-11e6-8169-fec0bba72fcc.png)

This is what browsing looks like right now, and it's not great. There are some good ideas here though, as the master list can be filtered by things.

At our scale, it may be worth having filters for A-Z, and #'s, and make that the standard way to browse. By default it's A-Z plus #'s, but clicking on them creates a list of just those games beginning with that letter.

This should help those people that try to find their game in the list immediately after submitting.

It would be nice if the search results reported when it was last updated. Of course, if it's a fresh search it returns 'now', but if we cache results of a search, at least say the results are a few minutes old.

**Comment by povrazor** [comment]
The Itch.io Ludum Dare browser does provide a nice alternative way to browse games.

http://ludumdare.itch.io/

![itchbrowser](https://cloud.githubusercontent.com/assets/1570313/21125513/3c3c1498-c0b4-11e6-83e0-8591031ee455.png)

![itchy-options](https://cloud.githubusercontent.com/assets/1570313/21125515/4078f95e-c0b4-11e6-81d4-1afc4ff8f60e.png)

The browsing should at least be as good as this. We've had lackluster browsing for long enough. :wink:

**Comment by povrazor** [comment]
The judging interface leaves much to be desired as well.

![judgeld](https://cloud.githubusercontent.com/assets/1570313/21125563/b15f7ef4-c0b4-11e6-81d7-7bf1f025ec1a.png)

**Comment by povrazor** [comment]
#81 I've started collecting similar notes for the Submission Form.

**Comment by Jezzamonn** [comment]
An additional thing to put in the search is number of players, and what additional peripherals are needed (e.g. VR equipment, controllers, etc).

I'm imagining some way to tick what platforms/game styles you can play (and filter out the ones you can't). So I'd tick just web and mac at the moment, and single player games only (and no VR games)

I'm noticing this now as I'm rating games and finding that I can't play most of them! Which I guess happens when the people with limiting games play and rate a lot -- their games end up on the front but don't get more players. It'd be nice to filter to just games I could play.

**Comment by povrazor** [comment]
Ah, I thought I had an item here for `Tags`, but I apparently don't.

Part of what you're suggesting is taken care of by `Tools` and `Tags`. `Tools` being the things used to make a game (Unity, Photoshop, etc), and tags being the elements of a game (Linux, Android, Multiplayer, VR, GamePad, Colorblind, etc).

I like the idea of creating a personal rating profile of elements (things you can and can't play), and filtering based on them.

**Comment by zwrawr** [comment]
#689 is the start of this. Adds a way to browse games but not any advanced searching features.

**Comment by randomjammer** [comment]
As a temporary workaround I made a quick and dirty full-text search app: https://randomjammer.github.io.
Feel free to promote it or delete it (I have invited you to become "collaborators").
I hope it will be somehow helpful...

**Comment by povrazor** [comment]
It sucks, but it exists.
