### ISSUE TITLE
Toolchain: Generate a bunch of useful nodes

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#499]
To make it easier to get started, generate a bunch of useful nodes for people using the toolchain.

Examples:

* A user (or two)
* Some news posts
* an event (or two, in different states)

etc

**Comment by povrazor** [comment]
This is sort of #491, but more explicit.

**Comment by spirulence** [comment]
Combining a little research with a conversation with Mike on gitter:
> Sample posts, sample news posts, sample games, sample users, etc.

The extra script should create a few of each of these:

- [ ] posts
- [ ] news posts
- [ ] games
- [ ] users
- [ ] events
- [ ] tags

**Comment by mikekasprzak** [comment]
Calling this done thanks to the simulator (though it needs to be better explained).
