### ISSUE TITLE
Static Server: WebP support

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#52]
Add a simple script for detecting WebP support. Then accordingly any Image URL munging should correctly remap any `.op`, `.oj`, and `.t` static files to `.o.png`, `o.jpeg`, and `.o.webp` respecfully.

**Comment by povrazor** [comment]
This could potentially be a javascript include, than server side does the check, and redirects to `/v1/has-webm.js` or `/v1/no-webm.js` depending on the value. The resulting pages is simple code that sets `window.hasWebM` to true or false.

Alternatively, a php script that can fetched with a JSONP request. `/v1/hasWebM/`

This value should be stored in localStorage, avoiding the need to check every refresh. It wont likely change, unless Mozilla or Microsoft suddenly add support. Just in case though, the value should expire automatically every week, maybe every day.

**Comment by povrazor** [comment]
This depends on image upload tranformer.

**Comment by povrazor** [comment]
Since we are generating pages client side, in one of the initial communications with the server, we can inform the user of their browser's ability to understand WebP (assuming it can't be done client side). Then like other embeds, we do an inline transform on any image coming from the static server.

**Comment by povrazor** [comment]
WebP serving will not be handled by a script. It will be generated if it doesn't exist. Client will detect support, and choose to request WebP versions of _non-animated_, _non-raw_ images.

**Comment by mikekasprzak** [comment]
This was finished a long time ago. Next step is make the client rewrite the content URLs to take advantage of this feature.
