### ISSUE TITLE
CORE: Pagination

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#548]
Apparently I didn't have a bug for this. Affects #493, #173, #174, #175, #176, and... well honestly it's most of the website. :wink: 

Here is some research on the 3 ways of handling pagination (pagination, load more, and infinite scroll):

https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/

It turns out **Load More** is the most desirable across both Desktop and Moblie. Infinite scroll does work well, but stops you from putting useful things in the page footer (more meaningful on mobile). I like it better too. ;)

* * *

Also I saw a nice interpretation of pagination on Twitch recently: Each page they load 60 items, 5 of those items are actually from the last fetch. The lists then need to be merged. Here is a brief comparison of algorithms.

* Append (no extra items, like classic pagination)
  * Algorithm
    * Master_List += New_List;
  * Pros
    * Simplest, and Fastest
  * Cons
    * Holes, if order changed
    * Duplicates, if order changed
* Crop and Appended (extra items from before needed)
  * Algorithm
    * Master_List = Master_List-5 items (removed from end)
    * Master_List += New_List;
  * Pros
    * Improved accuracy from Append
  * Cons
* Merge (no extra items needed, but you could use them)
  * Algorithm
    * For all new items, if item is on the Master_List, remove it from the Master_List.
    * Master_List += New_List;
  * Pros
    * Improved Accuracy
  * Cons
    * Scanning the Master_List in JS becomes the bottleneck. 
      * Primarily a problem if the Scan is done linearly top to bottom. If there's cleverness (like DB indexes), this should be a non-issue.
    * Early order changes not known (Not as important though)
    * Deleted items are not known (rarely an issue)

**Comment by zwrawr** [comment]
Basic pagination is now part of the site, and its behaviour is being extended by  #742
