### ISSUE TITLE
Rules: Port rules text to markdown

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#575]
I think @Jezzamonn is taking care of this, but for reference here's the original text of the request.

> So if somebody has some time, I have a small task that needs to be done.
> 
> I would like the rules page text converted to Markdown syntax.
>
> You'll want to do it in a local document, but you can use the Edit/Preview on your User Page to test how the formatting will work.
>
> You'll also need to download the images. If you have the VM setup, you can place them /www/public-static/other/rules/, and embed them as long as you use ///other/rules/blah.png as the URL.
>
> There's a chance that the max-post-size might be too small, so if you're trying to do your editing entirely locally (without keeping a copy) it, that it might end up cropped. Not sure though.
> 
> ...
> 
> Feel free to make any corrections. I may have gone a bit overboard with my bolding use on the original page.
> 
> Also embeds currently fill the full width, so you wont be able to do the right-align thing I did with the video.
>
> As for the soundcloud embeds, figure out the URL to them (the playlist and the track), and paste them on a standalone line.
>
> The site needs to be smart, and figure out embed code automagically.
>
> Soundcloud is currently unsupported, but hey.

**Comment by Jezzamonn** [comment]
Yep, feel free to add me as an assignee. Shouldn't be too hard, there are some decent html-to-markdown converters so it's really just converting the embeds and such.

**Comment by Jezzamonn** [comment]
Current progress: https://gist.github.com/Jezzamonn/4be04550318eefaed85e5e97c3ac126b

I just need to add in the youtube and soundcloud links. I also removed the coloured asterisks. If we want a similar feature maybe we can use different symbols for that? e.g. *, †, ‡, §, ‖, ¶. I also like the idea of just linking to those sections. Maybe both.

**Comment by povrazor** [comment]
Nice. The YouTube video link can be removed, as can the two ---'s right after it.

The only embeds that are actually important are the soundcloud ones. The playlist of samples, and the sample song.

**Comment by Jezzamonn** [comment]
Hm. I'm having trouble linking to a section because it seems all links are being eaten by the javascript engine. Each section has an id, but I can't link to it with the regular #id notation

**Comment by zwrawr** [comment]
Punctuation is removed, its all lowercase and spaces are replaced with `-`'s.
E.g. links to a section like `# What is this, and that?` get an id of `#what-is-this-and-that`.

**Comment by povrazor** [comment]
Ah yes, sorry! #'s in links aren't going to work, and it's my fault. I'm use the # urls for something else (dialogs). It didn't cross my mind that we'd actually need them. Oops.

**Comment by povrazor** [comment]
I've pasted the current version of this here:

https://ldjam.com/events/ludum-dare/rules

**Comment by Jezzamonn** [comment]
Awesome. I think it still reads pretty well without those links.

I was going to submit a PR with the images last night but my laptop is at a friend's place. But if you create a folder other/rules and download all the images from the old page there with the same names then they should all work

**Comment by povrazor** [comment]
Groovy. I can do that quickly.

**Comment by povrazor** [comment]
Okay, I'm actually going to call this issue done. I've since opened a new issue for updates and changes to the rules #609.
