### ISSUE TITLE
Theme Voting: There is no way to see prior LD's voting rounds

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#58]
This used to be a feature, but it doesn't exist on the new site

**Comment by zwrawr** [comment]
![screenshot from 2017-12-11 07-40-36](https://user-images.githubusercontent.com/18352787/33820292-9bb3e47c-de46-11e7-94b0-e440b7bf2333.png)
![screenshot from 2017-12-11 07-41-16](https://user-images.githubusercontent.com/18352787/33820314-b1a0f9d2-de46-11e7-9895-bfc2ac0fcd9f.png)

Has been implemented, can be closed.

**Comment by povrazor** [comment]
I still want to show theme suggestions and slaughter, but yes, different issue.
