### ISSUE TITLE
Editor: When editing, Embeds (YouTube) persist after toggling back

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#585]
This one is bizarre.

![iframer](https://cloud.githubusercontent.com/assets/1570313/25001010/7987dce4-2011-11e7-865e-67cd93bd187a.png)

When toggling back and forth between the markdown rendered view, the embeds (iframes) persist after.

I did a test, and what seems to happen is each iframe in a dangerouslysetinnerhtml block gets placed under a div. In the case above, the first div is the description. This can be worked around by adding a dummy div, but if you have 2 embeds then the next div gets it.

This could be a preact bug... I hope it is, hehe.

**Comment by povrazor** [comment]
Yeah, sounds like Preact 8 will fix this. Author thinks so. :smile:

> **mikekasprzak [8:21 AM]**
> Preact 7.2.1 (yeah I'm not running 8 yet). I'm running in to a bug with a `div` using `dangerouslysetinnerhtml`. The `div` ocassionally contains an `iframe` (or two). I ocassionally delete (omit) the dangerous div, and what I'm finding is the `iframe`'s are depositing themselves in to the elements that replace the dangerous div. It's just the `iframe`'s. (edited)
> 
> Does this sound like anything that *might* have been fixed since 7.2?
> 
> I don't have a test case for you yet, but I just wanted to see if that sounds like something.
>
> If it helps, the `iframe`'s are children of `div`'s inside the dangerous `div`.
>
> **developit [11:12 AM]**
> Yup, that would be fixed in 8.

(PS: The lead guy behind Preact is a cool dude)

**Comment by povrazor** [comment]
Is this fixed?

**Comment by zwrawr** [comment]
This is fixed.
