### ISSUE TITLE
Syntax Highlighting: Make New (Dark) Theme

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#587]
I'll be honest, I can't for the life of me remember why the source blocks use that gawd-awful yellow.

![coolbug](https://cloud.githubusercontent.com/assets/1570313/25003043/7f17b13e-201b-11e7-98d9-700db64be0c5.png)

Okay! So a lot of us are programmers here. While this isn't true for all programmers, a popular aesthetic of coders is the _dark theme_ in your source editor. i.e. something like this.

![darktheme](https://cloud.githubusercontent.com/assets/1570313/25003138/f17a28d8-201b-11e7-904f-d92b29706b73.png)

**NOTE:** Do not copy this exactly. This is a random image I googled for illustrative purposes.

The current theme can be found here.

`/src/custom/prism/prism.css`

I would like someone to create a new dark theme using our palette.

http://ludumdare.org/palette

i.e. `COL_A`, `COL_B`, `COL_C` are the primary colors. `COL_AB` and its ilk are inbetweens. `COL_N` is the neutral monochromatic, and the variants like `COL_NDD` and `COL_NLLLL` are steps Darker and Lighter about the neutral monochromatic. 5 steps from `COL_N` is the "white" and "black" used, also known as `COL_L` and `COL_D`. True white and black are `COL_W` and `COL_K`, but shouldn't typically be used.

If you create a `.less` file (instead of `.css`), you can use the color codes listed in the palette.

```css
@import 'defs.less';

.stuff {
  color: @COL_A;
}
```

The code blocks should look decent when placed in both posts and comments.

![monochrom](https://cloud.githubusercontent.com/assets/1570313/25003534/dad8a684-201d-11e7-8c67-f7eab3b76b89.png)

**Comment by zwrawr** [comment]
Made some progress on this, for some reason the `pre` and `code` styling is in about half a dozen different files. I hope they weren't important because I removed them from all but 2 files. :crossed_fingers: 
![](http://image.prntscr.com/image/6e2ddfddb44b42c0915636bd26e7bf5a.png)

**Comment by povrazor** [comment]
> I hope they weren't important because I removed them from all but 2 files

They shouldn't be. It's possibly a bunch of old stuff that's still lingering. As far as I know, `<pre>` tags are only used by the markup parser to hold code. `<code>` tags however are used for inline backticks, as I've been doing in this comment.

**Comment by zwrawr** [comment]
Nearly done. Not sure if the rounded corners work with the rest of theme, any thoughts?
![](http://image.prntscr.com/image/6c1336aa37d8487da6d6d16d51fc4ecf.png)
![](http://image.prntscr.com/image/805ec80f48bf48c0bbff3a3d47873de1.png)
![](http://image.prntscr.com/image/e6ada2b481f244dbaa821de54f1655c9.png)

**Comment by povrazor** [comment]
Yeah, I think backticks should probably stay light style. But code, because CODE can be dark.
