### ISSUE TITLE
<> in markup code blocks are removed

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#595]
## Issue
Any <> in markup code blocks are removed, as well as their contents. This is most likely becuase any html tags in the markup are removed. But code blocks and quotes should be interprited as text and so <> tags should be allowed.

### Example
E.g. writing this in the edit pane
![](http://image.prntscr.com/image/9be8470e6ef54fca858e29871e2eac55.png)

If you then go straight to preview you get this
![](http://image.prntscr.com/image/8391fb4e5f3341069e6acf9def16fa45.png)

Which looks good. But once you've saved your bio and then go back and veiw it you get
![](http://image.prntscr.com/image/de13e238ff0946059057c84b59358c2b.png)
![](http://image.prntscr.com/image/4fa2641c90724fe8b75db73bbeeba459.png)

**Comment by povrazor** [comment]
Ah shoot. I thought that was fixed a long time ago, but maybe I grabbed the wrong code when merging this feature in.

**Comment by povrazor** [comment]
okay try now. You should be able to save source code with tags.

**Comment by zwrawr** [comment]
Works properly now
![](http://image.prntscr.com/image/35aa34124df54aa7b4d4c369341feebe.png)
