### ISSUE TITLE
Core: Fix anchor link support

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#608]
#469 is a page that uses a lot of anchor links. The rules would like to use them too. Unfortunately the popups system captures and consumes all `#events`.

**Comment by Aurel300** [comment]
I see `src/public-ludumdare.com/main-ld.js` captures `hashchange` events. I see two ways to solve this:

 - In the `hashchange` handler, check if there is a dialog with the given id. If not, first check if there is an anchor, e.g. with `document.querySelector("[name=" + anchor + "]")`. If yes, scroll to it, if not, spawn the unfinished dialog.
 - When presenting a page to the user, parse it for anchors, and add them to the list. Then on `hashchange`, check dialogs and anchors.

**Comment by povrazor** [comment]
I'm going to have a special anchor prefix, something like `#a/`, and that will be reserved for page anchors. Relevant code will be rewritten to reference it.

**Comment by zwrawr** [comment]
Was fixed by #708
