### ISSUE TITLE
Unused requests: product.png, company.png, tagline.png, example.png

### ISSUE THREAD

**Issue by Aurel300** [ludumdare/ludumdare#614]
Looking at the Network tab in Inspector, I see a reload of the page requests these files:

![screen shot 2017-04-16 at 14 09 05](https://cloud.githubusercontent.com/assets/1102162/25071420/47a52eda-22ae-11e7-91d8-6be33e8fb19a.png)

All located in https://static.jam.vg/other/event/sample/sponsor/

Can we not request them when the even is not sponsored / the logos don't get displayed? I assume that is the intended usage for this.

**Comment by povrazor** [comment]
Yes that is the intent. I was making mockups and I needed them on the live site.

**Comment by povrazor** [comment]
Okay, I've committed a fix to my repo, but it wont be live until my next merge.

**Comment by povrazor** [comment]
Okay, this should be fixed.
