### ISSUE TITLE
Landing page for events

### ISSUE THREAD

**Issue by Aurel300** [ludumdare/ludumdare#616]
Navigating to:

https://ldjam.com/events/ludum-dare

I get a spinner and nothing happens.

I'd suggest either navigating to a page that actually loads something (e.g. just https://ldjam.com/), or creating a page that is relevant to the given event. I.e. shows posts in that event, games in that event, etc.

Another thought:

There is no list of "guides" anywhere, this could be a place for a list of links to various guides. Without knowing about it, there is no way to get to https://ldjam.com/events/ludum-dare/hosting-guide, or https://ldjam.com/events/ludum-dare/rules right now, AFAIK.

(The same thing happens with https://ldjam.com/events/)

**Comment by povrazor** [comment]
`/ludum-dare` is a group node. It's broken at the moment, but it will eventually be a list of events under it (kinda like how `/news`) shows the news.
