### ISSUE TITLE
Edit mode bug on posts where you have no permissions

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#623]
I was looking at the hosting [guide page]( https://ldjam.com/events/ludum-dare/hosting-guide) and noticed that there was an edit button. Which shouldn't be displayed because I'm not the author of that post.
![](http://image.prntscr.com/image/303447dbf00d4fabba6d908d53f92a08.png)

So i clicked it. Which brought up a 401 permission denied (as expected).
![](http://image.prntscr.com/image/feb0b6d211e74859a0135bca3210a8f6.png)

I then clicked the back button to go back and  ended up with.
![](http://image.prntscr.com/image/dc67bb16296b4881bd582c2715b8b265.png)

Which is showing the edit mode page. This dose not allow you to make changes to the post (no save button and if there was you'd probably get a 401).

**Comment by povrazor** [comment]
Yep. Confirmed this is a bug.

**Comment by povrazor** [comment]
Haha, okay I should probably fix this before we get more reports. :wink:

**Comment by zwrawr** [comment]
Can be closed, no edit button so no issue.
![](http://image.prntscr.com/image/062ddf3c064c47b7a688d438c9baa463.png)
