### ISSUE TITLE
Markdown: Embedded username links overriding markdown links

### ISSUE THREAD

**Issue by ntratcliff** [ludumdare/ludumdare#629]
If the text for a markdown link contains the @ symbol, that portion of the text will link to a user's page, not to the URL for the markdown link.

e.x.

```Markdown
[gamejolt.com/@20c109](http://gamejolt.com/@20c109)
```

becomes

```html
<a href="http://gamejolt.com/@20c109" target="_blank">gamejolt.com/</a><a href="/users/20c109">@20c109</a>

**Comment by zwrawr** [comment]
Yup defiantly an issue.
![](http://image.prntscr.com/image/c4f10ff11c9441a49ee3bc14b2e8657f.png)
![](http://image.prntscr.com/image/7b3d1d5fcc9841a8abe14322cd076051.png)

Probably have to change [this regex](https://github.com/ludumdare/ludumdare/blob/2934aa37408406820e123d01fb4ce76793b53334/src/custom/marked/marked.js#L466) to not detect @names in urls. Or add a check [here](https://github.com/ludumdare/ludumdare/blob/2934aa37408406820e123d01fb4ce76793b53334/src/custom/marked/marked.js#L702) to detect urls

**Comment by povrazor** [comment]
I think it can probably be fixed by moving the URL check before the @name check.

**Comment by povrazor** [comment]
Nope, I'm wrong about `<span>`. That might have been the syntax highlighter. The markdown parser cares nothing of `<span>`'s.

**Comment by ntratcliff** [comment]
Not sure how the lexer works, but could you just skip ahead in the string you're parsing by the length of the match when matching links? 

That way, you don't match any text inside the link.

**Comment by povrazor** [comment]
The lexer is a little old. It's based on a project called `marked`. The author unfortunately abandoned it, so my version has changes not in mainline. It looked like there was an effort to continue development, but I haven't checked in a while.

We may need our own parser anyway, 'cause I think I would like us to do things outside the "spec" (which is a vague thing anyway).

In general: 

* Most standard GitHub like formatting (text, tables, images, etc)
* Emoji Codes `:smile:`
* Custom Emoji Codes (things like `:key_spacebar:`, `:key_f2:`, `:mouse_left:`, i.e. emoji's for game controls)
* Some way to float images
* Any links by themselves on a new line are embeds, the rest are not.

**Comment by ntratcliff** [comment]
Perhaps check out [Parsedown](https://github.com/erusev/parsedown)? It's got good support for extending the parser, and decent docs. 

You'd have to move from js to php for markdown parsing, though.

**Comment by zwrawr** [comment]
Can't change to php, markdown is delt with client side.

If you do change to something that still active markdown-it might work. I changed from marked to [markdown-it](https://github.com/markdown-it/markdown-it/) because marked is dead. And i used [markdown-it-containers](https://github.com/markdown-it/markdown-it-container) to float images.

containers look like this can have classes the same way that codeblocks do
```
:::float-left
    ![](some image)
:::
```

could be made to produce
```
<div class="float-left">
    <img src=some image/>
</div>
```

**Comment by povrazor** [comment]
My main complaint about markdown-it is the file size: ~100k minified. As opposed to marked which is ~20k minified.

**Comment by ntratcliff** [comment]
> Can't change to php, markdown is delt with client side.

Arguably you could. You can create a php service that takes markdown text and returns the parsed html, and make an ajax call to that service from client side.

It's not too much more work, and would solve the size concern, but increases hits on the server.

**Comment by povrazor** [comment]
The server hit _is_ the issue. One of the key goals with the redesign is to take advantage of the wasted CPU power on the client side, so the server can focus on being fast and responsive.

**Comment by povrazor** [comment]
I'll just leave this here.

https://github.com/developit/snarkdown

**Comment by zwrawr** [comment]
So back to the topics of @name, if we change the regex to ^\s@([A-Za-z0-9-]+)(?!@) it should work. It just adds a need for a whitespace character before the @name. Which should fix the url and email issues.

**Comment by povrazor** [comment]
Could that be an issue for @names in brackets `i.e. (@names)`?

FWIW when I get comment replies finished, they're going to be inserting @names at the very beginning of the comment. This is how I'm working around the need for deep nesting of comments (they're supported, but it makes an unwieldy layout).

**Comment by zwrawr** [comment]
This is fixed now. If we don't link a partial url `github.com/@zwrawr` then the @name gets linked, which seems reasonable.

![image](https://cloud.githubusercontent.com/assets/18352787/25270616/2ef5c9e8-2679-11e7-8bd0-09915fe678dc.png)

**Comment by povrazor** [comment]
Yep. I'm fine with this.
