### ISSUE TITLE
[Comments] Peoples suggestions and issues from the comments

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#631]
## Suggestions
- [ ] 
    > (@chaseplays)
    Could you put the commenting box at the top? It’s a bit annoying to have to scroll in order to comment…
- [x] 
    >  (@dietzribi)
    @pov we need timestamps for comments!
- [ ] 
    >   (@sorceress)
    no comment delete button?
- [x]
    > (@boaheck-artgent)
    Would be nice if there was something that told you to sign in to comment if you are logged out. Thought it wasn’t working for a second there.
- [x]
    >  (@scornz)
    Eyyyy, looks cool :) The huge spacing between comments kind of bothers me though, keep up the goods work!

**Comment by povrazor** [comment]
Thanks for collecting these.

**Comment by povrazor** [comment]
Sign in is done.

**Comment by zwrawr** [comment]
Timestamps done!

 ![](http://image.prntscr.com/image/fafdc1ceeb9a4c71802bc956207441b4.png)

**Comment by povrazor** [comment]
Yep. Was just about to say. I had to fix a tiny bug where newly added comments had a "NAN" date first. :+1: 

Anyway, I think I'm done with this for now. Gotta move on to the next thing.

**Comment by rplnt** [comment]
The title of the timestamp in comments only contains the date, missing time.

Using something like this from `sandbox/internal/src/locale.js` might work, but I'm not exactly sure

`window.getLocaleTimestamp = function( date ) {
  return getLocaleDate(date) + " " + getLocaleTime(date) + " " + getLocaleTimeZone(date);
}
`

**Comment by povrazor** [comment]
Yep, that would be better than `getLocaleDate`.

**Comment by mkalam-alami** [comment]
Another suggestion, the current word wrapping rule (break-all) breaks the words without hyphens, which makes stuff less readable:

![wrapping](https://cloud.githubusercontent.com/assets/694508/25132179/db52bbfc-2448-11e7-8e6a-42e4c347ee64.PNG)

Nice job with adding the timestamps and "(edited)" markers.

**Comment by zwrawr** [comment]
I belive this behaviour was added as a temp fix for long lines in code
blocks, just to revert.

**Comment by zwrawr** [comment]
#633 and #634 were responsible i think.

On 18 Apr 2017 14:35, "ZWRAWR" <zwrawr@gmail.com> wrote:

I belive this behaviour was added as a temp fix for long lines in code
blocks, just to revert.

**Comment by povrazor** [comment]
Yeah. After some searching, I couldn't find a good answer on wrapping. To stop people from breaking the layout I did that, but as you noticed it's not ideal.

That said, now that the code overflow problem is fixed, we should test super-long-lines again to see if that helped at all.

Ideally I'd like to just use `hyphens: auto`, but I'm not entirely sure that's actually supported everywhere.

**Comment by mkalam-alami** [comment]
Yeah it looks like it's a bit early for [hyphens: auto](http://caniuse.com/#feat=css-hyphens)... (missing on Chrome + Win/Linux)

**Comment by povrazor** [comment]
@rplnt Oh ha, I didn't realize at the time that function didn't exist. I've since added it, and you should see better hover timestamps later today once I merge in my changes.

**Comment by zwrawr** [comment]
#688 does some work towards this.

**Comment by JortHub** [comment]
When the comment buttons overflow on a mobile phone the publish button goes a line down. It might look better when you resize the buttons, use less padding and/or remove the margin.

The buttons on an Galaxy S5:
![ld3](https://cloud.githubusercontent.com/assets/10116429/25314384/271ebea2-2843-11e7-91e5-0cfd26a6f65d.png)

**Comment by povrazor** [comment]
Yep. The buttons are missing a style. I wasn't able to easily _just remove the text_. If anyone has time to figure out what styles are needed to make those buttons not get glitchy when they are not beside text, let me know.

**Comment by JortHub** [comment]
Is this better?
![ld4](https://cloud.githubusercontent.com/assets/10116429/25326644/6057ccac-28d1-11e7-8015-bf6830bbe7bc.png)

**Comment by zwrawr** [comment]
Nice can you make a pr with that?

**Comment by JortHub** [comment]
Sure, I'll setup everything, but when that's done I'll pr

**Comment by povrazor** [comment]
Sure, I'll add it to mine. Thanks for the help.

**Comment by JortHub** [comment]
No problem

**Comment by povrazor** [comment]
Closing this. Only outstanding issue is #826.
