### ISSUE TITLE
Emoji Tag

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#645]
For page building, it would be nice to have access to an `<Emoji>` tag. This would effectively be the same thing as `<SVGIcon>`, but pull graphics from the emoji set (emoji-one) instead of SVG. 'cause right now, the only way to insert emoji is using a markdown parsed box.

**Comment by povrazor** [comment]
... I think somebody made this for me?

**Comment by local-minimum** [comment]
There's no emoji in https://github.com/ludumdare/ludumdare/tree/master/src/com but it sound easy to make a placeholder atm that simply renders an svgicon.
