### ISSUE TITLE
[UI] messed up buttons in small windows

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#652]
![](http://image.prntscr.com/image/e84112d6c75544f49fd1fd997e87743e.png)
![](https://lh3.googleusercontent.com/v9TDHnI1sO4WgbyKyzJdCkCnPqoeTuRFU3kwgGyQhdSNUTJ21cEx8XIdztmgkKAckn5pbEmq5foEX6cbmEi9fPAAM7UuUjsWthiIVzWTSG92j6WgjnIZuby9i6UQ3ZM_z2QE7rlKDCaj51PoLRxfX6AxlY_qZKn0KqghWe44Wa364l9et5qAranqGKdi23lTbmMAdMB7PV2F2s4SX8ONGmpJcsN_14xjvDory4VOApT3scUAnWK_fwUPbZtia2B6Ng-vZkJMNskxxrz9OpProUpw3KmUVnsLshapcMQ264PzU5UEtYVjRTzLN2h5JlkymQ7C3itNQKuV8SDXbIAHOby9aeO1aDMk_Xi26FZDli9_S5D8mUh-yIsntjGrdEx81YzdMc9v9647pwL2rAZPuV5LeZ-QHDtqdU8ZJ3ljRDuHhtAQHWnbAD8EULWL9CXP_qekmtM1LBJt8xDRL2iaH5kZtm5zNuYvt08weOvanOKSvEnYljmZ2DojK9zU0RGoPJI9vmtjSWcgu7aYh2EzkY6phhj9QbDB0AHhLLPcFYQpVdPg2lyO_2OrTQVoyKM1LlhTwkPhWYtUnho9xGYshVN8rjbtki2HsLVmgSrFr_xKKIieF9jA=w365-h648-no)

**Comment by povrazor** [comment]
Okay. I thought I saw that happening but I wasn't sure.

Should be an easy fix, just need to know what style can be applied to the buttons to make them no longer collapse when empty.

**Comment by ishanpm** [comment]
Setting their `height` seems to do the trick, 2em makes it look the same as on the wide layout.

**Comment by zwrawr** [comment]
Yup, looks like [this](https://github.com/ludumdare/ludumdare/blob/master/src/com/content-nav/nav.less#L12) line needs changing. Must of broken when pov made it inline-block.

**Comment by povrazor** [comment]
Yep. Anyway, it should be fixed now. Also in the updated Event page layout, the buttons should fit now.

**Comment by zwrawr** [comment]
Works for me ![](https://lh3.googleusercontent.com/olllQNQ0MxWCIUnPxRXpT7QlwJ887sy4g_wgWkKQLc8YyRAzHGTVnRon7vu0niuv3s957iy2oQWqS7ngefBSgsakVGujCu3qpdqp7f0P5uJN4cdHs0BagMwYayAV71SOMFldZTybA0daZ3Ji8pokU-ge7JzpZtz-83G1PCp0o79ehjMQ0Pt6JVpQnUqWtQU-6Av0OX2UKufBDV_ld4x5ivDXzQXhdOB_CJW-ob66ItmSDHGnQfgeEV3P2Adxg8NSQJ-QuAKxTUPmPHATr-b9yvfSDgUI1Dc9nXvafdtv2ZR8voeptgQNubgPmUCBqTrDehC31EttqxikihO_6c-z01EvbfFZ-yfffSX2MHPZHMBtFZxaHETGe2cqE9jmrq_ZkAsNsKGhQLFN87nnHtC7YIql4TCGA85f4grBe80OFPfpjz7coy4HhNTEOiNzxDifXZ74LLsg0VgtueIcFAGuO0BdoLovRv0zAt9u9a109vwIADBunvXocuFtDpbCZn935ysqYX99jrbhNfN_ZxhehwCclsXU7LFFs0bwnVj1efVQ7HAAz28gIW6DtSsZZ-L8AFfIoaoh6PfLILg7fY_tMvZUAniVj7XVX3iMhUiLVto8u6BF8lDI=w372-h660-no)

**Comment by povrazor** [comment]
Great. One more bites the dust.
