### ISSUE TITLE
The page's editor appears after clicking "back" on the browser despite initial "Permission Denied" messages

### ISSUE THREAD

**Issue by japtar10101** [ludumdare/ludumdare#655]
I've noticed that the page editor, such as [rules](https://ldjam.com/events/ludum-dare/rules) and [hosting](https://ldjam.com/events/ludum-dare/hosting-guide) page appears by simply click back on the Google Chrome browser.  Fortunately, I can't actually make changes to the page, but it's a bit disconcerting.  Here's the step-by-step process of bringing up the editor:

1.  Login as a normal user.  In this case, I logged in as [Omiya Games](https://ldjam.com/users/omiya-games/).
1.  Open the rules page. ![chrome 2017-04-18 130](https://cloud.githubusercontent.com/assets/71934/25146379/a99128ee-2441-11e7-8583-e487777be7cb.png)
2. Click on the edit button at the bottom of the rules page.  ![chrome 2017-04-18 131](https://cloud.githubusercontent.com/assets/71934/25146381/a9933378-2441-11e7-9e9e-a3c0709a5631.png)
3. After getting the permission denied page, click on the back button on Chrome.  ![chrome 2017-04-18 132](https://cloud.githubusercontent.com/assets/71934/25146382/a9944f92-2441-11e7-9692-bd2ce961343c.png)
4. Observe the page editor appearing.  ![chrome 2017-04-18 133](https://cloud.githubusercontent.com/assets/71934/25146380/a99250f2-2441-11e7-98ea-5b3f8ac12f41.png)

**Comment by zwrawr** [comment]
Dupe of #623

**Comment by japtar10101** [comment]
Fair enough.  My search-fu is lacking.
