### ISSUE TITLE
Wrapped text doesn't break on word boundaries

### ISSUE THREAD

**Issue by endlessplumber** [ludumdare/ludumdare#659]
Throughout the site (particularly in comments), I'll run into places where the text wraps but doesn't break on standard hyphenated syllable- or word-boundaries. See attached image for an example.

I'm running Firefox 52.0.2 (32-bit). I haven't tested other browsers to see how they render.

![text_wrap_problems](https://cloud.githubusercontent.com/assets/27740925/25150060/431edc28-2446-11e7-8254-8a83f33cdc43.png)

**Comment by zwrawr** [comment]
Checkout #631 there's some discussion about it.

**Comment by povrazor** [comment]
Try it now.

**Comment by endlessplumber** [comment]
Looks great on my end! No awkward letter breaks, and standard hyphenated breaks on long words.

![text_wrap_fixed](https://cloud.githubusercontent.com/assets/27740925/25154054/8e1b3dbc-2454-11e7-8a27-fbed5d503652.png)
