### ISSUE TITLE
Weird '/' on the main page

### ISSUE THREAD

**Issue by Jezzamonn** [ludumdare/ludumdare#672]
Not really sure what it's meant to say, but it looks like you missed one of the link's text.

![image](https://cloud.githubusercontent.com/assets/10319630/25186133/19047f68-24d4-11e7-8479-5a0e58a34bbb.png)

It's part of the sentence "To check when the event is ending look at the countdown clock in the sidebar of / site. The Compo finishes 48 hours after the theme was announced and the Jam ends 72 hours after the theme was announced."

**Comment by Jezzamonn** [comment]
Ok, looks like the page has since been updated. Maybe I was looking at it mid edit.

**Comment by povrazor** [comment]
I think you were thinking of this page:

https://ldjam.com/events/ludum-dare/hosting-guide
