### ISSUE TITLE
Autoembedder is breaking api.ldjam.com URLs

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#676]
This useful URL:

https://api.ldjam.com/vx/user/logout

is getting mangled by the autoembedder. the `api` part is getting binned.

**Comment by zwrawr** [comment]
Should be fixed by #694 or #693 i don't rember which one . .

**Comment by zwrawr** [comment]
![image](https://cloud.githubusercontent.com/assets/18352787/25269420/77621a74-2674-11e7-81b4-9d02f128beb6.png)
