### ISSUE TITLE
Laggy typing in the comments box on Android

### ISSUE THREAD

**Issue by ajayyy** [ludumdare/ludumdare#685]
For some reasons when I type in the comments box in chrome on Android, the keyboard lags a ton. I have to type it out slowly or else some characters are missed. This doesn't happen in chrome on windows.

I have a Samsung Galaxy note 4. This could be an issue only on my end though, I'm not sure. I've restarted the phone and the same thing happens.

**Comment by povrazor** [comment]
We did recently introduce a fix for Microsoft Edge that could have made things worse on Mobile Chrome. I haven't tried writing anything on my phone in a while, but I'll have a look, see if I can reproduce.

**Comment by Noojuno** [comment]
I can add a platform check if need be to make the fix only apply to edge

**Comment by povrazor** [comment]
Confirmed to be laggy on my Nexus 6P running Chrome for Android.

**Comment by povrazor** [comment]
It's worth a try if you have a spare moment.

**Comment by Noojuno** [comment]
Should be fixed in #686

**Comment by povrazor** [comment]
Merged and deployed. This appears to fix the problem for me. I just want to double check Edge to make sure it's still in effect, then I'll be satisfied.

**Comment by povrazor** [comment]
Fantastic. Best I can tell this issue is now fixed everywhere.

Thanks for the fix @Noojuno! :smile:
