### ISSUE TITLE
Students! When are your exams?

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#687]
Hey folks!

I'm looking to do a bit of research. It's no secret that Ludum Dare events tend to be awfully close to exam time. Scheduling for an international audience is quite difficult. I've done a pretty good job of avoiding industry events, but as the stars aligned over the years, we ended up on a 4 month schedule of events that almost perfectly aligns with exam time.

But rather than running away from the problem, I want to understand it a bit better. I can't promise I'll be able to fix it for you, but I might be able to make things more convenient for future students.

So let me know.

* When are your exams
* Name of Institution
* Country
* A little about the program (i.e. Computer Science, 2 year degree, anything else of interest)

**Comment by shubshub** [comment]
My degree doesn't have exams

**Comment by povrazor** [comment]
Then lets say Ludum Dare is your exam. :wink:

**Comment by shubshub** [comment]
I suppose that's fair since my degree is in software engineering (Specifically game development)

**Comment by DavidColson** [comment]
This year exams start 24th of April and run to 8th of May.  Almost always summer exams start the final week of April and run for 22.5 weeks. Christmas exams are almost always the first full week of December and last 2 weeks. Last year they started on the 5th of December.

Also, I study theoretical physics in the National University of Ireland, Galway

**Comment by povrazor** [comment]
> summer exams start the final week of April and run for 22.5 weeks

Whoa. Isn't a semester only 18 weeks? :wink:

**Comment by NoNiMad** [comment]
Two semesters therefore two sessions of exams for me : the end of December/beginning of January and end of May/beginning of June. During the last 3 years I don't remember having a problem with exams colliding with LD, but maybe a bit earlier would be nice for the April one, as it is the one that have the biggest probability to end up during or just before exams.

I study Computer Science and Networks in Esisar, an Engineering School in Valence, France.

**Comment by Zyrconium** [comment]
3rd Year BSc Computer Science from the University of the West of Scotland. My only exam for this semester is today, so less LD prep time, but LD ends up framed as some nice relaxation time.

**Comment by DNAbro** [comment]
Exams officially start on Monday for my university. So this weekend will be studying.
University of Florida
U.S
Computer Science degree

**Comment by 5Mixer** [comment]
I'm in year 10 so my exams are not as serious as those in universities haha. My school is in Melbourne, Australia. First week of exams start on Friday the 9th of June and run for a week. Second week starts on Thursday  9th November and run for a week. :+1:

**Comment by TeamQuiggan** [comment]
I've taught at 2 Game Development Programs in Ontario and I can not convince students to do LD, as this is the weekend immediately after finals, so students are either moving and/or burned out. Also I can't do it because I have to mark papers.

**Comment by boaheck** [comment]
This time round it's fine I have a project deadline like 12 hours before the jam starts but I'm free for the weekend and my exams are all mid may. However I do usually have trouble with the December one because of project deadlines which is a pity.

**Comment by J-eno** [comment]
My Spring semester exams start around May 21st. I'm at the University of Maryland Baltimore County USA. I'm pursuing a BSc in Computer Science with a gamedev focus. I can never really find time to do anything during the semesters so I only do summer/winter break jams. Haven't been part of an LDJam since highschool sadly.

**Comment by ajayyy** [comment]
Jst make sure not to move LD back to mid February please, because my high-school exams are then, and in June. I probably would be able to do skip studying, but I don't know if I should...

**Comment by povrazor** [comment]
FWIW Ludum Dare is set on April, August and December. But we need to play nice with industry events. Usually that leads me to choosing between 2 weekends. Historically my choice is "whichever one is later", so what I'm trying to gauge here is if choosing that earlier date would help more students find time, or it just doesn't matter and every weekend has something wrong with it for someone.

**Comment by fodinabor** [comment]
University Augsburg, Germany
My winter exams usually are in mid-february or those repeating are in the last march or first april weeks.
My summer exams are last july week or first aug weeks... repeating once are in the first october weeks.
Summer lectures start next week ;-) (usually second april week..)
Winter start mid october.

I'm doing a Informatik & Multimedia B.Sc., i.e. Computer Science... it usually takes 6 semesters.

**Comment by HjalteTagmose** [comment]
Exams from 21/5 till 21/5
Game College, Denmark
Equivelant of highschool with a focus on game development (3yrs)

**Comment by Aurel300** [comment]
Exams starting first week of May. First year Computer Science at Imperial College, UK.

So there's about a week between LD and the first exams (although the exams last for three weeks, so time to study :D), not that bad.

**Comment by ThomasGiro** [comment]
Exam from 24/04 to 28/04 so I can't fully participate 😞 
University of Lorraine, France
Third Year in Computer Science

**Comment by dmitrix** [comment]
The April and August events usually don't interfere with school but the one in December is always the weekend before exam week.

**Comment by J-Vernay** [comment]
J'ai ! I'm from France !
My exams end the 16 of June.
I'm from Télécom st-Étienne, first year ^^ (School of programming).
I home I'll finally take part to Ludum Dare ^^

**Comment by torcado194** [comment]
exams for me are from April 24 to April 28 (but screw it i'm still participating)
Weber State University. Utah, USA
Computer science degree

**Comment by ntratcliff** [comment]
Our exams week is May 15th-19th this semester, I believe the December LD was the weekend before finals week for the winter semester, which was a bit unfortunate.

**Comment by lightblub** [comment]
I have high school exams next week.

>  But we need to play nice with industry events. Usually that leads me to choosing between 2 weekends. Historically my choice is "whichever one is later", so what I'm trying to gauge here is if choosing that earlier date would help more students find time

At least in this case, the earlier weekend would've been better for me, at least. Nevermind, I'm going to try and put some time in this weekend anyway for the compo.

**Comment by YWainczak** [comment]
My finals start on the 24th (Oh geez, that's next week... :/) Last Ludum Dare was smack in the middle of finals...

I go to Becker College in the good ol' USA for interactive media & game design.

**Comment by povrazor** [comment]
Do some schools have 6 month long semesters? I may have mistakenly assumed semesters were always 4 months.

**Comment by zwrawr** [comment]
So my uni has 3 10 week terms a year (not totaly true but close enough) and most uk uni are similar

**Comment by whatFruit** [comment]
When are your exams: Fall Semester (December 11-14)  ; Spring Semester (May 7 - 10)
Name of Institution: Reed College
Country: USA
A little about the program: 4 year BS, Majoring in biochemistry with a minor focus in CS.

**Comment by BNeutral** [comment]
When are your exams: 
Midterms: April 10 to May 8, September 18 to October 16. Although if you fail at those you need to try again 2 weeks later, and if you fail at that again 2 weeks later.
Finals: Jun 26 to Aug 7, Dicemeber 1 to 24, February 1 to 28
The semesters are generally 4 months of class followed by a month or two of finals where you can choose among many dates. The only month without any activity is January.
Name of Institution: Universidad de Buenos Aires (UBA)
Country: Argentina
A little about the program: 6 year engineering degree (which is actually very hard to finish in just 6 years)

**Comment by crocojim18** [comment]
I'm not exactly sure how the start of the year/exams are calculated, but without fail, every single year, Ludum Dare has happened right as the school year starts in August, and directly before finals week in April and December. This has happened so far for 3 years. Sufficed to say, I haven't participated since high school. _(I hope to change that this LD despite finals, though!)_
I go to the University of Pittsburgh in PA, US.
I'm doing a BA in Linguistics as a four-year program. One year left!

**Comment by b3015389** [comment]
My dissertation is due on Monday, luckily I should finish it this afternoon!
Exams across all computing courses at my uni are in December/January and May.
The course is Game Software Development at Sheffield Hallam University, UK.

**Comment by HiddeVanDerKooij** [comment]
This LD is great, exactly in the middle of a couple of days off. NHTV, The Netherlands, game Dev. Critical days were past Monday and Tuesday.

**Comment by keeferrourke** [comment]
> When are your exams

Winter semester (now) : normally the end of April; W17 was/is April 10-22
Summer semester (soon) : normally the middle of August; S17 exam period will be Aug 10-18
Fall semester (later) : normally the first few weeks of Dec; F17 exam period will be Dec 4-15

> Name of Institution

University of Guelph

> Country

Canada

> A little about the program (i.e. Computer Science, 2 year degree, anything else of interest)

5-year Honours Bachelor of Computer Science, with CO-OP (without CO-OP this degree would be 4 years). I am also pursuing a minor in Mathematics.

**Comment by Bob-The-Seagull-King** [comment]
Well I don't yet have exams (yay) but school holidays are from early to late July and from the end of September to about the end of October. I was really only able to participate because the Jam and holidays aligned this time.

**Comment by mkalam-alami** [comment]
In France the exam-heavy months are:

* June in particular, with sometimes exams starting in may
* January/February for semester-based studies

The current April/late August/early December pattern fits our country pretty well actually.

**Comment by CosineP** [comment]
AP exams (high school, extremely common) are in May, usually the first two weeks.
