### ISSUE TITLE
Use prepared statements / parameterized queries?

### ISSUE THREAD

**Issue by 31** [ludumdare/ludumdare#7]
I saw [SQL statements by string concatenation](https://github.com/povrazor/ludumdare/blob/master/core/star.php#L33-L37) and felt a little odd. Should someone work on using a safer approach? I don't know PHP too well, but it seems to me especially if you start getting pull requests that a practice like this could lead to a security vulnerability pretty easily.

**Comment by povrazor** [comment]
Yeah, at the moment, sanitization is handled outside of this code (there's a note about this in node.php, but not in love.php or star.php). But certainly, for performance they should be switched.

**Comment by povrazor** [comment]
All live code is parametrized queries, but old code (WIP site) hasn't been converted yet.

**Comment by povrazor** [comment]
DB library from Delorean was merged in, and Theme Voting code updated. Any code referencing the old un-prepared functions should now be broken, making them harmless. Closing this issue.
