### ISSUE TITLE
Go to LDJAM HTML code

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#700]
I need a big block of code to drop on the old website, LudumDare.com

It needs to be raw HTML, inlined CSS, and JavaScript in a script tag. The point is it needs to be easy for me to just paste in.

Fill the page with semitransparent black, and put an image in the middle (the one in the top post that says Ludum Dare 38 on LDJAM.com). Just hotlink it. Clicking on the image goes to https://ldjam.com (HTTPS!). Clicking outside (on the black) hides everything instead. 

Too many users appear to not realize we're over on LDJAM, despite the post. This is to make sure. 

Unfortunately this is going to pop up every time you click a link, so here's where it gets fancy. 

Add something floating in the top right corner. The words "dismiss" or "keep closed" or something like that. Store a variable in sessionStorage that you check before popping this stuff up (something that won't likely conflict). Of course, set it when you click that dismiss text. 

The reason I say sessionStorage and not localStorage is that it needs a timeout (in case folks click off and miss it). Also there's a good chance I will forget to disable this, so some persistent way to disable it will help frustrate users of the old site less. 

If you're feeling really fancy, commit a change to the ludumdare-2008 repo, your changes in wp-content/theme/header.php (I think). That will let me check it out easily, directly on the server (and checkout disabling it, if someone wants to do that after LD). 

Be sure to let me know here if you do this. I don't monitor the ludumdare-2008 repo.

**Comment by zwrawr** [comment]
This is cover now
![image](https://cloud.githubusercontent.com/assets/18352787/25291186/f29bf544-26c8-11e7-93f0-5e92463974bf.png)
