### ISSUE TITLE
Calender: Current day style needs to be higher priority than event style

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#710]
![wherecalr](https://cloud.githubusercontent.com/assets/1570313/25279408/599fd670-2674-11e7-8087-1ebc5f0548f3.png)

Friday should be white. with a trophy on top.

**Comment by zwrawr** [comment]
This was fixed by #719 
![image](https://cloud.githubusercontent.com/assets/18352787/25315800/03a6cdf6-2853-11e7-91a6-023084ce5efe.png)
