### ISSUE TITLE
Nav button colours

### ISSUE THREAD

**Issue by Inari-Whitebear** [ludumdare/ludumdare#726]
Personally I find the nav buttons (News/Games) somewhat hard to read when not hovered, due to the colours being quite similar to each other.

**Comment by povrazor** [comment]
![navco](https://user-images.githubusercontent.com/1570313/27363014-e34101be-55ff-11e7-8e99-d7f0637d3b6e.png)

**Comment by zwrawr** [comment]
The colors were changed
![screenshot from 2017-12-11 07-34-07](https://user-images.githubusercontent.com/18352787/33820133-bbe52608-de45-11e7-8da8-5980e6e7d3e8.png)
