### ISSUE TITLE
Cannot see users I am following

### ISSUE THREAD

**Issue by gonutz** [ludumdare/ludumdare#747]
I do the following:
- click on the user icon in the top-right
- click on the 'Following' button
Below the user description the spinning circle appears, indicating that the list is loading, but it keeps spinning for ever.

**Comment by zwrawr** [comment]
Can you tell us what browser and os your using. and can you see if there are any errors in the javascript console. (In chrome press `Fn12` (or right click and choose `inspect`) and click on the `console` tab.

**Comment by dickclaus** [comment]
Hey, I'm using latest Firefox on MacOS. Have the same problem. Here is log from console.

```
GET 
XHR 
https://api.ldjam.com/vx/node/walk/1/users/dick-claus/following [HTTP/2.0 200 OK 151ms]
GET 
XHR 
https://api.ldjam.com/vx/node/get/12583 [HTTP/2.0 200 OK 142ms]
[fetchNode] Done: 12583  all.min.js:8:28064
GET 
XHR 
https://api.ldjam.com/vx/node/get/11+10536+4287+5667+2584 [HTTP/2.0 200 OK 214ms]
 Potentially unhandled rejection [1] ContentUserFollowing</t.prototype.render/n<@https://ldjam.com/-/all.min.js?v=2470-668569c:7:25936
ContentUserFollowing</t.prototype.render@https://ldjam.com/-/all.min.js?v=2470-668569c:7:25896
renderComponent@https://ldjam.com/-/all.min.js?v=2470-668569c:1:7713
rerender@https://ldjam.com/-/all.min.js?v=2470-668569c:1:1392
F@https://ldjam.com/-/all.min.js?v=2470-668569c:4:24558
L@https://ldjam.com/-/all.min.js?v=2470-668569c:4:24192
[7]</</</</x.prototype.when@https://ldjam.com/-/all.min.js?v=2470-668569c:4:27863
[7]</</</</I.prototype.run@https://ldjam.com/-/all.min.js?v=2470-668569c:4:28952
[3]</</</e.prototype._drain@https://ldjam.com/-/all.min.js?v=2470-668569c:4:18805
e/this.drain@https://ldjam.com/-/all.min.js?v=2470-668569c:4:18472
t@https://ldjam.com/-/all.min.js?v=2470-668569c:4:20395
```

**Comment by gonutz** [comment]
I am using Firefox 53 on Windows 8.1.
Can you tell me how to get that log in Firefox?

**Comment by zwrawr** [comment]
If your right click there should be some option that sounds like dev tools or inspect or something

**Comment by gonutz** [comment]
I just tried it in Chrome and the log says

> all.min.js?v=2470-668569c:4 Potentially unhandled rejection [1] TypeError: Cannot read property 'indexOf' of undefined
    at https://ldjam.com/-/all.min.js?v=2470-668569c:7:25962
    at Array.sort (native)
    at t.render (https://ldjam.com/-/all.min.js?v=2470-668569c:7:25913)
    at renderComponent (https://ldjam.com/-/all.min.js?v=2470-668569c:1:7715)
    at rerender (https://ldjam.com/-/all.min.js?v=2470-668569c:1:1392)
    at F (https://ldjam.com/-/all.min.js?v=2470-668569c:4:24560)
    at L (https://ldjam.com/-/all.min.js?v=2470-668569c:4:24192)
    at x.when (https://ldjam.com/-/all.min.js?v=2470-668569c:4:27863)
    at I.run (https://ldjam.com/-/all.min.js?v=2470-668569c:4:28972)
    at e._drain (https://ldjam.com/-/all.min.js?v=2470-668569c:4:18820)

and then the same error once more.

**Comment by zwrawr** [comment]
If you look in the console you should see a line like this `[fetchUser] caller_id: 29` but it wont be 29 it will be your id. If you then put that id in `https://api.ldjam.com/vx/node/get/29?pretty` (replace 29 with your id) you should get a page of text. If you paste that here it'd help

**Comment by zwrawr** [comment]
But it looks like were missing a check that makes sure you have followers to show.

**Comment by gonutz** [comment]
> {
    "status": 200,
    "caller_id": 4280,
    "node": [
        {
            "id": 4280,
            "parent": 2,
            "superparent": 1,
            "author": 4280,
            "type": "user",
            "subtype": "",
            "subsubtype": "",
            "published": "2016-12-05T11:08:57Z",
            "created": "2016-12-05T11:08:57Z",
            "modified": "2017-04-11T07:49:13Z",
            "version": 10972,
            "slug": "gonutz",
            "name": "gonutz",
            "body": "Go programmer, see my [Github account](https://github.com/gonutz/)",
            "path": "/users/gonutz",
            "parents": [
                1,
                2
            ],
            "games": 1,
            "articles": 0,
            "posts": 2,
            "meta": [],
            "link": [],
            "love": 0
        }
    ]
}

**Comment by dickclaus** [comment]
{
    "status": 200,
    "caller_id": 12583,
    "node": [
        {
            "id": 12583,
            "parent": 2,
            "superparent": 1,
            "author": 12583,
            "type": "user",
            "subtype": "",
            "subsubtype": "",
            "published": "2017-04-18T11:13:37Z",
            "created": "2017-04-18T11:13:37Z",
            "modified": "2017-04-22T21:38:30Z",
            "version": 31635,
            "slug": "dick-claus",
            "name": "dick-claus",
            "body": "Hi, I'm Dmitry.\n\nI started doing Ludum Dare back in the **Apr 2012**.\nSince then my life changed. I started to dream about making games. And my dreams came true.\nRight now I'm working in game industry. Doing web games for all platforms.\n\nSince then I had participated in many LD events, some were successful, some not.\n\nBut I really like doing LD because it is LOTS OF FUN!\n\nhttps://twitter.com/dickclaus\n\nhttps://www.youtube.com/channel/UCgv2YKySjmybi5BPPt6dQUA\n\n\n",
            "path": "/users/dick-claus",
            "parents": [
                1,
                2
            ],
            "games": 1,
            "articles": 0,
            "posts": 3,
            "meta": [],
            "link": [],
            "love": 0
        }
    ]
}

**Comment by zwrawr** [comment]
So neither of you are following other people, thats why it's messed.
We need to add a check for that.
In the meantime if you follow someone e.g. [pov](https://ldjam.com/users/pov) then the page should work fine.

**Comment by gonutz** [comment]
Well I actually clicked on two people's 'Follow' buttons. Is there anything else I would need to do?

**Comment by zwrawr** [comment]
If you head back to their profile do the buttons say following and are blue?

**Comment by gonutz** [comment]
Just did another test, clicked on a user's Follow button, it says Following and if I refresh the page it stays blue but nothing shows up in my profile's Following page, still the same problem as above.

**Comment by dickclaus** [comment]
I've followed pov first. And I see him in following first. But after I followed some people it stopped working. 
Just tried to unfollow pov. And follow him again. Same result.

**Comment by zwrawr** [comment]
So with a brand new account i get
![image](https://cloud.githubusercontent.com/assets/18352787/25313376/18ad9cda-2825-11e7-9cda-e5c8115998ee.png)

Then after following pov 
![image](https://cloud.githubusercontent.com/assets/18352787/25313384/44387730-2825-11e7-9c2a-bb508d20d0e1.png)

And then after following my main account
![image](https://cloud.githubusercontent.com/assets/18352787/25313401/9426375a-2825-11e7-9c53-7989f6965e77.png)

```
Potentially unhandled rejection [1] ContentUserFollowing</t.prototype.render/n<@https://ldjam.com/-/all.min.js?v=2470-668569c:7:25936
ContentUserFollowing</t.prototype.render@https://ldjam.com/-/all.min.js?v=2470-668569c:7:25896
renderComponent@https://ldjam.com/-/all.min.js?v=2470-668569c:1:7713
rerender@https://ldjam.com/-/all.min.js?v=2470-668569c:1:1392
F@https://ldjam.com/-/all.min.js?v=2470-668569c:4:24558
L@https://ldjam.com/-/all.min.js?v=2470-668569c:4:24192
[7]</</</</x.prototype.when@https://ldjam.com/-/all.min.js?v=2470-668569c:4:27863
[7]</</</</I.prototype.run@https://ldjam.com/-/all.min.js?v=2470-668569c:4:28952
[3]</</</e.prototype._drain@https://ldjam.com/-/all.min.js?v=2470-668569c:4:18805
e/this.drain@https://ldjam.com/-/all.min.js?v=2470-668569c:4:18472
t@https://ldjam.com/-/all.min.js?v=2470-668569c:4:20395
```
So it's asking the sever for who your following but not displaying them. Will take a look at this issue soon

**Comment by zwrawr** [comment]
A potential fix for this has been merged, once that goes lives you can check to see if everythings working 😄

**Comment by dickclaus** [comment]
It works for me thanks.

**Comment by gonutz** [comment]
Works for me as well, thank you very much!
