### ISSUE TITLE
Add hosting and submitting guide links on game publish page

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#751]
![image](https://cloud.githubusercontent.com/assets/18352787/25314044/dfda4ef8-2833-11e7-9196-36a0f129cf0f.png)
Add links to #722 and https://ldjam.com/events/ludum-dare/hosting-guide to that page

**Comment by povrazor** [comment]
Not actually to the page above, but edit. I can't remember if this is done already though.

**Comment by zwrawr** [comment]
If i remember correctly there is a link.
