### ISSUE TITLE
Auto embedded URLs with Query Strings don't work (Google Drive)

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#766]
> <Codex_> PoV: btw, urls like this http://meshpage.org/mesh.php?id=GVILK@57 doesnt work in the site, needed to use url shortener to get it linked to the game.

**Comment by povrazor** [comment]
Looks like it's query strings. oops. :smile:

**Comment by povrazor** [comment]
I think this is fixed. Needs double checking.

**Comment by zwrawr** [comment]
Doublechecked. Works fine.

**Comment by zwrawr** [comment]
Still works after the url parsing rewrite. Can be closed.

**Comment by povrazor** [comment]
Okay. We need need to fix `#/` and other `#`'s in URLs (especially those that are off site), but yeah, these still work.
