### ISSUE TITLE
Move user page nav buttons in to user body, like event pages

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#780]
Event Pages

![eventpager](https://cloud.githubusercontent.com/assets/1570313/25348623/ce71047c-28ec-11e7-9b89-f87d78ec6649.png)

User Pages

![userpagy](https://cloud.githubusercontent.com/assets/1570313/25348628/d3b64000-28ec-11e7-8802-ad5b436aa78a.png)

Or at least, move the idea of followers up to the same place the follow button goes, and add a `/home`. For all pages but home, minimize the bio.

Also add the minimize box.

**Comment by zwrawr** [comment]
User pages were redesigned, They now have a nav bar at the top like the main feed.
![screenshot from 2017-12-11 07-27-12](https://user-images.githubusercontent.com/18352787/33819933-d922ff52-de44-11e7-9895-2aa76e546320.png)

This can probably be closed.
