### ISSUE TITLE
[CSS] More button cut off

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#782]
This seems to only effect the games pages

## Home page
![image](https://cloud.githubusercontent.com/assets/18352787/25354577/4e83e6c8-292b-11e7-92f3-eafb6e16979d.png)

## Games page

![](http://image.prntscr.com/image/3c20b3d227b048d79a484110860e6802.png)

**Comment by povrazor** [comment]
Yeah, I made some tweaks in the more button and com/content-timeline. Haven't had a chance to look at games timeline yet.

**Comment by zwrawr** [comment]
This isn't fixed on ldjam.com but i cannot replicate it locally, so good luck to who ever tries to fix it next.

**Comment by zwrawr** [comment]
This seems to be fixed.
