### ISSUE TITLE
Can't publish (nor edit) game created on first day

### ISSUE THREAD

**Issue by f4nu** [ludumdare/ludumdare#784]
I've created a game ([#24460](https://ldjam.com/events/ludum-dare/38/$24460)) as soon as I had the occasion after the website feature release, gave it a name, but now it's uneditable. The game had the title changed to "Title", can't publish nor have the pencil icon to modify.

Can comment.

![capture](https://cloud.githubusercontent.com/assets/8605605/25357610/b8861006-293e-11e7-9691-210c5cb2d1c4.JPG)

**Comment by zwrawr** [comment]
I was just about to create an issue for this. Can you see if there were any issues in the javascript console (In chrome this can be found by pressing `Fn12` and going to the `console` tab)

**Comment by zwrawr** [comment]
Okay after messing with the api a bit I know whats wrong.
The author of your game is @jabba and so there the only one that can publish and edit it.

By the sounds of it you created it and so should be the author, so there seems to be a bug thats changed the author.

@jabba should be able to edit your post in the mean time

**Comment by f4nu** [comment]
No issues at all. Maybe it's because it's loading 2 games? (21922)
`all.min.js?v=2551-f3990ce:9 [constructor]`
`all.min.js?v=2551-f3990ce:9 [fetchData]`
`all.min.js?v=2551-f3990ce:9 [fetchUser]`
`all.min.js?v=2551-f3990ce:9 [fetchRoot]`
`all.min.js?v=2551-f3990ce:9 [fetchUser] caller_id: 12615`
`all.min.js?v=2551-f3990ce:9 [fetchFeatured]`
`all.min.js?v=2551-f3990ce:9 [fetchRoot] Done: 1`
`all.min.js?v=2551-f3990ce:9 [fetchUser] Done: 12615`
`all.min.js?v=2551-f3990ce:9 [fetchNode]`
`all.min.js?v=2551-f3990ce:9 [fetchFeatured] Loaded:  9405`
`all.min.js?v=2551-f3990ce:9 [fetchFeatured] My Game: [21922, 24460]`
`all.min.js?v=2551-f3990ce:9 [fetchFeatured] Done: 9405`
`all.min.js?v=2551-f3990ce:9 [fetchNode] Done: 24460`

**Comment by f4nu** [comment]
That's it, my game is #21922 but the link on the header is pointing at jabba's game. Thank you!

Should I proceed with the editable one?

**Comment by zwrawr** [comment]
Yea, we need to add a UI option to switch between unauthored games in the mean time you can edit the url and replace the game id's with the ones that are in the consoe log. For you these are

https://ldjam.com/events/ludum-dare/38/$21922
and
https://ldjam.com/events/ludum-dare/38/$24460
