### ISSUE TITLE
Clicking the logo when on ldjam.com should scroll to top

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#785]
Websites like twitter implement this functionality and I've found myself attempting to to it on ldjam.com, Clicking on the `LudumDare` logo should scroll up to the top of the page like this.

![ld38_4](https://cloud.githubusercontent.com/assets/18352787/25359037/8213442e-293b-11e7-97fd-d630074e7646.gif)

This will be more important once #725 is addressed.

**Comment by povrazor** [comment]
Dialogs are doing some manipulation of scroll position. They need to be fixed too.

**Comment by Noojuno** [comment]
Fixed in #795
