### ISSUE TITLE
Can not publish or edit game description on ldjam, published on itch.io

### ISSUE THREAD

**Issue by shiitman** [ludumdare/ludumdare#786]
https://shiitman.itch.io/stardust
The game was submitted before the deadline.

I can not edit Game page at ldjam, I even can not figure out, if game was published, or is it still a draft. Images could not be uploaded either.

**Comment by povrazor** [comment]
Images are limited to 4MB, but the server is super saturated right now. Give it a little more time and try again. I will be keeping submissions open later because of the unresponsiveness.

**Comment by povrazor** [comment]
Looks like it got through.

https://ldjam.com/users/shiitman/games
