### ISSUE TITLE
Links do not open in new tab with Ctrl+Click (Cmd+Click)

### ISSUE THREAD

**Issue by Gipzo** [ludumdare/ludumdare#791]
Ctrl+Click on links opens them in same page. 'Open Link in New Tab' in context menu works fine.

It is rather frustrating, especially when creating blog post.

Same problem with Shift+Click. This must open link in new window, and now it is opening in same tab instead.

**Comment by zwrawr** [comment]
I thought this was part of the browser rather than the site. Uts possible
the react router is catching these links. If so it needs to be altered to
respect link targets eg target=_blank

**Comment by Gipzo** [comment]
It is not about link targets as link should normally open in same tab.
Also I think it is not a bug, just a feature request to add ctrl(cmd) and shift modifier detection to click handler.

**Comment by povrazor** [comment]
Yeah it is probably something we need to add. We are preventing the website from actually loading pages, because we can do it cheaper. It's completely fair that you might want to open something in a new tab.

**Comment by Noojuno** [comment]
Fixed in #795

**Comment by noah-potter** [comment]
The middle mouse button usually has the same behavior as well.

**Comment by Noojuno** [comment]
In my testing the middle mouse button worked

**Comment by noah-potter** [comment]
Yup, looks like it works. Maybe it was an issue with that computer. It works on the one I'm using now.
