### ISSUE TITLE
Comments keep rescrolling window

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#798]
In `FireFox 52.0.2 (32-bit)` on `Windows 10` commenting on a game that had about four comments while writing a lengthy comment made the bottom of the comment (where I was writing) keep scrolling out of view.

**Comment by povrazor** [comment]
I've noticed something similar in posts on Chrome. When a post is too tall (larger than the browser window), it jumps around a bit.

**Comment by povrazor** [comment]
#845

**Comment by povrazor** [comment]
This should be fixed.

**Comment by local-minimum** [comment]
I've enjoyed writing long comments all day without any issues.
