### ISSUE TITLE
Automatic Hyphenation in text is too agressive

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#799]
The record I've gotten is `it` being split into `i-` and `t` on the following line. There ought to be a minimum length of what will be left on line (3 or so) and min length of what may be moved down (3 or so) and if this is not valid, make entire word go to next line.

**Comment by povrazor** [comment]
Funny thing, it's actually a modern browser feature (it's not even supported in Desktop Chrome).

**Comment by zwrawr** [comment]
For reference https://caniuse.com/#feat=css-hyphens

**Comment by povrazor** [comment]
If it's an issue, we'll just disable hyphens entirely.
