### ISSUE TITLE
Game Submission: Add inline help for each part of the submission process

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#81]
The original guide (found at the bottom of the page).

> Mini Submission FAQ
> 
> TEAMS: Teams entering the Jam should pick a single representative to submit your game, or create a team specific account you can share. We currently do not support Team Voting, but sharing an account and together playing and rating games is acceptable.
> 
> CAN I ENTER BOTH EVENTS?: You should pick 1 event, whichever you think it’ll do better in. If the idea is strong, and everything plays well enough, you can go Compo. If you’re a perfectionist, and would prefer people to play a more polished game, do the Jam. Historically, more games are entered in the Compo, but with more people and more time, Jam games have the potential to be better (that doesn’t mean they are). Many solo participants do enter the Jam.
> 
> If you made 2 games, unfortunately, the website doesn’t support multiple submissions per user. To submit your 2nd game, you will have to make a 2nd account. Only do this if you made 2 games. Alternatively, if one game is better than the other, then consider just entering the better game.
> 
> CAN I KEEP WORKING UNTIL THE DEADLINE?: Yes! Immediately after the 48 or 72 hours, we do something called Submission Hour. As the name suggests, it’s an extra hour for you to package, upload, and submit your games. If there were catastrophic issues trying submitting your game, or you misunderstood how submissions work, that’s okay. It happens. We’re flexible. If you need advice, check with the folks on IRC. If you need an admin, get in touch.
> 
> CAN I KEEP WORKING ON MY GAME?: Oh definitely! You should! But for the sake of judging, keep the Compo or Jam version around. You can include a link to the Post-Compo/Post-Jam version of your game on your games page, but sure your main links are the original version.
> 
> PORTS: Ports to other platforms can be done after the deadline. That said, the sooner you finish your port, the sooner people can play your game, improving your chances of placing in the final results. For best results, provide a Web version of your game, or a Windows version with no dependencies. Also be sure to rate at least 20 games to improve your visibility (Coolness).
> 
> MY GAME CRASHES, IS UNBEATABLE, OR I MADE A TYPO: We allow you to fix crashes, win condition, or tiny bugs after the deadline. In a sense, this is like “porting” to support more players. We leave this open to interpretation, but generally speaking your game should be identical to the game you submitted. No new features, just fixing mistakes you should have caught had you been better rested.
> 
> MY GAME DOESN’T SHOW UP: If you can’t find your game, it’s usually because the URL to your downloads are missing ‘http://‘. Fix your URLs (http://mysite.com/mygame.zip) and you will show up. Alternatively, if you just posted it, wait a minute. The cache may not have refreshed yet.
> 
> NOT LOGGED IN?: If you get a message about not being logged in, even though you are, it’s because your web browser cached the non-logged in page. You can fix this by either refreshing your cache or clearing your cache. CTRL+F5 in many browsers. Chrome is a bit more work. Press F12 to enable Developer Mode, then you can right click on the refresh button and select “Empty Cache and Hard Reload”. This option is unavailable if you are not in Developer Mode.

The new site should also have mini help guides per section, if needed. Collapsed at first, but (if possible) obvious that they are available.

**Comment by povrazor** [comment]
![submissionfo](https://cloud.githubusercontent.com/assets/1570313/21125680/57388942-c0b5-11e6-8ef5-8ccda2035bc3.png)

![submissionfo2](https://cloud.githubusercontent.com/assets/1570313/21125682/5c3d8cda-c0b5-11e6-8ffa-3df179a38ece.png)

![submissionfo3](https://cloud.githubusercontent.com/assets/1570313/21125685/608d5cca-c0b5-11e6-9d20-9aed2b8383ba.png)

**Comment by povrazor** [comment]
![submitbuu](https://cloud.githubusercontent.com/assets/1570313/21127065/2f26b6fa-c0be-11e6-96e1-84b290a83f40.png)

More bad UX, you need to click submit to commit your votes.
