### ISSUE TITLE
Game Browsing UX

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#825]
#493 

![browse-ux](https://cloud.githubusercontent.com/assets/1570313/25566972/d9805b3c-2db1-11e7-9bb0-61d1a2bee4f0.png)

Okay, so here's browsing right now. There's no filtering.

I'm thinking of adding a 2nd row for the filters, but visual wise 2 rows of dark icons wont be that great looking. So in this issue I'm looking for feedback how to make the 2 rows look decent and be useful.

My current thought is making the 1st row (the row you see right now), give it a light background, and use the dark style (what you see now) for the filtering options.

```
[All] [Jam] [Compo]
```

Currently the only filters that are supported (not visible to the user) are those above. I.e. show all games, all jam, all compo. Also, each of those is just listing all games in reverse order.

For now, once coolness calculating is working, I can just make those sort by coolness. But later on we need to give choices, to filter by coolness, popularity, date published, etc.

And the other important detail: filtering needs to be mobile friendly.

I'm thinking of a drop-down box, merging `all, jam, compo` in to a single drop down, and making the sorting order another one. I would imagine that's all the width used on Mobile.

In addition, we need to be able to filter by tags. That probably goes on the next line (one of those rows of `(x) Tag Name` things). That and a button to add a new filters.

![steamy](https://cloud.githubusercontent.com/assets/1570313/25567039/3a2d5c7c-2db3-11e7-8852-f29f89bed00a.png)

Not sure how useful Steam is as reference, but it is an example of tag filtering.

**Comment by local-minimum** [comment]
One obvious thing, just to have it mentioned here is platform support / web as something to filter on.

**Comment by povrazor** [comment]
Closing this, and moving to #867
