### ISSUE TITLE
Uploaded game image distortion

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#838]
The uploaded image gets distorted / blurred even if it matches the resolution specified which isn't kind on sharp games.

![blur](https://cloud.githubusercontent.com/assets/8041100/25588360/4591bc84-2ea8-11e7-8ea9-d0beb49c9a8b.png)

**Comment by povrazor** [comment]
Yeah, I'm actually scaling them down to 75% of that. You're actually not supposed to see them that large (bug).
