### ISSUE TITLE
Comments: Highlight any comment by a Post/Game author/team

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#84]
That

**Comment by povrazor** [comment]
![inv-name](https://cloud.githubusercontent.com/assets/1570313/20857812/a709cc32-b904-11e6-8491-fba620dcdaea.png)

I like this means of highlighting. Stolen from YouTube.

**Comment by ALobker** [comment]
I would like to make a small addendum:
Please also highlight comments that were made by the user that is logged in. This makes it easier to find your own comments.

**Comment by local-minimum** [comment]
On a technical side, could this be handled by shrub?

`$Node.IsAuthor(nodeId, authorId, includeCoAuthors)`

And similar for `$Note`?

That way we don't need the check reimplemented all over the place and they can fetch whatever n needed not in the cache. Only issue is that it would have to return a promise.

**Comment by local-minimum** [comment]
Yes I was considering 'author' 'me' 'mention'

**Comment by mikekasprzak** [comment]
Ooh "mention", thats a good idea too.


On Aug. 11, 2018 15:06, "Martin Zackrisson" <notifications@github.com>
wrote:

Yes I was considering 'author' 'me' 'mention'

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ludumdare/ludumdare/issues/84#issuecomment-412295469>,
or mute the thread
