### ISSUE TITLE
Remind judges of type of entry (compo/jam) next to Ratings

### ISSUE THREAD

**Issue by scriptorum** [ludumdare/ludumdare#840]
I think most of us hold a jam entry to a higher standard than a compo entry. Therefore a 5 star jam has to impress more than a 5 star compo would. Some comments have made me think not all folks are aware if they're rating a jam or a compo entry. I'm recommending changing the RATINGS header to say COMPO RATINGS or JAM RATINGS as a reminder.

In the long term it probably doesn't make much of a difference. 😜  *:low_priority: :emoji_missing: #shut_up_eric_and_rate_more_games*

**Comment by zwrawr** [comment]
I'd even go for adding the whole thumbnail thing next to the ratings, but that is probably over kill.
![image](https://cloud.githubusercontent.com/assets/18352787/25762802/237a074a-31d8-11e7-91e2-a434b7d8f316.png)

I'm guessing your suggesting something more like 
![image](https://cloud.githubusercontent.com/assets/18352787/25763001/0440fd1a-31d9-11e7-95e7-0cf130237a32.png)

**Comment by scriptorum** [comment]
@zwrawr Yes, that's my suggestion, because it seems trivial to implement, but your approach would have the same effect. I also wouldn't mind the entry type being repeated near the draft post text box, again to remind users to to consider the entry type before commenting.

**Comment by zwrawr** [comment]
I probably have fix for this, need to get my VM to the stage of an event where it shows the ratings view before i can test it.

**Comment by povrazor** [comment]
Should be fixed in #860
