### ISSUE TITLE
[UI] Show coolness of User/User's game

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#848]
*
    > **XAVIER_INDIE_GAMEDEV (@xavier-indie-gamedev)**
        *posted 2 days ago (edited)*
        Question: I know we can’t see our ratings until it ends, but are we able to keep track of our coolness %?
    >
    >   It’d be nice to know how much more rating/feedback giving we had to do to actually appear reasonably near the top in the ‘/games’ list

*
    > **lepatryckduffy (@lepatryckduffy)**
        *posted a day and a half ago*
    >
    >   @pov We can see our colness score ?

pov mentioned in a comment that'd this would probably be added at some point but there wasn't a issue for it.

**Comment by karai17** [comment]
Yeah it would be really handy to know when we've hit the minimum threshold.

**Comment by povrazor** [comment]
I got started on this last night, but switched priorities to showing all games on user pages.

**Comment by karai17** [comment]
I think this might be higher priority since it immediately affects the current judging process.

**Comment by povrazor** [comment]
It's already done (for now at least). Oddly I've had more requests for user pages working right than knowing how many votes, but they are both up there.

**Comment by karai17** [comment]
ETA on push to production?

**Comment by povrazor** [comment]
It's been live since last night (i.e. game page listings, not coolness).

**Comment by karai17** [comment]
ETA on coolness?

**Comment by povrazor** [comment]
Sometime tonight. You can see the stub for it on your game pages now.

**Comment by karai17** [comment]
Cool (heh), I look forward to it.
