### ISSUE TITLE
Emoji stopped working (:heavy_check_mark:)

### ISSUE THREAD

**Issue by scriptorum** [ludumdare/ludumdare#855]
This emoji stopped working: :heavy_check_mark: (`:heavy_check_mark:`). It was displaying properly, but now it displays like this: `heavy,_check,_mark`. I haven't noticed any other affected emojis.

**Comment by zwrawr** [comment]
@Noojuno basically rewrote the entire marked markdown parser, there's probably a couple of broken things.

**Comment by scriptorum** [comment]
@zwrawr Ah okay. Feel free to retitle or close this issue.

**Comment by zwrawr** [comment]
Should be easy to fix, somewhere the emoji name is being split up into an array, just got to find out where (or just concat them properly)

**Comment by zwrawr** [comment]
I've PRed a fix #857
