### ISSUE TITLE
Post editor broken

### ISSUE THREAD

**Issue by gatechgrad** [ludumdare/ludumdare#858]
After text fills up the text editor box, it will force the browser to scroll back up to the top of the page whenever a key is pressed.  This essentially makes it impossible to have a post longer than what the text box can hold without scrolling, unless you compose your post in another text editor and paste it in the text box.

**Comment by zwrawr** [comment]
Related to #798

**Comment by povrazor** [comment]
Also #845

**Comment by povrazor** [comment]
This should be fixed
