### ISSUE TITLE
Number of ratings per category

### ISSUE THREAD

**Issue by pfefferminzz** [ludumdare/ludumdare#859]
Hi,

in my opinion, it would be good to know how many ratings a game recieved in the individual rating categories, yet. Quick mockup:

![ldratings](https://cloud.githubusercontent.com/assets/5459440/25792841/655931e8-33c9-11e7-97ec-c4dba0a4304c.png)
(After the very first rating of this game.)

How many ratings does a game need to be ranked?

Best regards,
Christian

**Comment by zwrawr** [comment]
If i remember correctly and if its the same as before, then you need votes
from 20 people (I think?)

**Comment by pfefferminzz** [comment]
People? Or votes in the respective category to be ranked in this category? There has not been written in the /news about it, afaik.

**Comment by povrazor** [comment]
#848

**Comment by zwrawr** [comment]
Fixed by #872 
![image](https://cloud.githubusercontent.com/assets/18352787/25897242/2e801f76-357f-11e7-8a13-8479ac2d7425.png)

**Comment by pfefferminzz** [comment]
Great! Thanks!
