### ISSUE TITLE
File Limits?

### ISSUE THREAD

**Issue by Samusoidal** [ludumdare/ludumdare#881]
What is the daily upload limit for files? I know the individual limit is 4MB, but how much of that can I upload per session?
And can we boost it until external embedding works?

**Comment by zwrawr** [comment]
For context
@Samusoidal think he's hit some kinda of rate limit / session limit that's stopping him from uploading more images. It's possible that he's hit a hard maximum rather than a rate limit too.

**Comment by povrazor** [comment]
... there shouldn't be a number of uploads limit.

**Comment by Samusoidal** [comment]
Okay, ran some tests and it seems it's only certain .png files, it could be a problem on my end.
'Scuse me while I test it.

**Comment by Samusoidal** [comment]
Okay, it seems to be my paint.net settings that mess it up. Some PNGs won't upload but JPEGs will. PNGs that I've downloaded off of the website (like screenshots already uploaded) will upload fine.

**Comment by Samusoidal** [comment]
Yeah, it's definitely my PDN settings. Thanks for the time!
