### ISSUE TITLE
Feature - See Who's Following You

### ISSUE THREAD

**Issue by Samusoidal** [ludumdare/ludumdare#882]
A good feature would be to see who's following you, and how many followers you have.
Just thought I'd leave it here (under enhancement, maybe?).

**Comment by povrazor** [comment]
It's already implemented, but I had to disable it due to an issue.

**Comment by Samusoidal** [comment]
Okay, thanks!

**Comment by zwrawr** [comment]
Just replace the `following` with `followers` in the url
