### ISSUE TITLE
Inline code block: escapes text

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#883]
![image](https://cloud.githubusercontent.com/assets/18352787/25966734/c6d6849a-3683-11e7-8ecd-c44115b51618.png)

```markdown
### Markdown

'''md
spoilers
!> this is a spoiler
'''

Spoilers in inline code doesnt work `!> it's messed up`

```

**Comment by povrazor** [comment]
Ah, I see. It's not necessarily the `!>` tag, but things that need escaping.

**Comment by local-minimum** [comment]
Yes I found this on `'` too. So how does
```
!&gt;
```
look like? Like here spelled out or just a `>`? If the former, then it is _just_ a matter of making the inline thing work like the block thing. Right?

**Comment by povrazor** [comment]
Is this fixed? I can't remember. I merged a thing the other day.

**Comment by zwrawr** [comment]
Fixed !
![image](https://cloud.githubusercontent.com/assets/18352787/26035328/52e90b20-38c2-11e7-8651-25d823ba456f.png)
