### ISSUE TITLE
Self hearting

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#911]
![selfheart](https://cloud.githubusercontent.com/assets/8041100/26033165/2c2de22e-38a6-11e7-80ec-0a8b04c26d71.png)

I can heart my own comments. I can even heart my unwritten comments.

**Comment by zwrawr** [comment]
Most site allow you to like your own content, and they do hide it from you when posting.

Reddit is an interesting case where you automatically up vote your own comment when you post it.

**Comment by povrazor** [comment]
We're all for letting you be as vain as you want to be. :wink:

**Comment by povrazor** [comment]
Hearting unwritten comments should now be fixed.
