### ISSUE TITLE
To easy to follow people

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#912]
Especially for people who participated and not uploaded but even in general, it is too easy to click on follow, when really what you want is to get to their game in current event.

Suggestion, add the following button to the user-profile:
![gamebutton](https://cloud.githubusercontent.com/assets/8041100/26033340/81861f58-38aa-11e7-8321-debcd6a66397.png)

**Comment by zwrawr** [comment]
Adding a `LD 38 Game` button to users with no games does not help the user experience. It suggest that the user has authored games and when some one clicks it they will be taken to an empty page. 
And in the case of users who have published games your moving the game button even closer to the follow button, and so your more likely to hit follow by accident.

I don't think we should add a `LD 38 GAME` button to user for the reason you suggested, but i may be worth considering for other reasons.  
After a couple of LD's (or jammer being a thing). Users game pages are going to be quite full. So adding a quick link to games from the featured event might be a good idea.

**Comment by local-minimum** [comment]
I didn't mean for ppl without games, then it really shouldn't be there. But right now if you were part of a team you don't get the games below the user profile while the game is listed on your games (separate bug), and even more in that case it would be nice with game link in profile to current event.

**Comment by povrazor** [comment]
Yeah, I'm using the wrong method to calculate the total number of games belonging to a node right now, so the games button doesn't know to appear.

**Comment by Cerno-b** [comment]
How about instead you make the Game list the default and not the Feed? I would argue that most people are more interested in what games someone made, instead of what they wrote.

**Comment by local-minimum** [comment]
Well @Cerno-b, if there are hotlinks to games entered in currently active event, then the feed is probably nicer, but it could be a quick fix before that logic is in.

**Comment by Cerno-b** [comment]
I guess if the games appear next to the name in the feed then having the feed as the default would be better I agree.

**Comment by povrazor** [comment]
A bunch of restructuring needs to happen on user pages. I forget the issue, but I like how event pages have a row of buttons in the post bottom itself, that outright change what is going on below (theme selection, results, etc).
