### ISSUE TITLE
Metadata and Linkage implementation unnecessarily complex

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#914]
In working with the improved feed code, I'm running in to bugs that lead to more complex queries.

It seems **mysql**, the way it handles the `MAX(number)` function is that it quite literally gives you the maximum value. It doesn't actually act as a sorting mechanism, so once you know the ID of a maximum, you need to perform a 2nd outer query to utilize it. If I had control of the read order in a `GROUP BY` query I could work around this issues, but alas it seems I don't (`ORDER BY` changes output order, not input). 

If the number of returned fields by queries further down the chain is low, then this isn't a big deal, it's just (as the title suggests) unnecessarily complex.

Generating feed queries require some kung fu to manage properly. I believe I have it working now, but every time I try to get clever (authors, tags, etc), it's more frustrating to implement than it needs to be.

## Solution
Split metadata and linkage in to two tables each:
* One for values
* One for history

As before, when nodes are "deleted", their `scope` goes negative. The difference being that the history of changes no longer populates the same table.

The advantage of the current system is that it takes less disk space, and is faster to insert (because it's just 1 table). The solution would be slower to insert, and take more space, but would `SELECT` much faster and greatly simplify writing complex queries.

**Comment by povrazor** [comment]
Another missing feature of metadata and links is patching. Currently there is no way to describe a change-set for anything other than nodes and notes. Patching is a complicated subject, and I haven't even put any thought in to how to fully implement it, but metadata needs to be part of it (even if it isn't visible to the user).

**Comment by local-minimum** [comment]
Looking at https://stackoverflow.com/questions/6881424/how-can-i-select-the-row-with-the-highest-id-in-mysql#6881429 the most popular answer is to `ORDER BY` while there's also a solution with max. My guess is that the votes mean `ORDER BY` is more efficient.

**Comment by povrazor** [comment]
The issue is that it takes 2 queries (main and subquery), where it could take 1.

**Comment by povrazor** [comment]
Technically speaking Metadata and Links could be merged in to a single datatype. Metadata being data with either 0 as `b`, or `a` and `b` being the same (`0` makes it easier to detect).

**Comment by mikekasprzak** [comment]
This is done (and it's much better).
