### ISSUE TITLE
The new "Jamming" mixed view

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#952]
If you're a participant in the current active event, your default homepage should be taylored to you and the event.

![jammview](https://cloud.githubusercontent.com/assets/1570313/26171205/1b06e4e6-3b12-11e7-943a-e5d580567bc1.png)

Super rough mockup. To avoid confusion with `Jammer`, I'm thinking the tab should be named `Jamming`. Participant/Participation is just a crappy word. :wink:

The idea is this is a brand new mixed view. It combines smaller versions of other views, while putting key information you care about on top.

At the top is data about your game. Similar to the data shown in Metrics, plus a few things only you and your team care about.

Next is a mini "games you should play" section. A single row of games based on your personalized filtering criteria. Here you can also define that criteria. Typically this is picking the platform you run/have available to you (Windows, Linux, Android, etc), but there may be a reason to allow other tags. When you later visit /games pages, these can carry over as your defaults. There should be a link/button to view more games here, which takes you to the correct place (i.e. `/event/ludum-dare/38/games`, and not `/games`).

After that is the same minimized news item found on the feed page, followed by the feed.

Ludum Dare 38's feed was filled with a lot of self promotion/spam posts during the event, so I'm thinking this feed after the news should actually be a popular feed (i.e. posts with hearts). This way it's more effective at highlighting thing you may care about, like new tools and things from the community.

**Comment by povrazor** [comment]
It might be worth making a version of this available to users that didn't participate/finish. Only participants can actually give ratings in official categories, but everyone is free to give feedback. 

This would not be the default view, but something that can be selected, or triggered/enabled by other conditions (adding yourself to an event as a media correspondent).

Users that decide to participate here (either with unfinished games or as media) can earn placement in a 2nd pool of coolness winners (Community Winners). In this case, their scores will be based on Feedback Karma and Bonus Points.

**Comment by ajayyy** [comment]
Just to give my opinion, one of the things I love about Ludum Dare is that anyone can post something and it is immediatly placed on the front page. I think replacing this with a popular feed would ruin the feeling of openness of LD.

**Comment by local-minimum** [comment]
Just to add what I said on #956, it would be good if there's a bottom banner on game pages too, because that's where you end up after you have written a comment and that's when you need to get to the next game to rate.

**Comment by egordorichev** [comment]
Why is the lazy loading so slow?

**Comment by povrazor** [comment]
> Why is the lazy loading so slow?

Couple reasons, but long story short it's not optimized.

For a URL
* Walk the tree (i.e. figure out the node from the URL)
* Load the node (separate call, cached both client and server side)
* Load the authors (where applicable)
* Possibly load the parent node.
* Load all the posts (if a feed)
* Load all their authors (should happen sooner, and together with other post)

I'm sure I've missed a step too.  Many if these can be merged in to fewer calls. Just hadn't had free time to tackle it.

**Comment by local-minimum** [comment]
can we close this one now?

**Comment by mikekasprzak** [comment]
Sure. I think the intent for this was just to differentiate between the homepage, the feed, the news, etc. Even most of the batching mentioned a comments ago is now in (alas the DB server is still choking, but it should be more responsive). 

There is more information I want in (suggested by "data" above), but that's super vague and no reason to keep this open for.
