### ISSUE TITLE
Game browsing should open in new tab

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#956]
There are a bunch of clicks right now to get back to `https://ldjam.com/games` so I think either we need a link at the top like `My Game` or we need the games feeds to open in new tabs when you click on them. I get that this breaks the logic of internal pages open in same tab, but I think it will be helpful. We want retain people voting and commenting on games as long as possible so they need to end up in game selection as quickly and easily as possible.

**Comment by zwrawr** [comment]
Why not `Ctrl+left-click` or `middle-click` or `right-click` or `long-press` on mobile. This is a built in feature of every browser i've ever used. I don't think it's some thing we need to duplicate.

**Comment by local-minimum** [comment]
Well it is too easy to simply click and then it is a bit of a hassle to get back to the game list and really I see it as our job to make the site so people keep rating game when they've started. Previous site you automatically got back to games list after voting. That doesn't work now, but we need something that makes transition to next game really easy.

But if #952 is implemented and perhaps adds a banner at the very bottom too, especially on game pages, then this is a non-issue.

**Comment by zwrawr** [comment]
A `Back To Games` button at the bottom of the game post seems like a reasonable idea. 
It could appear once you've rated > 1 catogorey.

**Comment by local-minimum** [comment]
That would be nice, especially if we deal with pagination and that link actually sends you back to where in the feed you were.
