### ISSUE TITLE
Countdown to the end of Judging.

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#957]
For the next LD we should make the sidebar clock count down to the end of judging.

**Comment by local-minimum** [comment]
This would be great as it would be the data I need for my suggestion for better handling of `danger` list on #971

**Comment by povrazor** [comment]
I've been hardcoding the schedule instead of finishing the schedule page. I really want this working properly internally

**Comment by zwrawr** [comment]
This was implemented 
![screenshot from 2017-12-11 07-22-24](https://user-images.githubusercontent.com/18352787/33819786-1fb90002-de44-11e7-9f90-d0c267b18107.png)
