### ISSUE TITLE
Permalink letsplay list

### ISSUE THREAD

**Issue by Cerno-b** [ludumdare/ludumdare#969]
I would like to have a permanent link to the right of the site (below the streamer box) where streamers or letsplayers can post their forms for people who want their games played.

I may be a bit dense but I often miss the posts that collect that sort of information, so it would be nice to have it in one specific spot. It would be even cooler if you had a section on the website where the organization of streams and creator could take place, so not everyone has to use different spreadsheets and such. It may also make contacting creators when their game has been played easier.

There are disadvantages of course, since some streamers may prefer to collect information not available on the LD site. Also making it overly hassle-free to get onto a list (like adding a button that adds your game to all lists) might unnecessarily swamp the streamers.

Anyway, the permalink to a current LD's list of streamers would be neat.

While at it, keep other types of posts there as well, like organizing live meetings and such.

**Comment by zwrawr** [comment]
Defiantly need something like this.

So when voting opened this time, pov made a post where streamer and lets players could post there lists. This wasn't pinned to the top as only one item can be pinned to the top, I think something similar to your sidebar idea could work.

What i'd suggest is having a section in the side bar where the titles of recent news posts are displayed. E.g. The currently pinned post might be `Jam is over, Voting has opened` but this side bar list could be

>   * Streaming and Lets Play List
>   * Jam is over, Voting has opened
>   * Compo is over
>    * Theme Announcement

**Comment by Cerno-b** [comment]
Here you mentioned alternative Feeds: https://github.com/ludumdare/ludumdare/issues/993

But this issue would be a bit different, right? As these would be fixed announcements that work like pinned posts but in a different place so they don't take up all the website real estate.

These points of information are fixtures in every LD and I agree that they need a specific place where they can live permanently during the jam.

**Comment by povrazor** [comment]
This isn't a good example, but I think what I'd rather do is further condense minimized posts, starting with something like this:

https://github.com/ludumdare/ludumdare/issues/767

Packing the height more, removing gaps, and having the 2-3 most recent news items instead of just 1.

**Comment by Cerno-b** [comment]
I see, I hadn't paid attention to the needs of mobile users. 

Do you generally follow a style where the desktop and mobile versions of the site have to look the same?
Because I could see the sidebar being used for quite some useful things, that could be placed in a different manner on mobile devices.

Concretely, you could go with https://github.com/ludumdare/ludumdare/issues/767 on the mobile version and put the same info in the sidebar on the desktop version.

I don't have any insight into the design process though, so keeping everything the same may be easier to maintain.

Anyway, I'm fine with any solution that keeps the important posts accessible throughout the jam and doesn't eat up all the space.
