### ISSUE TITLE
Featured Posts

### ISSUE THREAD

**Issue by Cerno-b** [ludumdare/ludumdare#993]
I hope this is not a duplicate again :)

So there has been discussion about keeping posts with many likes on top of the feed for longer, and a counterargument is that it clogs the feed, which I agree on. Still, I think it would be helpful to give interesting posts a bit more exposition.

My suggestion is to have a list of featured posts on the sidebar of the website. This would be a list of headlines of the recent 10 most interesting posts. The list could be sorted by a score that takes into account number of likes, number of comments and how recent the comments were. The score should also decay over time, so that topics of interest can remain on the list longer.

Maybe this could be organized as an alternative feed where entries are not ranked by time but by the score mentioned above. The top 10 entries of that featured feed could be shown on the sidebar.

**Comment by zwrawr** [comment]
Right now we only show the main feed `ALL`

Eventually there will probably be `ALL`, `FOR YOU`, `POPULAR`

**Comment by Cerno-b** [comment]
Exactly, perfect!

What's the FOR YOU one about? When people I follow post something?

**Comment by zwrawr** [comment]
Yup, people/groups/communities

**Comment by povrazor** [comment]
Closing to avoid confusion with Post Featuring.
